using System.Collections.Immutable;
using System.Text;
using tsbindgen.Analysis;
using tsbindgen.Core;
using tsbindgen.Emit.Printers;
using tsbindgen.Model.Symbols.MemberSymbols;
using tsbindgen.Renaming;
using tsbindgen.Model;

namespace tsbindgen.Emit;

/// <summary>
/// Emits extension method bucket interfaces to __internal/extensions/index.d.ts.
/// Buckets are scoped by declaring namespace (C# using semantics).
/// Example: __Ext_System_Linq_IEnumerable_1&lt;T&gt; contains Where, Select, etc.
/// </summary>
public static class ExtensionsEmitter
{
    private static string GetShapeTypeExpressionForConditional(ExtensionBucketPlan bucket, string targetNamespaceAlias)
    {
        // For TS primitives, always match against the TS primitive keyword type.
        // This prevents extension method availability from depending on global interface augmentation.
        //
        // Example:
        //   System.String is emitted as `type String = string & ...`
        //   Without global augmentation, `string` does not extend `System.String`.
        //   But users will naturally write `ExtensionMethods<string>`, so we must match `string`.
        var target = bucket.TargetType;
        if (target.Namespace == "System")
        {
            return target.TsEmitName switch
            {
                "String" => "string",
                "Boolean" => "boolean",
                "Double" => "number",
                _ => $"{targetNamespaceAlias}.{target.TsEmitName}",
            };
        }

        return $"{targetNamespaceAlias}.{target.TsEmitName}";
    }

    /// <summary>
    /// Emit the __internal/extensions/index.d.ts file containing all bucket interfaces.
    /// </summary>
    /// <param name="ctx">Build context</param>
    /// <param name="plan">Extension methods plan with all buckets</param>
    /// <param name="graph">Symbol graph for type resolution</param>
    /// <param name="outputDirectory">Root output directory</param>
    public static void Emit(BuildContext ctx, ExtensionMethodsPlan plan, SymbolGraph graph, string outputDirectory)
    {
        if (plan.Buckets.Length == 0)
        {
            ctx.Log("ExtensionsEmitter", "No extension methods found - skipping extensions file");
            return;
        }

        ctx.Log("ExtensionsEmitter", $"Emitting extension method buckets: {plan.Buckets.Length} buckets");

        // Create __internal/extensions directory
        var extensionsDir = Path.Combine(outputDirectory, "__internal", "extensions");
        Directory.CreateDirectory(extensionsDir);

        // Generate file content
        var content = GenerateExtensionsFile(ctx, plan, graph);

        // Write file
        var filePath = Path.Combine(extensionsDir, "index.d.ts");
        File.WriteAllText(filePath, content);

        ctx.Log("ExtensionsEmitter", $"Wrote {filePath}");
    }

    /// <summary>
    /// Generate the complete extensions file content.
    /// </summary>
    private static string GenerateExtensionsFile(BuildContext ctx, ExtensionMethodsPlan plan, SymbolGraph graph)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Extension Method Buckets");
        sb.AppendLine("// This file contains bucket interfaces for C# extension methods.");
        sb.AppendLine("// Buckets are scoped by declaring namespace (C# using semantics).");
        sb.AppendLine("// For each namespace with extension methods, this file exports an ExtensionMethods_<Namespace> helper.");
        sb.AppendLine();

        // Collect all namespaces used in extension method signatures
        var namespacesUsed = new HashSet<string>();
        // Track the actual referenced CLR full names per namespace so we can choose an
        // import source package in --lib mode even when a namespace is split across packages.
        var namespaceToClrFullNames = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var bucket in plan.Buckets)
        {
            // Add the target type's namespace (needed for ExtensionMethods_<Namespace> helper)
            namespacesUsed.Add(bucket.TargetType.Namespace);

            // Also record the receiver type's CLR full name so --lib import planning can resolve
            // namespaces even when only the receiver (and not any parameter/return types) appears.
            if (!string.IsNullOrEmpty(bucket.TargetType.Namespace))
            {
                if (!namespaceToClrFullNames.TryGetValue(bucket.TargetType.Namespace, out var set))
                {
                    set = new HashSet<string>(StringComparer.Ordinal);
                    namespaceToClrFullNames[bucket.TargetType.Namespace] = set;
                }

                set.Add(bucket.TargetType.ClrFullName);
            }

            foreach (var method in bucket.Methods)
            {
                // Collect from return type
                CollectNamespaces(method.ReturnType, namespacesUsed, namespaceToClrFullNames, graph);

                // Collect from parameters (skip first 'this' parameter)
                foreach (var param in method.Parameters.Skip(1))
                {
                    CollectNamespaces(param.Type, namespacesUsed, namespaceToClrFullNames, graph);
                }

                // Collect from generic constraints
                foreach (var genParam in method.GenericParameters)
                {
                    foreach (var constraint in genParam.Constraints)
                    {
                        CollectNamespaces(constraint, namespacesUsed, namespaceToClrFullNames, graph);
                    }
                }
            }
        }

        // Generate namespace imports
        // Extension methods file is at __internal/extensions/index.d.ts
        // Local namespaces are at ../../{Namespace}/internal/index.js
        // External namespaces (from --lib contracts) are imported via package specifiers
        // (e.g., @tsonic/dotnet/System.Linq/internal/index.js).
        var localNamespaces = graph.Namespaces.Select(n => n.Name).ToHashSet();
        var namespaceAliasByPackage = new Dictionary<(string Namespace, string Package), string>();
        Func<string, string, string, string>? facadeNamespaceAliasResolver = null;
        if (namespacesUsed.Count > 0)
        {
            static string SanitizePackageAlias(string pkg)
            {
                // Convert an npm package specifier (e.g., "@tsonic/dotnet", "microsoft-foo-types")
                // into a TS identifier-safe suffix.
                var sb = new StringBuilder(pkg.Length);
                foreach (var ch in pkg)
                {
                    if (char.IsLetterOrDigit(ch))
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append('_');
                    }
                }

                var s = sb.ToString().Trim('_');
                if (s.Length == 0)
                    return "pkg";

                // Identifiers can't start with a digit.
                if (char.IsDigit(s[0]))
                    return "_" + s;

                return s;
            }

            string GetNamespaceModuleImportPath(string ns, string? pkg)
            {
                if (string.IsNullOrEmpty(ns))
                {
                    // Root namespace is always local within the output package.
                    return "../../_root/index.js";
                }

                var outputName = NamespacePathMapper.GetOutputName(ns, ctx);

                // Local namespace: relative import within this output package.
                if (localNamespaces.Contains(ns) || ctx.LibraryContract == null || pkg == null)
                {
                    return $"../../{outputName}/internal/index.js";
                }

                return $"{pkg}/{outputName}/internal/index.js";
            }

            // Build deterministic per-(namespace, package) imports in --lib mode.
            // Airplane-grade: if a namespace is split across multiple packages, we import all
            // contributing namespace modules and qualify type references based on the owning package
            // of each referenced CLR full name (LibraryContract.GetPackageForClrFullName).
            var namespaceImports = new List<(string Namespace, string Alias, string ImportPath)>();

            foreach (var ns in namespacesUsed.OrderBy(n => n, StringComparer.Ordinal))
            {
                var baseAlias = GetNamespaceAlias(ns);

                // Local namespaces (or non-lib mode): single import as before.
                if (string.IsNullOrEmpty(ns) || localNamespaces.Contains(ns) || ctx.LibraryContract == null)
                {
                    var importPath = GetNamespaceModuleImportPath(ns, pkg: null);
                    namespaceImports.Add((ns, baseAlias, importPath));
                    continue;
                }

                // External namespace in --lib mode: import one module per contributing package.
                var referenced = namespaceToClrFullNames.TryGetValue(ns, out var clrs) ? clrs : null;
                if (referenced == null || referenced.Count == 0)
                {
                    // We should always have at least the receiver type recorded. Keep strict behavior
                    // rather than guessing.
                    throw new InvalidOperationException(
                        $"No referenced CLR types recorded for namespace '{ns}' in extension bucket emission. " +
                        "This indicates a tsbindgen bug in namespace collection.");
                }

                var pkgs = referenced
                    .Select(ctx.LibraryContract.GetPackageForClrFullName)
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(p => p, StringComparer.Ordinal)
                    .ToList();

                if (pkgs.Count == 0)
                {
                    throw new InvalidOperationException(
                        $"No owning packages resolved for namespace '{ns}' in extension bucket emission.");
                }

                // Choose a canonical package for the base alias so existing code that hardcodes
                // certain namespace aliases (e.g., System.* constraints) remains valid.
                var canonicalPkg = pkgs[0];
                if (ns == "System")
                {
                    try
                    {
                        canonicalPkg = ctx.LibraryContract.GetPackageForClrFullName("System.Int32");
                    }
                    catch
                    {
                        // Fall back to deterministic sorted-first
                    }
                }

                foreach (var pkg in pkgs)
                {
                    var alias = pkg == canonicalPkg ? baseAlias : $"{baseAlias}__{SanitizePackageAlias(pkg)}";
                    namespaceAliasByPackage[(ns, pkg)] = alias;
                    namespaceImports.Add((ns, alias, GetNamespaceModuleImportPath(ns, pkg)));
                }
            }

            facadeNamespaceAliasResolver = (clrFullName, ns, defaultAlias) =>
            {
                if (ctx.LibraryContract == null)
                    return defaultAlias;

                if (string.IsNullOrEmpty(ns) || localNamespaces.Contains(ns))
                    return defaultAlias;

                var pkg = ctx.LibraryContract.GetPackageForClrFullName(clrFullName);
                return namespaceAliasByPackage.TryGetValue((ns, pkg), out var alias) ? alias : defaultAlias;
            };

            sb.AppendLine("// Import namespace modules for cross-namespace type references");
            foreach (var import in namespaceImports
                         .OrderBy(i => i.Namespace, StringComparer.Ordinal)
                         .ThenBy(i => i.Alias, StringComparer.Ordinal))
            {
                sb.AppendLine($"import * as {import.Alias} from \"{import.ImportPath}\";");
            }
            sb.AppendLine();
        }

        // Import primitive type aliases from @tsonic/core
        sb.AppendLine("// Import primitive type aliases");
        sb.AppendLine("import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';");
        sb.AppendLine();

        // Import Rewrap helper from @tsonic/core (sticky extension scopes across fluent chains)
        sb.AppendLine("// Import sticky extension scope helper");
        sb.AppendLine("import type { Rewrap } from '@tsonic/core/lang.js';");
        sb.AppendLine();

        // Import CLR primitive type aliases from System namespace
        // TypeRefPrinter's generic primitive lifting emits System_Internal.Int32/Char/etc.
        // This import must work in both normal mode (System emitted locally) and library mode (--lib @tsonic/dotnet).
        sb.AppendLine("// Import CLR type aliases for generic type arguments");
        {
            var systemNs = "System";
            var outputName = NamespacePathMapper.GetOutputName(systemNs, ctx);

            string systemImportPath;
            if (localNamespaces.Contains(systemNs) || ctx.LibraryContract == null)
            {
                systemImportPath = $"../../{outputName}/internal/index.js";
            }
            else
            {
                var pkg = ctx.LibraryContract.GetPackageForClrFullName("System.Int32");
                systemImportPath = $"{pkg}/{outputName}/internal/index.js";
            }

            sb.AppendLine($"import * as System_Internal from \"{systemImportPath}\";");
        }
        sb.AppendLine();

        // Import ptr from @tsonic/core (needed for pointer types)
        // Note: ref/out/in modifiers are ABI semantics tracked in metadata, not TS types
        sb.AppendLine("// Import unsafe type markers");
        sb.AppendLine("import type { ptr } from '@tsonic/core/types.js';");
        sb.AppendLine();

        // Create TypeNameResolver for this file
        // Extension methods file needs all cross-namespace types to be fully qualified
        // Use a dummy namespace "__internal.extensions" and enable facade mode
        // This triggers cross-namespace qualification for all type references
        var resolver = new TypeNameResolver(
            ctx,
            graph,
            importPlan: null,
            currentNamespace: "__internal.extensions",
            facadeMode: true,
            libraryImportStyle: Plan.LibraryImportStyle.InternalIndex,
            facadeNamespaceAliasResolver: facadeNamespaceAliasResolver);

        var (preferredBase, effectiveMethods) = ComputeBucketOverrides(plan, graph);

        // Emit each bucket interface
        foreach (var bucket in plan.Buckets)
        {
            EmitBucketInterface(sb, ctx, bucket, effectiveMethods[bucket], resolver);
            sb.AppendLine();
        }

        // Emit per-namespace ExtensionMethods_<Namespace><TShape> helper types
        EmitExtensionMethodsHelpers(
            sb,
            plan,
            getTargetNamespaceAlias: t => (facadeNamespaceAliasResolver ?? ((_, __, d) => d))(
                t.ClrFullName,
                t.Namespace,
                GetNamespaceAlias(t.Namespace)),
            preferredBase: preferredBase,
            effectiveMethods: effectiveMethods);

        return sb.ToString();
    }

    private static string GetNamespaceAlias(string ns) =>
        string.IsNullOrEmpty(ns) ? "_root" : ns.Replace('.', '_');

    private static string GetExtensionMethodsTypeName(string declaringNamespace) =>
        $"ExtensionMethods_{GetNamespaceAlias(declaringNamespace)}";

    /// <summary>
    /// Recursively collect all namespaces used in a type reference.
    /// </summary>
    private static void CollectNamespaces(
        Model.Types.TypeReference typeRef,
        HashSet<string> namespaces,
        Dictionary<string, HashSet<string>> namespaceToClrFullNames,
        SymbolGraph graph)
    {
        switch (typeRef)
        {
            case Model.Types.NamedTypeReference named:
                // Always add the declared namespace, even if the type is external (filtered out in --lib mode).
                // Relying on graph lookup causes us to miss external namespaces, producing missing imports.
                namespaces.Add(named.Namespace);
                if (!string.IsNullOrEmpty(named.Namespace))
                {
                    if (!namespaceToClrFullNames.TryGetValue(named.Namespace, out var set))
                    {
                        set = new HashSet<string>(StringComparer.Ordinal);
                        namespaceToClrFullNames[named.Namespace] = set;
                    }
                    // Use the CLR full name key used by LibraryContract.ClrFullNameToPackage.
                    set.Add(named.FullName);
                }

                // Collect from type arguments
                foreach (var arg in named.TypeArguments)
                {
                    CollectNamespaces(arg, namespaces, namespaceToClrFullNames, graph);
                }
                break;

            case Model.Types.ArrayTypeReference array:
                CollectNamespaces(array.ElementType, namespaces, namespaceToClrFullNames, graph);
                break;

            case Model.Types.ByRefTypeReference byRef:
                CollectNamespaces(byRef.ReferencedType, namespaces, namespaceToClrFullNames, graph);
                break;

            case Model.Types.PointerTypeReference pointer:
                CollectNamespaces(pointer.PointeeType, namespaces, namespaceToClrFullNames, graph);
                break;

            case Model.Types.NestedTypeReference nested:
                CollectNamespaces(nested.FullReference, namespaces, namespaceToClrFullNames, graph);
                break;
        }
    }

    /// <summary>
    /// Check if any method requires an IEquatable constraint for a type parameter.
    /// This happens when methods have "where T : IEquatable&lt;T&gt;" constraints.
    /// </summary>
    private static bool BucketNeedsIEquatableConstraint(IEnumerable<MethodSymbol> methods, string paramName)
    {
        foreach (var method in methods)
        {
            // Check if any of the method's generic parameters that match paramName have IEquatable constraint
            foreach (var genericParam in method.GenericParameters)
            {
                if (genericParam.Name == paramName)
                {
                    // Check constraints on this generic parameter
                    if (genericParam.Constraints != null)
                    {
                        foreach (var constraint in genericParam.Constraints)
                        {
                            // Check if constraint is IEquatable<T>
                            if (constraint is Model.Types.NamedTypeReference namedConstraint &&
                                namedConstraint.FullName.Contains("IEquatable"))
                            {
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }

    /// <summary>
    /// Emit a single bucket interface.
    /// </summary>
    private static void EmitBucketInterface(
        StringBuilder sb,
        BuildContext ctx,
        ExtensionBucketPlan bucket,
        IReadOnlyList<MethodSymbol> methodsToEmit,
        TypeNameResolver resolver)
    {
        var targetType = bucket.TargetType;

        // Interface declaration with generic parameters
        sb.Append($"export interface {bucket.BucketInterfaceName}");

        // Add generic parameters if target type is generic
        if (targetType.GenericParameters.Length > 0)
        {
            sb.Append('<');
            var genericParams = new List<string>();
            foreach (var param in targetType.GenericParameters)
            {
                // Check if any method in this bucket requires IEquatable constraint for this parameter
                var needsIEquatable = BucketNeedsIEquatableConstraint(methodsToEmit, param.Name);

                if (needsIEquatable)
                {
                    // Add IEquatable constraint: T extends IEquatable_1<T>
                    genericParams.Add($"{param.Name} extends System.IEquatable_1<{param.Name}>");
                }
                else
                {
                    // No constraint needed
                    genericParams.Add(param.Name);
                }
            }
            sb.Append(string.Join(", ", genericParams));
            sb.Append('>');
        }

        sb.AppendLine(" {");

        // Emit methods as proper TypeScript overloads (no numeric suffixes)
        // Group by base CLR name and emit multiple signatures with same name
        foreach (var method in methodsToEmit)
        {
            EmitExtensionMethod(sb, ctx, method, resolver, targetType.GenericParameters);
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Emit an extension method as an instance method in the bucket interface.
    /// Drops the first 'this' parameter and emits remaining parameters.
    /// Unifies method-level generics with target type's generics BY POSITION (not name).
    /// Example: Where&lt;TSource&gt;(this IEnumerable&lt;TSource&gt;, ...) becomes Where(...) using bucket's T.
    /// </summary>
    private static void EmitExtensionMethod(
        StringBuilder sb,
        BuildContext ctx,
        MethodSymbol method,
        TypeNameResolver resolver,
        IReadOnlyList<Model.Symbols.GenericParameterSymbol> targetGenericParameters)
    {
        // Skip the first parameter (the 'this' parameter) for extension methods
        var instanceParams = method.Parameters.Skip(1).ToArray();

        sb.Append("  ");

        // Method name: CLR-faithful (no casing transforms).
        var methodName = method.TsEmitName;
        sb.Append(methodName);

        // Build generic substitution map and unified generics set BY POSITION from receiver type
        // Example: IEnumerable<TSource> receiver → target IEnumerable<T> means TSource→T
        // unifiedGenerics includes ALL method generics that map to bucket (even if same name)
        var (genericSubstitution, unifiedGenerics) = BuildGenericSubstitution(method, targetGenericParameters);

        // Determine which method generics remain after unification
        // Method generics that map to bucket generics are removed (shouldn't shadow bucket's T)
        var methodGenericsToEmit = method.GenericParameters
            .Where(p => !unifiedGenerics.Contains(p.Name))
            .ToList();

        // Build allowed type parameter names (bucket generics + remaining method generics)
        var allowedTypeParams = new HashSet<string>(targetGenericParameters.Select(p => p.Name));
        foreach (var param in methodGenericsToEmit)
        {
            allowedTypeParams.Add(param.Name);
        }

        // Only emit method-level generics if there are non-unified ones
        if (methodGenericsToEmit.Count > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", methodGenericsToEmit.Select(p => p.Name)));
            sb.Append('>');
        }

        // Parameters - apply generic substitution
        sb.Append('(');
        var paramStrings = new List<string>();
        foreach (var param in instanceParams)
        {
            var paramType = PrintTypeWithSubstitution(param.Type, resolver, ctx, allowedTypeParams, genericSubstitution);
            var paramName = TypeScriptReservedWords.SanitizeParameterName(param.Name);

            // Preserve optional/default parameters and params arrays.
            // EF Core async extensions commonly use optional CancellationToken parameters which should be
            // callable without arguments (matches C# default-parameter semantics).
            if (param.IsParams)
            {
                paramStrings.Add($"...{paramName}: {paramType}");
            }
            else if (param.HasDefaultValue)
            {
                paramStrings.Add($"{paramName}?: {paramType}");
            }
            else
            {
                paramStrings.Add($"{paramName}: {paramType}");
            }
        }
        sb.Append(string.Join(", ", paramStrings));
        sb.Append(')');

        // Return type - apply generic substitution
        var returnType = PrintTypeWithSubstitution(method.ReturnType, resolver, ctx, allowedTypeParams, genericSubstitution);
        sb.Append($": Rewrap<this, {returnType}>");

        sb.AppendLine(";");
    }

    /// <summary>
    /// Build generic unification info from method generics to bucket generics BY POSITION.
    /// Analyzes the receiver type (first param) and matches its type arguments to target type params.
    /// Returns:
    ///   - substitution: Name mappings where method and bucket names differ (e.g., "TSource" → "T")
    ///   - unifiedGenerics: ALL method generic names that map to bucket generics (including same names)
    ///
    /// Example: Where&lt;TSource&gt;(this IEnumerable&lt;TSource&gt;) with bucket IEnumerable&lt;T&gt;
    ///          returns substitution: { "TSource" → "T" }, unifiedGenerics: { "TSource" }
    ///
    /// Example: Contains&lt;T&gt;(this IEnumerable&lt;T&gt;) with bucket IEnumerable&lt;T&gt;
    ///          returns substitution: {}, unifiedGenerics: { "T" }  (no rename needed, but T is unified)
    /// </summary>
    private static (Dictionary<string, string> substitution, HashSet<string> unifiedGenerics) BuildGenericSubstitution(
        MethodSymbol method,
        IReadOnlyList<Model.Symbols.GenericParameterSymbol> targetGenericParameters)
    {
        var substitution = new Dictionary<string, string>();
        var unifiedGenerics = new HashSet<string>();

        if (method.Parameters.Length == 0 || targetGenericParameters.Count == 0)
            return (substitution, unifiedGenerics);

        // Get receiver type (first 'this' parameter)
        var receiverType = method.Parameters[0].Type;

        // Extract type arguments from receiver if it's a generic named type
        if (receiverType is Model.Types.NamedTypeReference namedReceiver && namedReceiver.TypeArguments.Count > 0)
        {
            // Match type arguments by position to target generic parameters
            var minCount = Math.Min(namedReceiver.TypeArguments.Count, targetGenericParameters.Count);
            for (int i = 0; i < minCount; i++)
            {
                var receiverArg = namedReceiver.TypeArguments[i];

                // If the receiver's type argument is a generic parameter reference,
                // this method generic is unified with the bucket's corresponding parameter
                if (receiverArg is Model.Types.GenericParameterReference gpRef)
                {
                    var targetParamName = targetGenericParameters[i].Name;

                    // Always mark this method generic as unified (shouldn't be emitted on method)
                    unifiedGenerics.Add(gpRef.Name);

                    // Only add to substitution if names differ (actual rename needed)
                    // Example: TSource (method) → T (bucket)
                    if (gpRef.Name != targetParamName)
                    {
                        substitution[gpRef.Name] = targetParamName;
                    }
                }
            }
        }

        return (substitution, unifiedGenerics);
    }

    /// <summary>
    /// Print a type reference with generic substitutions applied.
    /// Replaces generic parameter names according to the substitution map.
    /// </summary>
    private static string PrintTypeWithSubstitution(
        Model.Types.TypeReference typeRef,
        TypeNameResolver resolver,
        BuildContext ctx,
        HashSet<string> allowedTypeParams,
        Dictionary<string, string> genericSubstitution)
    {
        // First, apply substitution to the type reference
        var substitutedRef = ApplySubstitution(typeRef, genericSubstitution);

        // Then print using TypeRefPrinter
        return TypeRefPrinter.Print(substitutedRef, resolver, ctx, allowedTypeParams);
    }

    /// <summary>
    /// Apply generic substitutions to a type reference, returning a new type reference.
    /// Uses `with` expressions to properly copy all required properties from originals.
    /// </summary>
    private static Model.Types.TypeReference ApplySubstitution(
        Model.Types.TypeReference typeRef,
        Dictionary<string, string> genericSubstitution)
    {
        if (genericSubstitution.Count == 0)
            return typeRef;

        return typeRef switch
        {
            // Rename generic parameter references if in substitution map
            Model.Types.GenericParameterReference gpRef when genericSubstitution.TryGetValue(gpRef.Name, out var newName) =>
                gpRef with { Name = newName },

            // Recursively apply substitution to type arguments in named type references
            Model.Types.NamedTypeReference named when named.TypeArguments.Count > 0 =>
                named with
                {
                    TypeArguments = named.TypeArguments.Select(arg => ApplySubstitution(arg, genericSubstitution)).ToImmutableList()
                },

            // Recursively apply substitution to element type in arrays
            Model.Types.ArrayTypeReference arr =>
                arr with { ElementType = ApplySubstitution(arr.ElementType, genericSubstitution) },

            // Recursively apply substitution to referenced type in byrefs
            Model.Types.ByRefTypeReference byRef =>
                byRef with { ReferencedType = ApplySubstitution(byRef.ReferencedType, genericSubstitution) },

            // Recursively apply substitution to pointee type in pointers
            Model.Types.PointerTypeReference ptr =>
                ptr with { PointeeType = ApplySubstitution(ptr.PointeeType, genericSubstitution) },

            _ => typeRef // No substitution needed
        };
    }

    private static (
        Dictionary<ExtensionBucketPlan, ExtensionBucketPlan?> PreferredBase,
        Dictionary<ExtensionBucketPlan, IReadOnlyList<MethodSymbol>> EffectiveMethods
    ) ComputeBucketOverrides(
        ExtensionMethodsPlan plan,
        SymbolGraph graph)
    {
        var preferredBase = new Dictionary<ExtensionBucketPlan, ExtensionBucketPlan?>();
        var effectiveMethods = new Dictionary<ExtensionBucketPlan, IReadOnlyList<MethodSymbol>>();

        if (plan.Buckets.Length == 0)
        {
            return (preferredBase, effectiveMethods);
        }

        // Build a fast lookup for inheritance traversal (ClrFullName -> first TypeSymbol)
        var typeByClrFullName = new Dictionary<string, Model.Symbols.TypeSymbol>();
        foreach (var t in graph.TypeIndex.Values)
        {
            if (!typeByClrFullName.ContainsKey(t.ClrFullName))
                typeByClrFullName[t.ClrFullName] = t;
        }

        bool IsStrictSubtypeOf(Model.Symbols.TypeSymbol derived, Model.Symbols.TypeSymbol @base)
        {
            if (derived.ClrFullName == @base.ClrFullName)
                return false;

            var visited = new HashSet<string>();
            return IsSubtypeOfFullName(derived, @base.ClrFullName, visited);
        }

        bool IsSubtypeOfFullName(Model.Symbols.TypeSymbol type, string baseClrFullName, HashSet<string> visited)
        {
            if (!visited.Add(type.ClrFullName))
                return false;

            if (type.BaseType is Model.Types.NamedTypeReference namedBase)
            {
                if (namedBase.FullName == baseClrFullName)
                    return true;

                if (typeByClrFullName.TryGetValue(namedBase.FullName, out var baseSym) &&
                    IsSubtypeOfFullName(baseSym, baseClrFullName, visited))
                    return true;
            }

            foreach (var ifaceRef in type.Interfaces)
            {
                if (ifaceRef is not Model.Types.NamedTypeReference namedIface)
                    continue;

                if (namedIface.FullName == baseClrFullName)
                    return true;

                if (typeByClrFullName.TryGetValue(namedIface.FullName, out var ifaceSym) &&
                    IsSubtypeOfFullName(ifaceSym, baseClrFullName, visited))
                    return true;
            }

            return false;
        }

        // Compute overrides per declaring namespace (C# using semantics).
        foreach (var group in plan.Buckets
                     .GroupBy(b => b.DeclaringNamespace)
                     .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var buckets = group.ToList();

            // Sort buckets by inheritance specificity so more specific receiver types override
            // overlapping member names from less specific buckets.
            buckets.Sort((a, b) =>
            {
                var aSubB = IsStrictSubtypeOf(a.TargetType, b.TargetType);
                var bSubA = IsStrictSubtypeOf(b.TargetType, a.TargetType);
                if (aSubB && !bSubA) return 1;   // a is more specific -> after b
                if (bSubA && !aSubB) return -1;  // b is more specific -> after a
                // Stable deterministic fallback
                var c = string.Compare(a.TargetType.Namespace, b.TargetType.Namespace, StringComparison.Ordinal);
                if (c != 0) return c;
                c = string.Compare(a.TargetType.TsEmitName, b.TargetType.TsEmitName, StringComparison.Ordinal);
                if (c != 0) return c;
                return a.Key.Arity.CompareTo(b.Key.Arity);
            });

            var bucketMemberNames = buckets.ToDictionary(
                b => b,
                b => b.Methods.Select(m => m.TsEmitName).ToHashSet(StringComparer.Ordinal));

            bool BucketsOverlap(ExtensionBucketPlan a, ExtensionBucketPlan b)
            {
                var aNames = bucketMemberNames[a];
                var bNames = bucketMemberNames[b];
                if (aNames.Count > bNames.Count) (aNames, bNames) = (bNames, aNames);
                foreach (var n in aNames)
                {
                    if (bNames.Contains(n)) return true;
                }
                return false;
            }

            ExtensionBucketPlan? FindNearestOverlappingBase(ExtensionBucketPlan derived)
            {
                var candidates = buckets
                    .Where(b =>
                        b != derived &&
                        (b.Key.Arity == derived.Key.Arity || b.Key.Arity == 0) &&
                        IsStrictSubtypeOf(derived.TargetType, b.TargetType) &&
                        BucketsOverlap(derived, b))
                    .ToList();

                if (candidates.Count == 0)
                    return null;

                ExtensionBucketPlan? best = null;
                foreach (var c in candidates)
                {
                    var isMoreSpecificThanAllOthers = candidates.All(o => o == c || !IsStrictSubtypeOf(o.TargetType, c.TargetType));
                    if (!isMoreSpecificThanAllOthers) continue;

                    if (best == null)
                    {
                        best = c;
                        continue;
                    }

                    var cmp = string.Compare(c.TargetType.Namespace, best.TargetType.Namespace, StringComparison.Ordinal);
                    if (cmp != 0)
                    {
                        if (cmp < 0) best = c;
                        continue;
                    }
                    cmp = string.Compare(c.TargetType.TsEmitName, best.TargetType.TsEmitName, StringComparison.Ordinal);
                    if (cmp != 0)
                    {
                        if (cmp < 0) best = c;
                        continue;
                    }
                    if (c.Key.Arity < best.Key.Arity)
                        best = c;
                }

                return best;
            }

            foreach (var b in buckets)
            {
                preferredBase[b] = FindNearestOverlappingBase(b);
            }

            var memo = new Dictionary<ExtensionBucketPlan, IReadOnlyList<MethodSymbol>>();

            IReadOnlyList<MethodSymbol> GetEffectiveMethods(ExtensionBucketPlan bucket)
            {
                if (memo.TryGetValue(bucket, out var cached))
                    return cached;

                var baseBucket = preferredBase[bucket];
                if (baseBucket == null)
                {
                    memo[bucket] = bucket.Methods;
                    return bucket.Methods;
                }

                // Omit-style preference (by name) without mapped types:
                // include base methods unless the derived bucket declares a method with the same name.
                var derivedNames = bucketMemberNames[bucket];
                var baseEffective = GetEffectiveMethods(baseBucket);

                var list = baseEffective
                    .Where(m => !derivedNames.Contains(m.TsEmitName))
                    .ToList();

                list.AddRange(bucket.Methods);

                memo[bucket] = list;
                return list;
            }

            foreach (var b in buckets)
            {
                effectiveMethods[b] = GetEffectiveMethods(b);
            }
        }

        return (preferredBase, effectiveMethods);
    }

    private static void EmitExtensionMethodsHelpers(
        StringBuilder sb,
        ExtensionMethodsPlan plan,
        Func<Model.Symbols.TypeSymbol, string> getTargetNamespaceAlias,
        Dictionary<ExtensionBucketPlan, ExtensionBucketPlan?> preferredBase,
        Dictionary<ExtensionBucketPlan, IReadOnlyList<MethodSymbol>> effectiveMethods)
    {
        if (plan.Buckets.Length == 0)
        {
            return;
        }

        // Internal helper types for "sticky" extension scopes across fluent chains.
        // Each ExtensionMethods_<Namespace><TShape> helper attaches an applier into __tsonic_ext so
        // extension methods can preserve all active namespaces via Rewrap<this, ReturnShape>.
        sb.AppendLine("// Internal helper types for sticky extension scopes");
        sb.AppendLine("type __TsonicExtMapOf<T> = T extends { __tsonic_ext?: infer M } ? M : {};");
        // NOTE: We intentionally avoid mapped types (Omit/Exclude/...) here.
        // Large, deeply nested extension surfaces (e.g. System.Linq + EF Core) can trigger
        // TS2321 "Excessive stack depth comparing types" when mapped types are involved in
        // the sticky-scope carrier / preference composition.
        //
        // We rely on the fact that extension scope keys (namespace strings) are stable and
        // applier types for a given key are identical, so `A & B` is sufficient.
        sb.AppendLine("type __TsonicMergeExtMaps<A, B> = A & B;");
        sb.AppendLine("type __TsonicWithExt<TShape, K extends string, TApplier> = { __tsonic_ext?: __TsonicMergeExtMaps<__TsonicExtMapOf<TShape>, { [P in K]: TApplier }> };");
        sb.AppendLine();

        // One helper per declaring namespace (C# using semantics)
        foreach (var group in plan.Buckets
                     .GroupBy(b => b.DeclaringNamespace)
                     .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var declaringNamespace = group.Key;
            var extensionMethodsTypeName = GetExtensionMethodsTypeName(declaringNamespace);
            var nsAlias = GetNamespaceAlias(declaringNamespace);
            var extSurfaceTypeName = $"__TsonicExtSurface_{nsAlias}";
            var extApplierTypeName = $"__TsonicExtApplier_{nsAlias}";
            var extKey = string.IsNullOrEmpty(declaringNamespace) ? "_root" : declaringNamespace;

            sb.AppendLine($"// Generic helper type for extension methods in namespace: {declaringNamespace}");

            var buckets = group
                .OrderBy(b => b.TargetType.Namespace, StringComparer.Ordinal)
                .ThenBy(b => b.TargetType.TsEmitName, StringComparer.Ordinal)
                .ThenBy(b => b.Key.Arity)
                .ToList();

            sb.AppendLine($"type {extSurfaceTypeName}<TShape> =");
            sb.AppendLine("  (");

            bool HasOverrideAncestor(ExtensionBucketPlan derived, ExtensionBucketPlan ancestor)
            {
                var cur = preferredBase[derived];
                while (cur != null)
                {
                    if (cur == ancestor) return true;
                    cur = preferredBase[cur];
                }
                return false;
            }

            string MarkerTestForBucket(ExtensionBucketPlan bucket, string targetNamespaceAlias)
            {
                if (bucket.TargetType.GenericParameters.Length == 0)
                    return $"{targetNamespaceAlias}.{bucket.TargetType.TsEmitName}";

                var inferClause = string.Join(", ", Enumerable.Range(0, bucket.TargetType.GenericParameters.Length).Select(i => $"infer _{i}"));
                return $"{targetNamespaceAlias}.{bucket.TargetType.TsEmitName}<{inferClause}>";
            }

            var conditionals = new List<string>();

            foreach (var bucket in buckets)
            {
                var targetType = bucket.TargetType;
                var targetNamespaceAlias = getTargetNamespaceAlias(targetType);

                if (targetType.GenericParameters.Length > 0)
                {
                    // Generic type: use infer to extract type arguments
                    // If bucket has IEquatable constraint, propagate it to infer clause
                    // Example: TShape extends System.Span_1<infer T extends IEquatable_1<T>> ? __Ext_Span_1<T>
                    var inferParams = new List<string>();
                    for (int i = 0; i < targetType.GenericParameters.Length; i++)
                    {
                        var param = targetType.GenericParameters[i];
                        var needsIEquatable = BucketNeedsIEquatableConstraint(effectiveMethods[bucket], param.Name);

                        if (needsIEquatable)
                        {
                            inferParams.Add($"infer T{i} extends System.IEquatable_1<T{i}>");
                        }
                        else
                        {
                            inferParams.Add($"infer T{i}");
                        }
                    }
                    var inferClause = string.Join(", ", inferParams);
                    var bucketArgs = string.Join(", ", Enumerable.Range(0, targetType.GenericParameters.Length).Select(i => $"T{i}"));

                    // If this bucket is an override-ancestor for any derived bucket, suppress it when the
                    // receiver matches a derived bucket (C# "more specific receiver wins").
                    var derivedMarkers = buckets
                        .Where(d => d != bucket && HasOverrideAncestor(d, bucket))
                        .Select(d => MarkerTestForBucket(d, getTargetNamespaceAlias(d.TargetType)))
                        .Distinct()
                        .ToList();

                    var trueExpr = bucketArgs.Length == 0 ? bucket.BucketInterfaceName : $"{bucket.BucketInterfaceName}<{bucketArgs}>";

                    if (derivedMarkers.Count > 0)
                    {
                        // Wrap base bucket with nested derived guards:
                        //   TShape extends Base<infer ...> ? (TShape extends Derived ? {} : BaseBucket<...>) : {}
                        var guarded = trueExpr;
                        for (var i = derivedMarkers.Count - 1; i >= 0; i--)
                        {
                            guarded = $"(TShape extends {derivedMarkers[i]} ? {{}} : {guarded})";
                        }
                        trueExpr = guarded;
                    }

                    conditionals.Add(
                        $"(TShape extends {targetNamespaceAlias}.{targetType.TsEmitName}<{inferClause}> ? {trueExpr} : {{}})");
                }
                else
                {
                    var shapeTypeExpression = GetShapeTypeExpressionForConditional(bucket, targetNamespaceAlias);

                    var derivedMarkers = buckets
                        .Where(d => d != bucket && HasOverrideAncestor(d, bucket))
                        .Select(d => MarkerTestForBucket(d, getTargetNamespaceAlias(d.TargetType)))
                        .Distinct()
                        .ToList();

                    var trueExpr = bucket.BucketInterfaceName;
                    if (derivedMarkers.Count > 0)
                    {
                        var guarded = trueExpr;
                        for (var i = derivedMarkers.Count - 1; i >= 0; i--)
                        {
                            guarded = $"(TShape extends {derivedMarkers[i]} ? {{}} : {guarded})";
                        }
                        trueExpr = guarded;
                    }

                    conditionals.Add(
                        $"(TShape extends {shapeTypeExpression} ? {trueExpr} : {{}})");
                }
            }

            // Special case: native T[] arrays get IEnumerable_1 extensions when present in this namespace.
            // This allows ExtensionMethods_System_Linq<string[]> to include LINQ extensions.
            var ienumerableBucket = buckets.FirstOrDefault(b =>
                b.TargetType.Namespace == "System.Collections.Generic" &&
                b.TargetType.TsEmitName == "IEnumerable_1");

            if (ienumerableBucket != null)
            {
                conditionals.Add($"(TShape extends (infer T)[] ? {ienumerableBucket.BucketInterfaceName}<T> : {{}})");
            }

            // Combine matches using intersection (&).
	            if (conditionals.Count == 0)
	                sb.AppendLine("    {}");
	            else
	                sb.AppendLine($"    {string.Join(" & ", conditionals)}");

            sb.AppendLine("  );");
            sb.AppendLine();

            // Applier interface stored in __tsonic_ext (used by Rewrap<this, ReturnShape>).
            //
            // IMPORTANT: This MUST be an HKT-style "applier" (not a generic function type).
            // Generic function appliers cannot be reliably re-applied to a new shape in TS,
            // because inference may instantiate the generic with a structural supertype.
            //
            // The HKT encoding forces exact substitution via intersection:
            //   __TsonicApplyApplier<A, Shape> = (A & { __tsonic_shape: Shape })["__tsonic_type"]
            sb.AppendLine($"interface {extApplierTypeName} {{");
            sb.AppendLine("  __tsonic_shape: unknown;");
            sb.AppendLine($"  __tsonic_type: {extSurfaceTypeName}<this[\"__tsonic_shape\"]>;");
            sb.AppendLine("}");
            sb.AppendLine();

            // Public wrapper type: attach this namespace's applier and apply its surface.
            sb.AppendLine($"export type {extensionMethodsTypeName}<TShape> =");
            sb.AppendLine("  TShape extends null | undefined ? TShape");
            sb.AppendLine("  : TShape extends void ? void");
            sb.AppendLine($"  : TShape & __TsonicWithExt<TShape, \"{extKey}\", {extApplierTypeName}> & {extSurfaceTypeName}<TShape>;");
            sb.AppendLine();
        }
    }
}
