using System.Text;
using tsbindgen.Analysis;
using tsbindgen.Core;
using tsbindgen.Emit.Printers;
using tsbindgen.Model;
using tsbindgen.Model.Symbols;
using tsbindgen.Model.Symbols.MemberSymbols;
using tsbindgen.Model.Types;
using tsbindgen.Renaming;

namespace tsbindgen.Emit;

/// <summary>
/// Emits extension method method-tables to __internal/extensions/index.d.ts.
/// Tables are scoped by declaring namespace (C# using semantics).
/// Example: __TsonicExtMethods_System_Linq contains Where, Select, etc. with explicit `this:` receiver constraints.
/// </summary>
public static class ExtensionsEmitter
{
    /// <summary>
    /// Emit the __internal/extensions/index.d.ts file containing method-table interfaces.
    /// </summary>
    /// <param name="ctx">Build context</param>
    /// <param name="plan">Extension methods plan with all buckets</param>
    /// <param name="graph">Symbol graph for type resolution</param>
    /// <param name="outputDirectory">Root output directory</param>
    public static void Emit(BuildContext ctx, ExtensionMethodsPlan plan, SymbolGraph graph, string outputDirectory)
    {
        if (plan.Buckets.Length == 0)
        {
            ctx.Log("ExtensionsEmitter", "No extension methods found - skipping extensions file");
            return;
        }

        ctx.Log("ExtensionsEmitter", $"Emitting extension method tables: {plan.Buckets.Length} buckets");

        // Create __internal/extensions directory
        var extensionsDir = Path.Combine(outputDirectory, "__internal", "extensions");
        Directory.CreateDirectory(extensionsDir);

        // Generate file content
        var content = GenerateExtensionsFile(ctx, plan, graph);

        // Write file
        var filePath = Path.Combine(extensionsDir, "index.d.ts");
        File.WriteAllText(filePath, content);

        ctx.Log("ExtensionsEmitter", $"Wrote {filePath}");
    }

    /// <summary>
    /// Generate the complete extensions file content.
    /// </summary>
    private static string GenerateExtensionsFile(BuildContext ctx, ExtensionMethodsPlan plan, SymbolGraph graph)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Extension Method Tables");
        sb.AppendLine("// This file contains method-table interfaces for C# extension methods.");
        sb.AppendLine("// Tables are scoped by declaring namespace (C# using semantics).");
        sb.AppendLine("// For each namespace with extension methods, this file exports an ExtensionMethods_<Namespace> helper.");
        sb.AppendLine();

        // Collect all namespaces used in extension method signatures
        var namespacesUsed = new HashSet<string>();
        // Track the actual referenced CLR full names per namespace so we can choose an
        // import source package in --lib mode even when a namespace is split across packages.
        var namespaceToClrFullNames = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var bucket in plan.Buckets)
        {
            // Add the target type's namespace (needed for ExtensionMethods_<Namespace> helper)
            namespacesUsed.Add(bucket.TargetType.Namespace);

            // Also record the receiver type's CLR full name so --lib import planning can resolve
            // namespaces even when only the receiver (and not any parameter/return types) appears.
            if (!string.IsNullOrEmpty(bucket.TargetType.Namespace))
            {
                if (!namespaceToClrFullNames.TryGetValue(bucket.TargetType.Namespace, out var set))
                {
                    set = new HashSet<string>(StringComparer.Ordinal);
                    namespaceToClrFullNames[bucket.TargetType.Namespace] = set;
                }

                set.Add(bucket.TargetType.ClrFullName);
            }

            foreach (var method in bucket.Methods)
            {
                // Collect from return type
                CollectNamespaces(method.ReturnType, namespacesUsed, namespaceToClrFullNames, graph);

                // Collect from parameters (include receiver `this` type).
                foreach (var param in method.Parameters)
                {
                    CollectNamespaces(param.Type, namespacesUsed, namespaceToClrFullNames, graph);
                }

                // Collect from generic constraints
                foreach (var genParam in method.GenericParameters)
                {
                    foreach (var constraint in genParam.Constraints)
                    {
                        CollectNamespaces(constraint, namespacesUsed, namespaceToClrFullNames, graph);
                    }
                }
            }
        }

        // Generate namespace imports
        // Extension methods file is at __internal/extensions/index.d.ts
        // Local namespaces are at ../../{Namespace}/internal/index.js
        // External namespaces (from --lib contracts) are imported via package specifiers
        // (e.g., @tsonic/dotnet/System.Linq/internal/index.js).
        var localNamespaces = graph.Namespaces.Select(n => n.Name).ToHashSet();
        var namespaceAliasByPackage = new Dictionary<(string Namespace, string Package), string>();
        Func<string, string, string, string>? facadeNamespaceAliasResolver = null;
        if (namespacesUsed.Count > 0)
        {
            static string SanitizePackageAlias(string pkg)
            {
                // Convert an npm package specifier (e.g., "@tsonic/dotnet", "microsoft-foo-types")
                // into a TS identifier-safe suffix.
                var sb = new StringBuilder(pkg.Length);
                foreach (var ch in pkg)
                {
                    if (char.IsLetterOrDigit(ch))
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append('_');
                    }
                }

                var s = sb.ToString().Trim('_');
                if (s.Length == 0)
                    return "pkg";

                // Identifiers can't start with a digit.
                if (char.IsDigit(s[0]))
                    return "_" + s;

                return s;
            }

            string GetNamespaceModuleImportPath(string ns, string? pkg)
            {
                if (string.IsNullOrEmpty(ns))
                {
                    // Root namespace is always local within the output package.
                    return "../../_root/index.js";
                }

                var outputName = NamespacePathMapper.GetOutputName(ns, ctx);

                // Local namespace: relative import within this output package.
                if (localNamespaces.Contains(ns) || ctx.LibraryContract == null || pkg == null)
                {
                    return $"../../{outputName}/internal/index.js";
                }

                return $"{pkg}/{outputName}/internal/index.js";
            }

            // Build deterministic per-(namespace, package) imports in --lib mode.
            // Airplane-grade: if a namespace is split across multiple packages, we import all
            // contributing namespace modules and qualify type references based on the owning package
            // of each referenced CLR full name (LibraryContract.GetPackageForClrFullName).
            var namespaceImports = new List<(string Namespace, string Alias, string ImportPath)>();

            foreach (var ns in namespacesUsed.OrderBy(n => n, StringComparer.Ordinal))
            {
                var baseAlias = GetNamespaceAlias(ns);

                // Local namespaces (or non-lib mode): single import as before.
                if (string.IsNullOrEmpty(ns) || localNamespaces.Contains(ns) || ctx.LibraryContract == null)
                {
                    var importPath = GetNamespaceModuleImportPath(ns, pkg: null);
                    namespaceImports.Add((ns, baseAlias, importPath));
                    continue;
                }

                // External namespace in --lib mode: import one module per contributing package.
                var referenced = namespaceToClrFullNames.TryGetValue(ns, out var clrs) ? clrs : null;
                if (referenced == null || referenced.Count == 0)
                {
                    // We should always have at least the receiver type recorded. Keep strict behavior
                    // rather than guessing.
                    throw new InvalidOperationException(
                        $"No referenced CLR types recorded for namespace '{ns}' in extension bucket emission. " +
                        "This indicates a tsbindgen bug in namespace collection.");
                }

                var pkgs = referenced
                    .Select(ctx.LibraryContract.GetPackageForClrFullName)
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(p => p, StringComparer.Ordinal)
                    .ToList();

                if (pkgs.Count == 0)
                {
                    throw new InvalidOperationException(
                        $"No owning packages resolved for namespace '{ns}' in extension bucket emission.");
                }

                // Choose a canonical package for the base alias so existing code that hardcodes
                // certain namespace aliases (e.g., System.* constraints) remains valid.
                var canonicalPkg = pkgs[0];
                if (ns == "System")
                {
                    try
                    {
                        canonicalPkg = ctx.LibraryContract.GetPackageForClrFullName("System.Int32");
                    }
                    catch
                    {
                        // Fall back to deterministic sorted-first
                    }
                }

                foreach (var pkg in pkgs)
                {
                    var alias = pkg == canonicalPkg ? baseAlias : $"{baseAlias}__{SanitizePackageAlias(pkg)}";
                    namespaceAliasByPackage[(ns, pkg)] = alias;
                    namespaceImports.Add((ns, alias, GetNamespaceModuleImportPath(ns, pkg)));
                }
            }

            facadeNamespaceAliasResolver = (clrFullName, ns, defaultAlias) =>
            {
                if (ctx.LibraryContract == null)
                    return defaultAlias;

                if (string.IsNullOrEmpty(ns) || localNamespaces.Contains(ns))
                    return defaultAlias;

                var pkg = ctx.LibraryContract.GetPackageForClrFullName(clrFullName);
                return namespaceAliasByPackage.TryGetValue((ns, pkg), out var alias) ? alias : defaultAlias;
            };

            sb.AppendLine("// Import namespace modules for cross-namespace type references");
            foreach (var import in namespaceImports
                         .OrderBy(i => i.Namespace, StringComparer.Ordinal)
                         .ThenBy(i => i.Alias, StringComparer.Ordinal))
            {
                sb.AppendLine($"import * as {import.Alias} from \"{import.ImportPath}\";");
            }
            sb.AppendLine();
        }

        // Import primitive type aliases from @tsonic/core
        sb.AppendLine("// Import primitive type aliases");
        sb.AppendLine("import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';");
        sb.AppendLine();

        // Import Rewrap helper from @tsonic/core (sticky extension scopes across fluent chains)
        sb.AppendLine("// Import sticky extension scope helper");
        sb.AppendLine("import type { Rewrap } from '@tsonic/core/lang.js';");
        sb.AppendLine();

        // Import CLR primitive type aliases from System namespace
        // TypeRefPrinter's generic primitive lifting emits System_Internal.Int32/Char/etc.
        // This import must work in both normal mode (System emitted locally) and library mode (--lib @tsonic/dotnet).
        sb.AppendLine("// Import CLR type aliases for generic type arguments");
        {
            var systemNs = "System";
            var outputName = NamespacePathMapper.GetOutputName(systemNs, ctx);

            string systemImportPath;
            if (localNamespaces.Contains(systemNs) || ctx.LibraryContract == null)
            {
                systemImportPath = $"../../{outputName}/internal/index.js";
            }
            else
            {
                var pkg = ctx.LibraryContract.GetPackageForClrFullName("System.Int32");
                systemImportPath = $"{pkg}/{outputName}/internal/index.js";
            }

            sb.AppendLine($"import * as System_Internal from \"{systemImportPath}\";");
        }
        sb.AppendLine();

        // Import ptr from @tsonic/core (needed for pointer types)
        // Note: ref/out/in modifiers are ABI semantics tracked in metadata, not TS types
        sb.AppendLine("// Import unsafe type markers");
        sb.AppendLine("import type { ptr } from '@tsonic/core/types.js';");
        sb.AppendLine();

        // Create TypeNameResolver for this file
        // Extension methods file needs all cross-namespace types to be fully qualified
        // Use a dummy namespace "__internal.extensions" and enable facade mode
        // This triggers cross-namespace qualification for all type references
        var resolver = new TypeNameResolver(
            ctx,
            graph,
            importPlan: null,
            currentNamespace: "__internal.extensions",
            facadeMode: true,
            libraryImportStyle: Plan.LibraryImportStyle.InternalIndex,
            facadeNamespaceAliasResolver: facadeNamespaceAliasResolver);

        EmitStickyScopeHelpers(sb);

        // Precompute a CLR type index for receiver specificity ordering.
        var typeByClrFullName = BuildTypeIndex(graph);

        // Emit per-namespace method tables + public wrapper helpers.
        foreach (var group in plan.Buckets
                     .GroupBy(b => b.DeclaringNamespace)
                     .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var declaringNamespace = group.Key;
            var buckets = group.ToList();

            EmitMethodTableInterface(sb, ctx, declaringNamespace, buckets, resolver, typeByClrFullName);
            sb.AppendLine();

            EmitExtensionMethodsHelper(sb, declaringNamespace, buckets);
        }

        return sb.ToString();
    }

    private static string GetNamespaceAlias(string ns) =>
        string.IsNullOrEmpty(ns) ? "_root" : ns.Replace('.', '_');

    private static string GetExtensionMethodsTypeName(string declaringNamespace) =>
        $"ExtensionMethods_{GetNamespaceAlias(declaringNamespace)}";

    private static string GetMethodsTableTypeName(string declaringNamespace) =>
        $"__TsonicExtMethods_{GetNamespaceAlias(declaringNamespace)}";

    private static string GetExtApplierTypeName(string declaringNamespace) =>
        $"__TsonicExtApplier_{GetNamespaceAlias(declaringNamespace)}";

    /// <summary>
    /// Recursively collect all namespaces used in a type reference.
    /// </summary>
    private static void CollectNamespaces(
        TypeReference typeRef,
        HashSet<string> namespaces,
        Dictionary<string, HashSet<string>> namespaceToClrFullNames,
        SymbolGraph graph)
    {
        switch (typeRef)
        {
            case NamedTypeReference named:
                // Always add the declared namespace, even if the type is external (filtered out in --lib mode).
                // Relying on graph lookup causes us to miss external namespaces, producing missing imports.
                namespaces.Add(named.Namespace);
                if (!string.IsNullOrEmpty(named.Namespace))
                {
                    if (!namespaceToClrFullNames.TryGetValue(named.Namespace, out var set))
                    {
                        set = new HashSet<string>(StringComparer.Ordinal);
                        namespaceToClrFullNames[named.Namespace] = set;
                    }
                    // Use the CLR full name key used by LibraryContract.ClrFullNameToPackage.
                    set.Add(named.FullName);
                }

                // Collect from type arguments
                foreach (var arg in named.TypeArguments)
                {
                    CollectNamespaces(arg, namespaces, namespaceToClrFullNames, graph);
                }
                break;

            case ArrayTypeReference array:
                CollectNamespaces(array.ElementType, namespaces, namespaceToClrFullNames, graph);
                break;

            case ByRefTypeReference byRef:
                CollectNamespaces(byRef.ReferencedType, namespaces, namespaceToClrFullNames, graph);
                break;

            case PointerTypeReference pointer:
                CollectNamespaces(pointer.PointeeType, namespaces, namespaceToClrFullNames, graph);
                break;

            case NestedTypeReference nested:
                CollectNamespaces(nested.FullReference, namespaces, namespaceToClrFullNames, graph);
                break;
        }
    }

    private static void EmitStickyScopeHelpers(StringBuilder sb)
    {
        sb.AppendLine("// Internal helper types for sticky extension scopes");
        sb.AppendLine("type __TsonicExtMapOf<T> = T extends { __tsonic_ext?: infer M } ? M : {};");
        sb.AppendLine("type __TsonicMergeExtMaps<A, B> = A & B;");
        sb.AppendLine("type __TsonicWithExt<TShape, K extends string, TApplier> = { __tsonic_ext?: __TsonicMergeExtMaps<__TsonicExtMapOf<TShape>, { [P in K]: TApplier }> };");
        sb.AppendLine();
    }

    private static Dictionary<string, TypeSymbol> BuildTypeIndex(SymbolGraph graph)
    {
        // Prefer the first occurrence for determinism (graph is deterministic).
        var map = new Dictionary<string, TypeSymbol>(StringComparer.Ordinal);
        foreach (var t in graph.TypeIndex.Values)
        {
            if (!map.ContainsKey(t.ClrFullName))
            {
                map[t.ClrFullName] = t;
            }
        }
        return map;
    }

    private static bool IsStrictSubtypeOf(
        TypeSymbol derived,
        TypeSymbol @base,
        IReadOnlyDictionary<string, TypeSymbol> typeByClrFullName)
    {
        if (derived.ClrFullName == @base.ClrFullName)
            return false;

        var visited = new HashSet<string>(StringComparer.Ordinal);
        return IsSubtypeOfFullName(derived, @base.ClrFullName, typeByClrFullName, visited);
    }

    private static bool IsSubtypeOfFullName(
        TypeSymbol type,
        string baseClrFullName,
        IReadOnlyDictionary<string, TypeSymbol> typeByClrFullName,
        HashSet<string> visited)
    {
        if (!visited.Add(type.ClrFullName))
            return false;

        if (type.BaseType is NamedTypeReference namedBase)
        {
            if (namedBase.FullName == baseClrFullName)
                return true;

            if (typeByClrFullName.TryGetValue(namedBase.FullName, out var baseSym) &&
                IsSubtypeOfFullName(baseSym, baseClrFullName, typeByClrFullName, visited))
                return true;
        }

        foreach (var ifaceRef in type.Interfaces)
        {
            if (ifaceRef is not NamedTypeReference namedIface)
                continue;

            if (namedIface.FullName == baseClrFullName)
                return true;

            if (typeByClrFullName.TryGetValue(namedIface.FullName, out var ifaceSym) &&
                IsSubtypeOfFullName(ifaceSym, baseClrFullName, typeByClrFullName, visited))
                return true;
        }

        return false;
    }

    private static void EmitMethodTableInterface(
        StringBuilder sb,
        BuildContext ctx,
        string declaringNamespace,
        IReadOnlyList<ExtensionBucketPlan> buckets,
        TypeNameResolver resolver,
        IReadOnlyDictionary<string, TypeSymbol> typeByClrFullName)
    {
        var methodsTableName = GetMethodsTableTypeName(declaringNamespace);

        sb.AppendLine($"// Extension method table for namespace: {declaringNamespace}");
        sb.AppendLine($"interface {methodsTableName} {{");

        // Order receiver buckets by CLR specificity (more specific receivers first).
        var orderedBuckets = buckets
            .OrderBy(b => b.TargetType.Namespace, StringComparer.Ordinal)
            .ThenBy(b => b.TargetType.TsEmitName, StringComparer.Ordinal)
            .ThenBy(b => b.Key.Arity)
            .ToList();

        orderedBuckets.Sort((a, b) =>
        {
            var aSubB = IsStrictSubtypeOf(a.TargetType, b.TargetType, typeByClrFullName);
            var bSubA = IsStrictSubtypeOf(b.TargetType, a.TargetType, typeByClrFullName);
            if (aSubB && !bSubA) return -1;   // a is more specific -> earlier
            if (bSubA && !aSubB) return 1;    // b is more specific -> earlier

            // Stable deterministic fallback
            var c = string.Compare(a.TargetType.Namespace, b.TargetType.Namespace, StringComparison.Ordinal);
            if (c != 0) return c;
            c = string.Compare(a.TargetType.TsEmitName, b.TargetType.TsEmitName, StringComparison.Ordinal);
            if (c != 0) return c;
            return a.Key.Arity.CompareTo(b.Key.Arity);
        });

        var bucketRank = orderedBuckets
            .Select((b, i) => (b, i))
            .ToDictionary(x => x.b, x => x.i);

        // Group by method name so overload order is deterministic and receiver-specific.
        var entries = orderedBuckets
            .SelectMany(b =>
                b.Methods.Select((m, idx) => (Bucket: b, Method: m, IndexInBucket: idx)))
            .GroupBy(e => e.Method.TsEmitName, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in entries)
        {
            foreach (var e in group
                         .OrderBy(e => bucketRank[e.Bucket])
                         .ThenBy(e => e.IndexInBucket))
            {
                EmitExtensionMethodSignature(sb, ctx, e.Method, resolver);
            }
        }

        sb.AppendLine("}");
    }

    private static void EmitExtensionMethodSignature(
        StringBuilder sb,
        BuildContext ctx,
        MethodSymbol method,
        TypeNameResolver resolver)
    {
        if (method.Parameters.Length == 0)
        {
            // Defensive: extension methods must have a receiver parameter.
            return;
        }

        // Allowed type parameter names = method generic parameters.
        var allowedTypeParams = new HashSet<string>(
            method.GenericParameters.Select(p => p.Name),
            StringComparer.Ordinal);

        sb.Append("  ");
        sb.Append(method.TsEmitName);

        if (method.GenericParameters.Length > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", method.GenericParameters.Select(p => p.Name)));
            sb.Append('>');
        }

        sb.Append('(');

        var paramStrings = new List<string>
        {
            $"this: {TypeRefPrinter.Print(method.Parameters[0].Type, resolver, ctx, allowedTypeParams)}"
        };

        foreach (var param in method.Parameters.Skip(1))
        {
            var paramType = TypeRefPrinter.Print(param.Type, resolver, ctx, allowedTypeParams);
            var paramName = TypeScriptReservedWords.SanitizeParameterName(param.Name);

            // Preserve optional/default parameters and params arrays.
            // EF Core async extensions commonly use optional CancellationToken parameters which should be
            // callable without arguments (matches C# default-parameter semantics).
            if (param.IsParams)
            {
                paramStrings.Add($"...{paramName}: {paramType}");
            }
            else if (param.HasDefaultValue)
            {
                paramStrings.Add($"{paramName}?: {paramType}");
            }
            else
            {
                paramStrings.Add($"{paramName}: {paramType}");
            }
        }

        sb.Append(string.Join(", ", paramStrings));
        sb.Append(')');

        var returnType = TypeRefPrinter.Print(method.ReturnType, resolver, ctx, allowedTypeParams);
        sb.Append($": Rewrap<this, {returnType}>");
        sb.AppendLine(";");
    }

    private static void EmitExtensionMethodsHelper(
        StringBuilder sb,
        string declaringNamespace,
        IReadOnlyList<ExtensionBucketPlan> buckets)
    {
        var extensionMethodsTypeName = GetExtensionMethodsTypeName(declaringNamespace);
        var methodsTableName = GetMethodsTableTypeName(declaringNamespace);
        var extApplierTypeName = GetExtApplierTypeName(declaringNamespace);
        var extKey = string.IsNullOrEmpty(declaringNamespace) ? "_root" : declaringNamespace;

        sb.AppendLine($"// Generic helper type for extension methods in namespace: {declaringNamespace}");

        // Applier interface stored in __tsonic_ext (used by Rewrap<this, ReturnShape>).
        //
        // IMPORTANT: This MUST be an HKT-style "applier" (not a generic function type).
        // The HKT encoding forces exact substitution via intersection:
        //   __TsonicApplyApplier<A, Shape> = (A & { __tsonic_shape: Shape })[\"__tsonic_type\"]
        sb.AppendLine($"interface {extApplierTypeName} {{");
        sb.AppendLine("  __tsonic_shape: unknown;");
        sb.AppendLine($"  __tsonic_type: {methodsTableName};");
        sb.AppendLine("}");
        sb.AppendLine();

        // Arrays: allow ExtensionMethods_<Ns><T[]> to participate in CLR interface-based resolution
        // by explicitly intersecting with IEnumerable_1<T> when this namespace includes IEnumerable_1
        // extensions (LINQ is the primary motivation).
        var hasIEnumerable1Bucket = buckets.Any(b =>
            b.TargetType.Namespace == "System.Collections.Generic" &&
            b.TargetType.TsEmitName == "IEnumerable_1");

        sb.AppendLine($"export type {extensionMethodsTypeName}<TShape> =");
        sb.AppendLine("  TShape extends null | undefined ? TShape");
        sb.AppendLine("  : TShape extends void ? void");

        if (hasIEnumerable1Bucket)
        {
            sb.AppendLine($"  : TShape extends (infer T)[] ? (TShape & System_Collections_Generic.IEnumerable_1<T> & __TsonicWithExt<TShape, \"{extKey}\", {extApplierTypeName}> & {methodsTableName})");
            sb.AppendLine($"  : TShape & __TsonicWithExt<TShape, \"{extKey}\", {extApplierTypeName}> & {methodsTableName};");
        }
        else
        {
            sb.AppendLine($"  : TShape & __TsonicWithExt<TShape, \"{extKey}\", {extApplierTypeName}> & {methodsTableName};");
        }

        sb.AppendLine();
    }
}

