using System.Collections.Immutable;
using System.Text;
using tsbindgen.Analysis;
using tsbindgen.Emit.Printers;
using tsbindgen.Model.Symbols.MemberSymbols;
using tsbindgen.Renaming;
using tsbindgen.Model;

namespace tsbindgen.Emit;

/// <summary>
/// Emits extension method bucket interfaces to __internal/extensions/index.d.ts.
/// Each bucket contains all extension methods for a specific target type.
/// Example: __Ext_IEnumerable_1&lt;T&gt; contains Select, Where, etc.
/// </summary>
public static class ExtensionsEmitter
{
    /// <summary>
    /// Emit the __internal/extensions/index.d.ts file containing all bucket interfaces.
    /// </summary>
    /// <param name="ctx">Build context</param>
    /// <param name="plan">Extension methods plan with all buckets</param>
    /// <param name="graph">Symbol graph for type resolution</param>
    /// <param name="outputDirectory">Root output directory</param>
    public static void Emit(BuildContext ctx, ExtensionMethodsPlan plan, SymbolGraph graph, string outputDirectory)
    {
        if (plan.Buckets.Length == 0)
        {
            ctx.Log("ExtensionsEmitter", "No extension methods found - skipping extensions file");
            return;
        }

        ctx.Log("ExtensionsEmitter", $"Emitting extension method buckets: {plan.Buckets.Length} buckets");

        // Create __internal/extensions directory
        var extensionsDir = Path.Combine(outputDirectory, "__internal", "extensions");
        Directory.CreateDirectory(extensionsDir);

        // Generate file content
        var content = GenerateExtensionsFile(ctx, plan, graph);

        // Write file
        var filePath = Path.Combine(extensionsDir, "index.d.ts");
        File.WriteAllText(filePath, content);

        ctx.Log("ExtensionsEmitter", $"Wrote {filePath}");
    }

    /// <summary>
    /// Generate the complete extensions file content.
    /// </summary>
    private static string GenerateExtensionsFile(BuildContext ctx, ExtensionMethodsPlan plan, SymbolGraph graph)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Extension Method Buckets");
        sb.AppendLine("// This file contains bucket interfaces for C# extension methods.");
        sb.AppendLine("// Each __Ext_* interface groups all extension methods for a specific target type.");
        sb.AppendLine();

        // Collect all namespaces used in extension method signatures
        var namespacesUsed = new HashSet<string>();
        foreach (var bucket in plan.Buckets)
        {
            // Add the target type's namespace (needed for ExtensionMethods<TShape> helper)
            namespacesUsed.Add(bucket.TargetType.Namespace);

            foreach (var method in bucket.Methods)
            {
                // Collect from return type
                CollectNamespaces(method.ReturnType, namespacesUsed, graph);

                // Collect from parameters (skip first 'this' parameter)
                foreach (var param in method.Parameters.Skip(1))
                {
                    CollectNamespaces(param.Type, namespacesUsed, graph);
                }
            }
        }

        // Generate namespace imports
        // Extension methods file is at __internal/extensions/index.d.ts
        // Namespaces are at ../../{Namespace}/internal/index.js
        if (namespacesUsed.Count > 0)
        {
            sb.AppendLine("// Import namespace modules for cross-namespace type references");
            foreach (var ns in namespacesUsed.OrderBy(n => n))
            {
                var namespaceAlias = ns.Replace('.', '_');
                var importPath = $"../../{ns}/internal/index.js";
                sb.AppendLine($"import * as {namespaceAlias} from \"{importPath}\";");
            }
            sb.AppendLine();
        }

        // Import primitive type aliases from @tsonic/core
        sb.AppendLine("// Import primitive type aliases");
        sb.AppendLine("import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';");
        sb.AppendLine();

        // Import CLR primitive type aliases from System namespace
        // These are needed for generic type arguments (e.g., Span_1<Char> instead of Span_1<char>)
        sb.AppendLine("// Import CLR type aliases for generic type arguments");
        sb.AppendLine("import * as System_Internal from \"../../System/internal/index.js\";");
        sb.AppendLine();

        // Import ptr from @tsonic/core (needed for pointer types)
        // Note: ref/out/in modifiers are ABI semantics tracked in metadata, not TS types
        sb.AppendLine("// Import unsafe type markers");
        sb.AppendLine("import type { ptr } from '@tsonic/core/types.js';");
        sb.AppendLine();

        // Create TypeNameResolver for this file
        // Extension methods file needs all cross-namespace types to be fully qualified
        // Use a dummy namespace "__internal.extensions" and enable facade mode
        // This triggers cross-namespace qualification for all type references
        var resolver = new TypeNameResolver(ctx, graph, importPlan: null, currentNamespace: "__internal.extensions", facadeMode: true);

        // Emit each bucket interface
        foreach (var bucket in plan.Buckets)
        {
            EmitBucketInterface(sb, ctx, bucket, resolver);
            sb.AppendLine();
        }

        // Emit ExtensionMethods<TShape> helper type
        EmitExtensionMethodsHelper(sb, plan, graph);

        return sb.ToString();
    }

    /// <summary>
    /// Recursively collect all namespaces used in a type reference.
    /// </summary>
    private static void CollectNamespaces(Model.Types.TypeReference typeRef, HashSet<string> namespaces, SymbolGraph graph)
    {
        switch (typeRef)
        {
            case Model.Types.NamedTypeReference named:
                // Look up the type in the graph
                if (graph.TypeIndex.TryGetValue(named.FullName, out var typeSymbol))
                {
                    // Add the namespace
                    namespaces.Add(typeSymbol.Namespace);
                }

                // Collect from type arguments
                foreach (var arg in named.TypeArguments)
                {
                    CollectNamespaces(arg, namespaces, graph);
                }
                break;

            case Model.Types.ArrayTypeReference array:
                CollectNamespaces(array.ElementType, namespaces, graph);
                break;

            case Model.Types.ByRefTypeReference byRef:
                CollectNamespaces(byRef.ReferencedType, namespaces, graph);
                break;

            case Model.Types.PointerTypeReference pointer:
                CollectNamespaces(pointer.PointeeType, namespaces, graph);
                break;

            case Model.Types.NestedTypeReference nested:
                CollectNamespaces(nested.FullReference, namespaces, graph);
                break;
        }
    }

    /// <summary>
    /// Check if any method in the bucket requires IEquatable constraint for a type parameter.
    /// This happens when methods have "where T : IEquatable&lt;T&gt;" constraints.
    /// </summary>
    private static bool BucketNeedsIEquatableConstraint(ExtensionBucketPlan bucket, string paramName)
    {
        foreach (var method in bucket.Methods)
        {
            // Check if any of the method's generic parameters that match paramName have IEquatable constraint
            foreach (var genericParam in method.GenericParameters)
            {
                if (genericParam.Name == paramName)
                {
                    // Check constraints on this generic parameter
                    if (genericParam.Constraints != null)
                    {
                        foreach (var constraint in genericParam.Constraints)
                        {
                            // Check if constraint is IEquatable<T>
                            if (constraint is Model.Types.NamedTypeReference namedConstraint &&
                                namedConstraint.FullName.Contains("IEquatable"))
                            {
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }

    /// <summary>
    /// Emit a single bucket interface.
    /// </summary>
    private static void EmitBucketInterface(StringBuilder sb, BuildContext ctx, ExtensionBucketPlan bucket, TypeNameResolver resolver)
    {
        var targetType = bucket.TargetType;

        // Interface declaration with generic parameters
        sb.Append($"export interface {bucket.BucketInterfaceName}");

        // Add generic parameters if target type is generic
        if (targetType.GenericParameters.Length > 0)
        {
            sb.Append('<');
            var genericParams = new List<string>();
            foreach (var param in targetType.GenericParameters)
            {
                // Check if any method in this bucket requires IEquatable constraint for this parameter
                var needsIEquatable = BucketNeedsIEquatableConstraint(bucket, param.Name);

                if (needsIEquatable)
                {
                    // Add IEquatable constraint: T extends IEquatable_1<T>
                    genericParams.Add($"{param.Name} extends System.IEquatable_1<{param.Name}>");
                }
                else
                {
                    // No constraint needed
                    genericParams.Add(param.Name);
                }
            }
            sb.Append(string.Join(", ", genericParams));
            sb.Append('>');
        }

        sb.AppendLine(" {");

        // Emit methods as proper TypeScript overloads (no numeric suffixes)
        // Group by base CLR name and emit multiple signatures with same name
        foreach (var method in bucket.Methods)
        {
            EmitExtensionMethod(sb, ctx, method, resolver, targetType.GenericParameters);
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Emit an extension method as an instance method in the bucket interface.
    /// Drops the first 'this' parameter and emits remaining parameters.
    /// Unifies method-level generics with target type's generics BY POSITION (not name).
    /// Example: Where&lt;TSource&gt;(this IEnumerable&lt;TSource&gt;, ...) becomes Where(...) using bucket's T.
    /// </summary>
    private static void EmitExtensionMethod(
        StringBuilder sb,
        BuildContext ctx,
        MethodSymbol method,
        TypeNameResolver resolver,
        IReadOnlyList<Model.Symbols.GenericParameterSymbol> targetGenericParameters)
    {
        // Skip the first parameter (the 'this' parameter) for extension methods
        var instanceParams = method.Parameters.Skip(1).ToArray();

        sb.Append("  ");

        // Method name: use CLR name (no numeric suffixes)
        var methodName = method.ClrName;
        sb.Append(methodName);

        // Build generic substitution map and unified generics set BY POSITION from receiver type
        // Example: IEnumerable<TSource> receiver → target IEnumerable<T> means TSource→T
        // unifiedGenerics includes ALL method generics that map to bucket (even if same name)
        var (genericSubstitution, unifiedGenerics) = BuildGenericSubstitution(method, targetGenericParameters);

        // Determine which method generics remain after unification
        // Method generics that map to bucket generics are removed (shouldn't shadow bucket's T)
        var methodGenericsToEmit = method.GenericParameters
            .Where(p => !unifiedGenerics.Contains(p.Name))
            .ToList();

        // Build allowed type parameter names (bucket generics + remaining method generics)
        var allowedTypeParams = new HashSet<string>(targetGenericParameters.Select(p => p.Name));
        foreach (var param in methodGenericsToEmit)
        {
            allowedTypeParams.Add(param.Name);
        }

        // Only emit method-level generics if there are non-unified ones
        if (methodGenericsToEmit.Count > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", methodGenericsToEmit.Select(p => p.Name)));
            sb.Append('>');
        }

        // Parameters - apply generic substitution
        sb.Append('(');
        var paramStrings = new List<string>();
        foreach (var param in instanceParams)
        {
            var paramType = PrintTypeWithSubstitution(param.Type, resolver, ctx, allowedTypeParams, genericSubstitution);
            var paramName = TypeScriptReservedWords.SanitizeParameterName(param.Name);
            paramStrings.Add($"{paramName}: {paramType}");
        }
        sb.Append(string.Join(", ", paramStrings));
        sb.Append(')');

        // Return type - apply generic substitution
        var returnType = PrintTypeWithSubstitution(method.ReturnType, resolver, ctx, allowedTypeParams, genericSubstitution);
        sb.Append($": {returnType}");

        sb.AppendLine(";");
    }

    /// <summary>
    /// Build generic unification info from method generics to bucket generics BY POSITION.
    /// Analyzes the receiver type (first param) and matches its type arguments to target type params.
    /// Returns:
    ///   - substitution: Name mappings where method and bucket names differ (e.g., "TSource" → "T")
    ///   - unifiedGenerics: ALL method generic names that map to bucket generics (including same names)
    ///
    /// Example: Where&lt;TSource&gt;(this IEnumerable&lt;TSource&gt;) with bucket IEnumerable&lt;T&gt;
    ///          returns substitution: { "TSource" → "T" }, unifiedGenerics: { "TSource" }
    ///
    /// Example: Contains&lt;T&gt;(this IEnumerable&lt;T&gt;) with bucket IEnumerable&lt;T&gt;
    ///          returns substitution: {}, unifiedGenerics: { "T" }  (no rename needed, but T is unified)
    /// </summary>
    private static (Dictionary<string, string> substitution, HashSet<string> unifiedGenerics) BuildGenericSubstitution(
        MethodSymbol method,
        IReadOnlyList<Model.Symbols.GenericParameterSymbol> targetGenericParameters)
    {
        var substitution = new Dictionary<string, string>();
        var unifiedGenerics = new HashSet<string>();

        if (method.Parameters.Length == 0 || targetGenericParameters.Count == 0)
            return (substitution, unifiedGenerics);

        // Get receiver type (first 'this' parameter)
        var receiverType = method.Parameters[0].Type;

        // Extract type arguments from receiver if it's a generic named type
        if (receiverType is Model.Types.NamedTypeReference namedReceiver && namedReceiver.TypeArguments.Count > 0)
        {
            // Match type arguments by position to target generic parameters
            var minCount = Math.Min(namedReceiver.TypeArguments.Count, targetGenericParameters.Count);
            for (int i = 0; i < minCount; i++)
            {
                var receiverArg = namedReceiver.TypeArguments[i];

                // If the receiver's type argument is a generic parameter reference,
                // this method generic is unified with the bucket's corresponding parameter
                if (receiverArg is Model.Types.GenericParameterReference gpRef)
                {
                    var targetParamName = targetGenericParameters[i].Name;

                    // Always mark this method generic as unified (shouldn't be emitted on method)
                    unifiedGenerics.Add(gpRef.Name);

                    // Only add to substitution if names differ (actual rename needed)
                    // Example: TSource (method) → T (bucket)
                    if (gpRef.Name != targetParamName)
                    {
                        substitution[gpRef.Name] = targetParamName;
                    }
                }
            }
        }

        return (substitution, unifiedGenerics);
    }

    /// <summary>
    /// Print a type reference with generic substitutions applied.
    /// Replaces generic parameter names according to the substitution map.
    /// </summary>
    private static string PrintTypeWithSubstitution(
        Model.Types.TypeReference typeRef,
        TypeNameResolver resolver,
        BuildContext ctx,
        HashSet<string> allowedTypeParams,
        Dictionary<string, string> genericSubstitution)
    {
        // First, apply substitution to the type reference
        var substitutedRef = ApplySubstitution(typeRef, genericSubstitution);

        // Then print using TypeRefPrinter
        return TypeRefPrinter.Print(substitutedRef, resolver, ctx, allowedTypeParams);
    }

    /// <summary>
    /// Apply generic substitutions to a type reference, returning a new type reference.
    /// Uses `with` expressions to properly copy all required properties from originals.
    /// </summary>
    private static Model.Types.TypeReference ApplySubstitution(
        Model.Types.TypeReference typeRef,
        Dictionary<string, string> genericSubstitution)
    {
        if (genericSubstitution.Count == 0)
            return typeRef;

        return typeRef switch
        {
            // Rename generic parameter references if in substitution map
            Model.Types.GenericParameterReference gpRef when genericSubstitution.TryGetValue(gpRef.Name, out var newName) =>
                gpRef with { Name = newName },

            // Recursively apply substitution to type arguments in named type references
            Model.Types.NamedTypeReference named when named.TypeArguments.Count > 0 =>
                named with
                {
                    TypeArguments = named.TypeArguments.Select(arg => ApplySubstitution(arg, genericSubstitution)).ToImmutableList()
                },

            // Recursively apply substitution to element type in arrays
            Model.Types.ArrayTypeReference arr =>
                arr with { ElementType = ApplySubstitution(arr.ElementType, genericSubstitution) },

            // Recursively apply substitution to referenced type in byrefs
            Model.Types.ByRefTypeReference byRef =>
                byRef with { ReferencedType = ApplySubstitution(byRef.ReferencedType, genericSubstitution) },

            // Recursively apply substitution to pointee type in pointers
            Model.Types.PointerTypeReference ptr =>
                ptr with { PointeeType = ApplySubstitution(ptr.PointeeType, genericSubstitution) },

            _ => typeRef // No substitution needed
        };
    }

    /// <summary>
    /// Emit the ExtensionMethods&lt;TShape&gt; conditional type helper.
    /// This maps base types to their extension method buckets.
    /// </summary>
    private static void EmitExtensionMethodsHelper(StringBuilder sb, ExtensionMethodsPlan plan, SymbolGraph graph)
    {
        if (plan.Buckets.Length == 0)
        {
            return;
        }

        sb.AppendLine("// Generic helper type for mapping shapes to their extension methods");
        sb.AppendLine("// Usage: type Rich<T> = BaseType<T> & ExtensionMethods<BaseType<T>>");
        sb.AppendLine("export type ExtensionMethods<TShape> =");

        var isFirst = true;
        foreach (var bucket in plan.Buckets)
        {
            var targetType = bucket.TargetType;
            var namespaceAlias = targetType.Namespace.Replace('.', '_');

            var prefix = isFirst ? "  " : ": ";
            sb.Append(prefix);

            // Build the conditional: TShape extends Namespace.TypeName<...> ?
            sb.Append($"TShape extends {namespaceAlias}.{targetType.TsEmitName}");

            if (targetType.GenericParameters.Length > 0)
            {
                // Generic type: use infer to extract type arguments
                // If bucket has IEquatable constraint, propagate it to infer clause
                // Example: TShape extends System.Span_1<infer T extends IEquatable_1<T>> ? __Ext_Span_1<T>
                var inferParams = new List<string>();
                for (int i = 0; i < targetType.GenericParameters.Length; i++)
                {
                    var param = targetType.GenericParameters[i];
                    var needsIEquatable = BucketNeedsIEquatableConstraint(bucket, param.Name);

                    if (needsIEquatable)
                    {
                        inferParams.Add($"infer T{i} extends System.IEquatable_1<T{i}>");
                    }
                    else
                    {
                        inferParams.Add($"infer T{i}");
                    }
                }
                sb.Append($"<{string.Join(", ", inferParams)}> ? {bucket.BucketInterfaceName}<{string.Join(", ", Enumerable.Range(0, targetType.GenericParameters.Length).Select(i => $"T{i}"))}>");
            }
            else
            {
                // Non-generic type
                sb.Append($" ? {bucket.BucketInterfaceName}");
            }

            sb.AppendLine();
            isFirst = false;
        }

        // Special case: native T[] arrays get IEnumerable_1 extensions (LINQ, etc.)
        // This allows ExtensionMethods<string[]> to resolve to __Ext_IEnumerable_1<string>
        sb.AppendLine(": TShape extends (infer T)[] ? __Ext_IEnumerable_1<T>");

        // Default case: no extensions available
        sb.AppendLine("  : {};");
        sb.AppendLine();
    }
}
