using System;
using System.IO;
using System.Linq;
using System.Text;
using tsbindgen.Model;
using tsbindgen.Plan;

namespace tsbindgen.Emit;

/// <summary>
/// Emits facade/index.d.ts files for each namespace.
/// Generates public-facing TypeScript declarations with proper imports and re-exports.
/// </summary>
public static class FacadeEmitter
{
    public static void Emit(BuildContext ctx, EmissionPlan plan, string outputDirectory)
    {
        ctx.Log("FacadeEmitter", "Generating facade index.d.ts files...");

        var emittedCount = 0;

        // Process each namespace in order
        foreach (var nsOrder in plan.EmissionOrder.Namespaces)
        {
            var ns = nsOrder.Namespace;
            ctx.Log("FacadeEmitter", $"  Emitting facade for: {ns.Name}");

            // Generate facade content
            var content = GenerateFacade(ctx, plan, ns);

            // Write to file: output/Namespace.Name.d.ts (flat ESM structure)
            // Use mapped output name if namespace-map is configured
            var outputName = NamespacePathMapper.GetOutputName(ns, ctx);
            var outputFile = Path.Combine(outputDirectory, $"{outputName}.d.ts");
            File.WriteAllText(outputFile, content);

            ctx.Log("FacadeEmitter", $"    → {outputFile}");
            emittedCount++;
        }

        ctx.Log("FacadeEmitter", $"Generated {emittedCount} facade files");
    }

    private static string GenerateFacade(BuildContext ctx, EmissionPlan plan, Model.Symbols.NamespaceSymbol ns)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Architecture");
        sb.AppendLine($"// Namespace: {ns.Name}");
        sb.AppendLine($"// Facade - Public API Surface");
        sb.AppendLine();

        // Import from Namespace/internal/index.d.ts (flat ESM structure)
        // Use mapped output name if namespace-map is configured
        sb.AppendLine("// Import internal declarations");
        var outputName = NamespacePathMapper.GetOutputName(ns, ctx);
        var internalImportPath = ns.IsRoot ? "./_root/index.js" : $"./{outputName}/internal/index.js";
        sb.AppendLine($"import * as Internal from '{internalImportPath}';");
        sb.AppendLine();

        // Check if this namespace has flattened classes - they need additional imports
        EmitFlattenedClassImports(sb, ctx, plan, ns);

        if (plan.Imports.NamespaceExports.TryGetValue(ns.Name, out var exports) && exports.Count > 0)
        {
            // Precompute stem info
            var stemGroups = exports
                .GroupBy(e => GetStem(e.ExportName))
                .ToDictionary(g => g.Key, g => g.ToList());

            var nonGenericRenames = new Dictionary<string, string>(StringComparer.Ordinal); // original export name -> renamed alias
            var stemsWithGeneric = new HashSet<string>(StringComparer.Ordinal);

            // Detect multi-arity families based on CLR identity (types sharing CLR base name with different arities)
            // Uses symbol-based detection (TypeSymbol) for stability before any facade renaming
            var multiArityFamilies = MultiArityFamilyDetect.FromNamespace(ns, ctx.Renamer, ctx);
            var reservedStems = multiArityFamilies.Select(f => f.PublicStem).ToHashSet(StringComparer.Ordinal);

            var potentialFriendlyStems = new HashSet<string>(exports
                .Where(e => e.SourceType.GenericParameters.Length > 0)
                .Select(e => GetStem(e.ExportName)), StringComparer.Ordinal);

            foreach (var kvp in stemGroups)
            {
                var stem = kvp.Key;
                var group = kvp.Value;
                var hasNonGeneric = group.Any(e => e.Arity == 0);
                var hasGeneric = group.Any(e => e.Arity > 0);
                if (hasNonGeneric && hasGeneric)
                {
                    stemsWithGeneric.Add(stem);
                    if (!reservedStems.Contains(stem))
                    {
                        // Rename the non-generic export to <Stem>_0
                        var nonGenericExport = group.First(e => e.Arity == 0);
                        nonGenericRenames[nonGenericExport.ExportName] = stem + "_0";
                    }
                }
            }

            // Flat ESM: import cross-namespace types for constraints (type-only)
            var importedTypeNames = new HashSet<string>(StringComparer.Ordinal);

            if (plan.Imports.NamespaceImports.TryGetValue(ns.Name, out var imports) && imports.Count > 0)
            {
                sb.AppendLine("// Cross-namespace type imports for constraints");
                foreach (var import in imports.OrderBy(i => i.ImportPath))
                {
                    var typeImports = import.TypeImports;
                    if (typeImports.Count == 0)
                        continue;

                    var typeList = string.Join(", ", typeImports
                        .OrderBy(ti => ti.TypeName)
                        .Select(ti =>
                        {
                            var name = ti.TypeName;
                            var needsAlias = potentialFriendlyStems.Contains(GetStem(name)) && string.IsNullOrEmpty(ti.Alias);
                            var alias = needsAlias ? name + "_Imported" : ti.Alias;
                            var emit = alias != null ? $"{name} as {alias}" : name;
                            importedTypeNames.Add(alias ?? name);
                            return emit;
                        }));

                    var facadePath = import.ImportPath;

                    // Facade files are at root level (Namespace.d.ts)
                    // Paths from PathPlanner are like "../../OtherNs/internal/index.js" (relative to internal/)
                    // Convert to "./" since facade is at root
                    if (facadePath.StartsWith("../../", StringComparison.Ordinal))
                    {
                        facadePath = "./" + facadePath.Substring(6);
                    }

                    sb.AppendLine($"import type {{ {typeList} }} from '{facadePath}';");
                }
                sb.AppendLine();
            }

            // CURATED FACADE EXPORTS: Individual exports only (no export *)
            // This prevents leaking internal $instance and $views types to end users
            sb.AppendLine("// Public API exports (curated - no internal $instance/$views leakage)");

            // TS2304 FIX: Create TypeNameResolver in facade mode to qualify cross-namespace types
            // This ensures constraints like "T extends IEquatable_1<T>" become "T extends System.IEquatable_1<T>"
            // Use ImportPlan so type-only imports can be referenced without qualification
            var resolver = new TypeNameResolver(ctx, plan.Graph, importPlan: plan.Imports, currentNamespace: ns.Name, facadeMode: false);

            // Track friendly aliases (arityless) to avoid duplicates
            var friendlyAliases = new HashSet<string>();
            var existingNames = new HashSet<string>(exports.Select(e => e.ExportName));
            var skipFriendlyNames = new HashSet<string>(importedTypeNames, StringComparer.Ordinal);
            foreach (var reserved in reservedStems)
            {
                skipFriendlyNames.Add(reserved);
            }

            foreach (var export in exports)
            {
                // Skip all multi-arity family members - they get sentinel-ladder aliases below
                if (reservedStems.Contains(GetStem(export.ExportName)))
                {
                    continue;
                }

                var exportKind = export.ExportKind switch
                {
                    ExportKind.Class => "class",
                    ExportKind.Interface => "interface",
                    ExportKind.Enum => "enum",
                    ExportKind.Type => "type",
                    ExportKind.Const => "const",
                    _ => "type"
                };

                // TS2315 FIX: Skip facade exports for types that lose their generics during emission
                // Static classes with generic static members are emitted as non-generic classes
                // (TypeScript doesn't support class-level generics for static-only classes)
                if (export.SourceType.Kind == Model.Symbols.TypeKind.StaticNamespace &&
                    export.SourceType.GenericParameters.Length > 0)
                {
                    ctx.Log("TS2315Fix", $"Skipping facade export for {export.ExportName} (static class with generics - emitted without generic parameters)");
                    continue;
                }

                // Apply rename for non-generic when sharing stem with generic
                var aliasName = nonGenericRenames.TryGetValue(export.ExportName, out var renamed)
                    ? renamed
                    : export.ExportName;

                // SKIP REDUNDANT EXPORTS: If aliasName == exportName, there's no alias benefit
                // We only want friendly names (List), not internal names (List_1)
                // The friendly alias below will emit the useful "List" export
                if (aliasName == export.ExportName && export.SourceType.GenericParameters.Length > 0)
                {
                    // Skip - the friendly alias below will handle this type
                    // Only skip generics because they get friendly aliases; non-generics are their own final name
                }
                else
                {
                    // Emit primary export (uses unified helper)
                    EmitFacadeExport(sb, aliasName, export.SourceType, export.ExportName, resolver, ctx, outputName);
                }

                // FRIENDLY GENERIC ALIAS: Provide arity-less name (List instead of List_1)
                if (export.SourceType.GenericParameters.Length > 0)
                {
                    var suffix = $"_{export.SourceType.GenericParameters.Length}";
                    if (export.ExportName.EndsWith(suffix, StringComparison.Ordinal))
                    {
                        var friendlyName = export.ExportName.Substring(0, export.ExportName.Length - suffix.Length);
                        // Skip if we've already emitted or name collides with imports/reserved helpers
                        if (!string.IsNullOrWhiteSpace(friendlyName) &&
                            !skipFriendlyNames.Contains(friendlyName) &&
                            friendlyAliases.Add(friendlyName))
                        {
                            // Emit friendly alias (uses same unified helper)
                            EmitFacadeExport(sb, friendlyName, export.SourceType, export.ExportName, resolver, ctx, outputName);
                        }
                    }
                }
            }

            // Multi-arity families: emit VALUE exports for arity-0 members (constructors/static namespaces).
            // The sentinel-ladder aliases below provide the TYPE surface for the family; this provides
            // the VALUE surface without leaking internal exports or conflicting with the type alias.
            if (multiArityFamilies.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine("// Multi-arity family value exports (arity-0 constructors/static namespaces)");

                foreach (var family in multiArityFamilies.OrderBy(f => f.PublicStem))
                {
                    var arity0Export = exports.FirstOrDefault(e =>
                        e.Arity == 0 &&
                        string.Equals(GetStem(e.ExportName), family.PublicStem, StringComparison.Ordinal));

                    if (arity0Export is null)
                        continue;

                    if (!NeedsValueExport(arity0Export.SourceType.Kind))
                        continue;

                    var internalValueName = GetInternalValueName(arity0Export.SourceType, ctx);
                    sb.AppendLine($"export const {family.PublicStem}: typeof Internal.{internalValueName};");
                }
            }

            // Emit sentinel-ladder aliases for all detected multi-arity families
            if (multiArityFamilies.Length > 0)
            {
                sb.AppendLine();
                MultiArityAliasEmit.EmitSentinelDeclaration(sb);
                foreach (var family in multiArityFamilies.OrderBy(f => f.PublicStem))
                {
                    MultiArityAliasEmit.Emit(sb, family, resolver, ctx, ns.Name);
                }
            }

            // Export primitive $instance interfaces for global type augmentation
            // These are needed by @tsonic/globals to extend global String, Number, Boolean interfaces
            if (ns.Name == "System")
            {
                EmitPrimitiveInstanceExports(sb, exports);
            }
        }

        // Re-export extension method helper for this namespace (C# using semantics)
        if (plan.ExtensionMethods.Buckets.Any(b => b.DeclaringNamespace == ns.Name))
        {
            var nsAlias = string.IsNullOrEmpty(ns.Name) ? "_root" : ns.Name.Replace('.', '_');
            sb.AppendLine("// Extension methods (C# using semantics)");
            sb.AppendLine($"export type {{ ExtensionMethods_{nsAlias} as ExtensionMethods }} from './__internal/extensions/index.js';");
            sb.AppendLine();
        }

        // Emit flattened exports from static classes (--flatten-class)
        EmitFlattenedExports(sb, ctx, plan, ns);

        return sb.ToString();
    }

    /// <summary>
    /// Emits imports required by flattened static class methods.
    /// The facade file needs primitive type aliases and namespace imports for types used in flattened exports.
    /// This is separate from the cross-namespace constraint imports which serve a different purpose.
    /// </summary>
    private static void EmitFlattenedClassImports(
        StringBuilder sb,
        BuildContext ctx,
        EmissionPlan plan,
        Model.Symbols.NamespaceSymbol ns)
    {
        var flattenedClasses = ctx.Policy.Emission.FlattenedClasses;
        if (flattenedClasses.Count == 0)
            return;

        // Find types in this namespace that are marked for flattening
        var typesToFlatten = ns.Types
            .Where(t => flattenedClasses.Contains(t.ClrFullName) && t.IsStatic)
            .ToList();

        if (typesToFlatten.Count == 0)
            return;

        // Collect all namespaces and type references used by flattened methods
        var referencedNamespaces = new HashSet<string>();
        var usesPrimitives = false;

        foreach (var type in typesToFlatten)
        {
            var staticMethods = type.Members.Methods
                .Where(m => m.IsStatic && m.EmitScope != Model.Symbols.MemberSymbols.EmitScope.Omitted);

            foreach (var method in staticMethods)
            {
                // Check return type
                CollectTypeReferencesForImports(method.ReturnType, ns.Name, referencedNamespaces, ref usesPrimitives, plan.Graph, ctx);

                // Check parameters
                foreach (var param in method.Parameters)
                {
                    CollectTypeReferencesForImports(param.Type, ns.Name, referencedNamespaces, ref usesPrimitives, plan.Graph, ctx);
                }
            }
        }

        // Emit primitive imports if needed
        if (usesPrimitives)
        {
            sb.AppendLine("// Primitive type aliases for flattened exports");
            sb.AppendLine("import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';");
            sb.AppendLine();
        }

        // Emit namespace imports for referenced external namespaces
        if (referencedNamespaces.Count > 0)
        {
            sb.AppendLine("// Namespace imports for flattened exports");
            foreach (var targetNs in referencedNamespaces.OrderBy(n => n))
            {
                var namespaceAlias = targetNs.Replace('.', '_') + "_Internal";
                string importPath;
                if (ctx.LibraryContract != null && ctx.LibraryContract.ClrFullNameToNamespace.ContainsValue(targetNs))
                {
                    var targetPackage = ctx.LibraryContract.GetPackageForNamespace(targetNs);
                    importPath = $"{targetPackage}/{targetNs}.js";
                }
                else
                {
                    importPath = Plan.PathPlanner.GetFacadeSpecifier(ctx, ns.Name, targetNs);
                }
                sb.AppendLine($"import * as {namespaceAlias} from \"{importPath}\";");
            }
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Recursively collects namespace and primitive type references from a type reference.
    /// Used to determine what imports are needed for flattened exports.
    /// </summary>
    private static void CollectTypeReferencesForImports(
        Model.Types.TypeReference? typeRef,
        string currentNamespace,
        HashSet<string> referencedNamespaces,
        ref bool usesPrimitives,
        SymbolGraph graph,
        BuildContext ctx)
    {
        if (typeRef == null) return;

        switch (typeRef)
        {
            case Model.Types.NamedTypeReference named:
                // Check if this is a primitive type (uses lowercase alias like double, int)
                if (IsPrimitiveType(named.FullName))
                {
                    usesPrimitives = true;
                }
                else if (!string.IsNullOrEmpty(named.Namespace) && named.Namespace != currentNamespace)
                {
                    // External namespace - need namespace import for qualified types
                    referencedNamespaces.Add(named.Namespace);
                }

                // Recurse into type arguments
                foreach (var arg in named.TypeArguments)
                {
                    CollectTypeReferencesForImports(arg, currentNamespace, referencedNamespaces, ref usesPrimitives, graph, ctx);
                }
                break;

            case Model.Types.ArrayTypeReference arr:
                CollectTypeReferencesForImports(arr.ElementType, currentNamespace, referencedNamespaces, ref usesPrimitives, graph, ctx);
                break;

            case Model.Types.ByRefTypeReference byref:
                CollectTypeReferencesForImports(byref.ReferencedType, currentNamespace, referencedNamespaces, ref usesPrimitives, graph, ctx);
                break;

            case Model.Types.PointerTypeReference ptr:
                CollectTypeReferencesForImports(ptr.PointeeType, currentNamespace, referencedNamespaces, ref usesPrimitives, graph, ctx);
                break;
        }
    }

    /// <summary>
    /// Checks if a CLR full name is a primitive numeric type that uses a lowercase TypeScript alias.
    /// These need to be imported from @tsonic/core/types.js.
    /// </summary>
    private static bool IsPrimitiveType(string clrFullName)
    {
        return clrFullName switch
        {
            "System.SByte" => true,
            "System.Byte" => true,
            "System.Int16" => true,
            "System.UInt16" => true,
            "System.Int32" => true,
            "System.UInt32" => true,
            "System.Int64" => true,
            "System.UInt64" => true,
            "System.Int128" => true,
            "System.UInt128" => true,
            "System.Half" => true,
            "System.Single" => true,
            "System.Double" => true,
            "System.Decimal" => true,
            "System.IntPtr" => true,
            "System.UIntPtr" => true,
            "System.Char" => true,
            _ => false
        };
    }

    /// <summary>
    /// Emits flattened exports from static classes marked with --flatten-class.
    /// Converts static methods to top-level function declarations.
    /// Example: Globals.parseInt becomes `export function parseInt(s: string): int;`
    /// </summary>
    private static void EmitFlattenedExports(
        StringBuilder sb,
        BuildContext ctx,
        EmissionPlan plan,
        Model.Symbols.NamespaceSymbol ns)
    {
        var flattenedClasses = ctx.Policy.Emission.FlattenedClasses;
        if (flattenedClasses.Count == 0)
            return;

        // Find types in this namespace that are marked for flattening
        var typesToFlatten = ns.Types
            .Where(t => flattenedClasses.Contains(t.ClrFullName) && t.IsStatic)
            .ToList();

        if (typesToFlatten.Count == 0)
            return;

        sb.AppendLine();
        sb.AppendLine("// Flattened exports from static classes");

        // Create resolver for type references
        var resolver = new TypeNameResolver(ctx, plan.Graph, importPlan: plan.Imports, currentNamespace: ns.Name, facadeMode: false);

        foreach (var type in typesToFlatten)
        {
            sb.AppendLine($"// From {type.ClrFullName}");

            // Get static methods (excluding omitted ones)
            var staticMethods = type.Members.Methods
                .Where(m => m.IsStatic && m.EmitScope != Model.Symbols.MemberSymbols.EmitScope.Omitted)
                .OrderBy(m => m.ClrName)
                .ThenBy(m => m.Parameters.Length)
                .ToList();

            foreach (var method in staticMethods)
            {
                // Get the TS name for this method
                var scope = Renaming.ScopeFactory.ClassSurface(type, isStatic: true);
                var methodName = ctx.Renamer.GetFinalMemberName(method.StableId, scope);

                // Print the method signature (without static/abstract modifiers)
                var signature = Printers.MethodPrinter.PrintSignatureOnly(method, type, methodName, resolver, ctx);

                // Emit as exported function declaration
                sb.AppendLine($"export declare function {signature};");
            }
        }
    }

    /// <summary>
    /// FACADE CONSTRAINTS: Generates generic type parameters WITH constraints for facade type aliases.
    /// Mirrors source type's generic parameter constraints to maintain type safety across facade boundary.
    ///
    /// Examples:
    ///   No constraints: "<T>" or "<T1, T2>"
    ///   With constraints: "<T extends IEquatable_1<T>>"
    ///   Multiple constraints: "<T extends IComparable_1<T> & IEquatable_1<T>>"
    ///   Mixed: "<T, U extends IComparer_1<T>>"
    ///
    /// CLR type names are automatically emitted by TypeRefPrinter for primitive type arguments in constraints.
    /// </summary>
    private static string GenerateTypeParametersWithConstraints(
        Model.Symbols.TypeSymbol sourceType,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        var gps = sourceType.GenericParameters;
        if (gps.Length == 0)
            return string.Empty;

        var parts = new List<string>(gps.Length);

        foreach (var gp in gps)
        {
            // Collect type constraints (interfaces/classes)
            // Skip C# special constraints (struct, class, new()) as TypeScript can't express them
            var typeConstraints = gp.Constraints
                .Where(c => c is not null && !IsSpecialConstraint(c))
                .ToList();

            if (typeConstraints.Count == 0)
            {
                // No constraints: just the parameter name
                parts.Add(gp.Name);
            }
            else
            {
                // Print each constraint using TypeRefPrinter (handles imports, qualification, etc.)
                // PRIMITIVE CONSTRAINT RELAXATION: Widen value semantics constraints
                var constraintStrings = typeConstraints
                    .Select(c =>
                    {
                        var printed = Printers.TypeRefPrinter.Print(c, resolver, ctx);
                        // Relax IEquatable_1<T>, IComparable_1<T>, IComparable to admit primitives
                        if (AliasEmit.IsValueSemanticsConstraint(c, gp.Name))
                        {
                            return AliasEmit.RelaxConstraintForPrimitives(printed, gp.Name);
                        }
                        return printed;
                    })
                    .ToArray();

                // Join multiple constraints with & (intersection type)
                var constraintList = string.Join(" & ", constraintStrings);
                parts.Add($"{gp.Name} extends {constraintList}");
            }
        }

        return $"<{string.Join(", ", parts)}>";
    }

    /// <summary>
    /// Check if a constraint is a C# special constraint (struct, class, new()).
    /// These don't translate to TypeScript and should be filtered out.
    ///
    /// In current model, special constraints are NOT represented as TypeReferences in Constraints array,
    /// so this is a defensive check that always returns false.
    /// </summary>
    private static bool IsSpecialConstraint(Model.Types.TypeReference constraint)
    {
        // Special constraints (struct, class, new()) are not in GenericParameter.Constraints
        // They're represented by separate flags in the model
        // This method is here for future-proofing in case the model changes
        return false;
    }

    /// <summary>
    /// Generates simple type argument list for RHS of facade alias (no constraints).
    /// Uses actual generic parameter names from source type for consistency.
    /// Examples: "<T>", "<TKey, TValue>", "<T1, T2, T3>"
    /// </summary>
    private static string GenerateTypeArguments(Model.Symbols.TypeSymbol sourceType)
    {
        var gps = sourceType.GenericParameters;
        if (gps.Length == 0)
            return string.Empty;

        var names = gps.Select(gp => gp.Name);
        return $"<{string.Join(", ", names)}>";
    }

    /// <summary>
    /// Get the stem name by stripping generic arity suffix (_1, _2, ...).
    /// </summary>
    private static string GetStem(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return name;

        var lastUnderscore = name.LastIndexOf('_');
        if (lastUnderscore >= 0 && lastUnderscore < name.Length - 1)
        {
            var suffix = name.Substring(lastUnderscore + 1);
            if (int.TryParse(suffix, out _))
            {
                return name.Substring(0, lastUnderscore);
            }
        }

        return name;
    }

    /// <summary>
    /// UNIFIED FACADE EXPORT HELPER
    ///
    /// Emits facade exports for a type. For classes/structs, emits BOTH value AND type exports
    /// to ensure users can use them both as constructors (new List()) and as types (const x: List<T>).
    ///
    /// FACADE EXPORT STRATEGY:
    /// Types that need VALUE + TYPE exports (for construction AND type annotations):
    ///   - Class: new List<T>() + const x: List<T> - BOTH value and type needed
    ///   - Struct: new Point() + const p: Point - BOTH value and type needed
    ///
    /// Types that need VALUE-ONLY exports:
    ///   - StaticNamespace: Console.writeLine() - static method access only
    ///   - Enum: ConsoleColor.red - enum member access (type inferred from value)
    ///
    /// Types that need TYPE-ONLY exports (no runtime value needed):
    ///   - Interface: IEnumerable<T> - purely type-level
    ///   - Delegate: Action<T>, Func<T> - function type signatures
    /// </summary>
    private static void EmitFacadeExport(
        StringBuilder sb,
        string aliasName,
        Model.Symbols.TypeSymbol sourceType,
        string exportName,
        TypeNameResolver resolver,
        BuildContext ctx,
        string outputName)
    {
        var kind = sourceType.Kind;
        var internalPath = string.IsNullOrEmpty(outputName) ? "./_root/index.js" : $"./{outputName}/internal/index.js";

        // Class/Struct: Value re-export only
        // When internal has BOTH `const List_1` AND `type List_1<T>`,
        // re-exporting with `export { List_1 as List }` exports BOTH value AND type
        // under the new name. No separate type export needed!
        if (kind == Model.Symbols.TypeKind.Class || kind == Model.Symbols.TypeKind.Struct)
        {
            var internalValueName = GetInternalValueName(sourceType, ctx);

            // Value re-export (also re-exports the type binding):
            // export { List_1 as List } from './internal/index.js';
            // Users can then use: new List<string>() AND const x: List<string>
            sb.Append("export { ");
            sb.Append(internalValueName);
            sb.Append(" as ");
            sb.Append(aliasName);
            sb.AppendLine($" }} from '{internalPath}';");
        }
        // StaticNamespace/Enum: Value-only export (no type alias needed)
        else if (kind == Model.Symbols.TypeKind.StaticNamespace || kind == Model.Symbols.TypeKind.Enum)
        {
            var internalValueName = GetInternalValueName(sourceType, ctx);

            // Value re-export: export { Console$instance as Console } from './internal/index.js';
            sb.Append("export { ");
            sb.Append(internalValueName);
            sb.Append(" as ");
            sb.Append(aliasName);
            sb.AppendLine($" }} from '{internalPath}';");
        }
        // Interface/Delegate: Type-only export (no runtime value)
        else
        {
            // Type alias: export type IEnumerable_1<T> = Internal.IEnumerable_1<T>;
            // Uses facadeMode=true to prefix constraints with "Internal." so they reference
            // the internal module's types (which have full constraints).
            var rhsBase = $"Internal.{exportName}";
            AliasEmit.EmitGenericAlias(
                sb,
                aliasName: aliasName,
                sourceType: sourceType,
                rhsExpression: rhsBase,
                resolver,
                ctx,
                withConstraints: true,
                facadeMode: true);
        }
    }

    /// <summary>
    /// Determines if a type kind needs a VALUE export (vs type-only export) in the facade.
    ///
    /// Value exports are needed for types with runtime presence:
    ///   - StaticNamespace: Static method access (Console.writeLine())
    ///   - Class: Construction and static/instance access (new List(), Exception.message)
    ///   - Struct: Construction and static access (new Point(), DateTime.now)
    ///   - Enum: Enum member access (ConsoleColor.red)
    ///
    /// Type-only exports are sufficient for purely type-level entities:
    ///   - Interface: No runtime value (IEnumerable<T>)
    ///   - Delegate: Function type signature (Action<T>, Func<T>)
    /// </summary>
    private static bool NeedsValueExport(Model.Symbols.TypeKind kind)
    {
        return kind switch
        {
            Model.Symbols.TypeKind.StaticNamespace => true,  // Static method access
            Model.Symbols.TypeKind.Class => true,            // Construction + static/instance access
            Model.Symbols.TypeKind.Struct => true,           // Construction + static access
            Model.Symbols.TypeKind.Enum => true,             // Enum member access
            Model.Symbols.TypeKind.Interface => false,       // Type-only (no runtime value)
            Model.Symbols.TypeKind.Delegate => false,        // Type-only (function signature)
            _ => false                                        // Unknown: default to type-only (safe)
        };
    }

    /// <summary>
    /// Gets the internal module's exported value name for a type.
    ///
    /// Different type kinds have different internal naming patterns:
    ///   - Classes/Structs: Use final name (List_1 - the const export)
    ///   - StaticNamespace: Use $instance suffix (Console$instance - abstract class)
    ///   - Enums: Use final name directly (ConsoleColor - no $instance)
    ///
    /// STATIC-SIDE FIX: Classes and structs now emit interface + const pattern,
    /// so the value export is the final type name (the const), not the $instance suffix.
    /// </summary>
    private static string GetInternalValueName(Model.Symbols.TypeSymbol type, BuildContext ctx)
    {
        // Enums are exported directly by their final name (no $instance suffix)
        if (type.Kind == Model.Symbols.TypeKind.Enum)
        {
            return ctx.Renamer.GetFinalTypeName(type);
        }

        // STATIC-SIDE FIX: Classes and Structs now use const export with final name
        // The interface is $instance, but the value export (with new()) is the final name
        if (type.Kind == Model.Symbols.TypeKind.Class || type.Kind == Model.Symbols.TypeKind.Struct)
        {
            return ctx.Renamer.GetFinalTypeName(type);
        }

        // StaticNamespace uses $instance suffix (abstract class pattern unchanged)
        return ctx.Renamer.GetInstanceTypeName(type);
    }

    /// <summary>
    /// Emits type-only re-exports for primitive $instance interfaces.
    /// These are needed by @tsonic/globals to extend global String, Number, Boolean interfaces
    /// with BCL methods (e.g., `interface String extends String$instance {}`).
    ///
    /// Exports the $instance interface for each primitive type defined in PrimitiveLift.Rules.
    /// </summary>
    private static void EmitPrimitiveInstanceExports(StringBuilder sb, List<Plan.ExportStatement> exports)
    {
        // Get the CLR simple names of primitives that exist in exports
        var exportedTypes = new HashSet<string>(exports.Select(e => e.SourceType.ClrName), StringComparer.Ordinal);

        sb.AppendLine();
        sb.AppendLine("// Primitive $instance interfaces for global type augmentation (@tsonic/globals)");

        foreach (var rule in PrimitiveLift.Rules)
        {
            // Only export $instance for primitives that are actually in this namespace's exports
            if (exportedTypes.Contains(rule.ClrSimpleName))
            {
                // export type { String$instance } from './System/internal/index.js';
                sb.AppendLine($"export type {{ {rule.ClrSimpleName}$instance }} from './System/internal/index.js';");
            }
        }
    }
}
