using System.Collections.Immutable;
using System.Text;
using tsbindgen.Emit.Printers;
using tsbindgen.Model;
using tsbindgen.Model.Symbols;
using tsbindgen.Model.Symbols.MemberSymbols;
using tsbindgen.Model.Types;
using tsbindgen.Plan;
using tsbindgen.Renaming;

namespace tsbindgen.Emit;

/// <summary>
/// Emits internal/index.d.ts files for each namespace.
/// Uses EmitOrder to generate declarations in deterministic order.
/// Orchestrates ClassPrinter, MethodPrinter, TypeRefPrinter.
/// </summary>
public static class InternalIndexEmitter
{
    /// <summary>
    /// Determines if a type should be emitted to .d.ts files.
    /// Only public types are emitted (EmitScope is for members, not types).
    /// </summary>
    public static bool ShouldEmit(TypeSymbol type)
    {
        return type.Accessibility == Accessibility.Public;
    }

    public static void Emit(BuildContext ctx, EmissionPlan plan, string outputDirectory)
    {
        ctx.Log("InternalIndexEmitter", "Generating TypeScript declarations...");

        var emittedCount = 0;

        // Process each namespace in order
        foreach (var nsOrder in plan.EmissionOrder.Namespaces)
        {
            var ns = nsOrder.Namespace;
            ctx.Log("InternalIndexEmitter", $"  Emitting namespace: {ns.Name}");

            // Generate .d.ts content
            var content = GenerateNamespaceDeclaration(ctx, plan, nsOrder);

            // Write to file: output/Namespace.Name/internal/index.d.ts (or _root for empty namespace)
            var namespacePath = Path.Combine(outputDirectory, ns.Name);
            // Use _root for empty namespace to avoid case-sensitivity collision with "Internal" namespace
            var subdirName = ns.IsRoot ? "_root" : "internal";
            var internalPath = Path.Combine(namespacePath, subdirName);
            Directory.CreateDirectory(internalPath);

            var outputFile = Path.Combine(internalPath, "index.d.ts");
            File.WriteAllText(outputFile, content);

            ctx.Log("InternalIndexEmitter", $"    → {outputFile}");
            emittedCount++;
        }

        ctx.Log("InternalIndexEmitter", $"Generated {emittedCount} declaration files");
    }

    private static string GenerateNamespaceDeclaration(BuildContext ctx, EmissionPlan plan, NamespaceEmitOrder nsOrder)
    {
        // Extract plan components
        var graph = plan.Graph;
        var importPlan = plan.Imports;
        var staticFlattening = plan.StaticFlattening;
        var staticConflicts = plan.StaticConflicts;
        var overrideConflicts = plan.OverrideConflicts;
        var propertyOverrides = plan.PropertyOverrides;
        var honestEmission = plan.HonestEmission;
        var safeToExtend = plan.SafeToExtend;

        // Create TypeNameResolver - single source of truth for type names
        // TS2693 FIX: Pass ImportPlan and current namespace for qualified name resolution
        var resolver = new TypeNameResolver(ctx, graph, importPlan, nsOrder.Namespace.Name);

        // V2 FIX: Create BindingsProvider for inherited member exposure (TS2416 fix)
        var bindingsProvider = new BindingsProvider(ctx, graph);

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Architecture");
        sb.AppendLine($"// Namespace: {nsOrder.Namespace.Name}");
        sb.AppendLine($"// Assembly: {string.Join(", ", nsOrder.Namespace.ContributingAssemblies.OrderBy(a => a))}");
        sb.AppendLine();

        // Branded primitive types are sourced from @tsonic/types
        EmitBrandedPrimitiveImports(sb);

        // Check if namespace uses unsafe markers (pointers/byrefs) and emit support import if needed
        var needsSupportTypes = NamespaceUsesSupportTypes(nsOrder.Namespace);
        if (needsSupportTypes)
        {
            sb.AppendLine("// Import support types from @tsonic/types");
            sb.AppendLine("import type { ptr, ref } from \"@tsonic/types\";");
            sb.AppendLine();
        }

        // Emit import statements for cross-namespace type references
        var imports = importPlan.GetImportsFor(nsOrder.Namespace.Name);

        // CLROf utility requires System_Internal namespace import
        // Check if we need to add it (for non-System namespaces)
        var systemImport = imports.FirstOrDefault(i => i.TargetNamespace == "System");
        var needsSystemInternalForCLROf = nsOrder.Namespace.Name != "System"
            && (systemImport == null || systemImport.TypeImports.All(ti => !ti.IsValueImport));

        if (imports.Count > 0 || needsSystemInternalForCLROf)
        {
            sb.AppendLine("// Import types from other namespaces");

            // Add System_Internal namespace import for CLROf if not already present
            if (needsSystemInternalForCLROf)
            {
                var systemPath = Plan.PathPlanner.GetSpecifier(nsOrder.Namespace.Name, "System");
                sb.AppendLine($"import * as System_Internal from \"{systemPath}\";");
            }

            // Sort imports by module specifier for stable output
            foreach (var import in imports.OrderBy(i => i.ImportPath))
            {
                // TS2693 FIX: Use namespace imports for value imports to make them accessible inside namespace blocks
                // TypeScript limitation: named value imports aren't accessible inside namespace declarations
                var valueImports = import.TypeImports.Where(ti => ti.IsValueImport).ToList();
                var typeOnlyImports = import.TypeImports.Where(ti => !ti.IsValueImport).ToList();

                // Emit BOTH named AND namespace imports for reflection types
                // - Named imports work outside namespace blocks (for simple names in return types)
                // - Namespace imports work inside namespace blocks (for base classes)
                // We need both to support reflection types used in both positions
                var reflectionValueImports = valueImports
                    .Where(ti => ReflectionTypes.IsCommonReflectionTypeName(import.TargetNamespace, ti.TypeName))
                    .ToList();

                // Emit named value imports for reflection types (accessible outside namespace)
                if (reflectionValueImports.Count > 0)
                {
                    var reflectionList = string.Join(", ", reflectionValueImports
                        .OrderBy(ti => ti.TypeName)
                        .Select(ti => ti.Alias != null ? $"{ti.TypeName} as {ti.Alias}" : ti.TypeName));

                    sb.AppendLine($"import {{ {reflectionList} }} from \"{import.ImportPath}\";");
                }

                // CRITICAL: Always emit namespace import for ALL value imports (not just non-reflection)
                // Namespace imports are required for accessing types inside namespace blocks
                if (valueImports.Count > 0)
                {
                    sb.AppendLine($"import * as {import.NamespaceAlias} from \"{import.ImportPath}\";");
                }

                // TS2416 FIX: Emit type-only imports for ALL types (not just non-value imports)
                // EXCEPT reflection types that were already imported as regular imports above
                // Types used in both value positions (extends) and type positions (return types) need BOTH:
                // - namespace import for extends: "import * as Foo_Internal"
                // - type import for return types: "import type { FooType }"
                // Example: ClaimsIdentity used in "extends ClaimsIdentity$instance" AND "clone(): ClaimsIdentity"
                var reflectionValueImportNames = new HashSet<string>(reflectionValueImports.Select(ti => ti.TypeName));
                var typesNotAlreadyImported = import.TypeImports
                    .Where(ti => !reflectionValueImportNames.Contains(ti.TypeName))
                    .ToList();

                if (typesNotAlreadyImported.Count > 0)
                {
                    var allTypeImportsList = string.Join(", ", typesNotAlreadyImported
                        .OrderBy(ti => ti.TypeName)
                        .Select(ti => ti.Alias != null ? $"{ti.TypeName} as {ti.Alias}" : ti.TypeName));

                    sb.AppendLine($"import type {{ {allTypeImportsList} }} from \"{import.ImportPath}\";");
                }
            }

            sb.AppendLine(); // Blank line after imports
        }

        // Emit CLROf utility after cross-namespace imports (so System_Internal is available)
        EmitCLROfUtility(sb, nsOrder.Namespace.Name);

        var indent = string.Empty;

        // Track types that lost generics during emission (used for diagnostics/aliases)
        var typesWithoutGenerics = new HashSet<string>();

        // Emit types in order (PUBLIC ONLY - internal types should not appear in .d.ts)
        foreach (var typeOrder in nsOrder.OrderedTypes.Where(to => ShouldEmit(to.Type)))
        {
            // PRIMITIVE ALIAS FIX: CLR primitive types must be simple aliases to branded TS primitives
            // This enables LINQ assignability: List<int> is assignable to IEnumerable<Int32> when Int32 = int
            // Example: export type Int32 = int; (not Int32$instance & __Int32$views)
            var tsPrimitiveName = PrimitiveLift.GetTsPrimitiveName(typeOrder.Type.ClrFullName);
            if (tsPrimitiveName != null)
            {
                var primitiveAlias = $"export type {typeOrder.Type.TsEmitName} = {tsPrimitiveName};";
                sb.Append(indent);
                sb.AppendLine(primitiveAlias);
                sb.AppendLine();
                continue; // Skip normal emission for primitives
            }

            // Check if type has explicit views (attached by ViewPlanner)
            var views = typeOrder.Type.ExplicitViews;
            var hasViews = views.Length > 0 && (typeOrder.Type.Kind == Model.Symbols.TypeKind.Class || typeOrder.Type.Kind == Model.Symbols.TypeKind.Struct || typeOrder.Type.Kind == Model.Symbols.TypeKind.Delegate);

            if (hasViews)
            {
                // Emit class with $instance suffix - PUBLIC TYPES GET export KEYWORD
                var instanceClass = ClassPrinter.PrintInstance(typeOrder.Type, resolver, ctx, graph, bindingsProvider, staticFlattening, staticConflicts, overrideConflicts, propertyOverrides, honestEmission);
                var indentedInstance = Indent(instanceClass, indent);

                // PUBLIC TYPES: Always export (both root and namespaces)
                sb.Append("export ");
                sb.AppendLine(indentedInstance);
                sb.AppendLine();

                // STATIC-SIDE FIX: Emit value export for constructors and static members
                // This is a const declaration that replaces the static side of the class
                var valueExport = ClassPrinter.PrintValueExport(typeOrder.Type, resolver, ctx, graph, staticConflicts);
                if (!string.IsNullOrEmpty(valueExport))
                {
                    var indentedValue = Indent(valueExport, indent);
                    sb.AppendLine(indentedValue);
                    sb.AppendLine();
                }

                // Emit companion views interface - PUBLIC TYPES GET export KEYWORD
                var viewsInterface = EmitCompanionViewsInterface(typeOrder.Type, views, resolver, ctx);
                var indentedViews = Indent(viewsInterface, indent);

                // PUBLIC TYPES: Always export (both root and namespaces)
                sb.Append("export ");
                sb.AppendLine(indentedViews);
                sb.AppendLine();

                // Emit intersection type alias (already has export in the returned string)
                var typeAlias = EmitIntersectionTypeAlias(typeOrder.Type, resolver, ctx);
                var indentedAlias = Indent(typeAlias, indent);

                // LINQ ASSIGNABILITY: Emit merged interface extends for type-level assignability
                // This allows List_1$instance<T> to be assignable to IEnumerable_1$instance<T>
                // without requiring "implements" (which would trigger TS2420 compliance)
                // Uses SafeToExtend analysis to only extend interfaces that won't cause TS2430/TS2320
                var mergedInterface = EmitMergedInterfaceExtends(typeOrder.Type, resolver, ctx, graph, safeToExtend);
                if (!string.IsNullOrEmpty(mergedInterface))
                {
                    var indentedMerged = Indent(mergedInterface, indent);
                    sb.Append("export ");
                    sb.AppendLine(indentedMerged);
                    sb.AppendLine();
                }

                // Type alias already includes "export" keyword
                sb.AppendLine(indentedAlias);
                sb.AppendLine();

            }
            else
            {
                // Normal emission (no views) - PUBLIC TYPES GET export KEYWORD
                var typeDecl = ClassPrinter.Print(typeOrder.Type, resolver, ctx, graph, typesWithoutGenerics, bindingsProvider, staticFlattening, staticConflicts, overrideConflicts, propertyOverrides, honestEmission);
                var indented = Indent(typeDecl, indent);

                // PUBLIC TYPES: Always export (both root and namespaces)
                sb.Append("export ");
                sb.AppendLine(indented);
                sb.AppendLine();

                // STATIC-SIDE FIX: Emit value export for constructors and static members (classes/structs only)
                var valueExport = ClassPrinter.PrintValueExport(typeOrder.Type, resolver, ctx, graph, staticConflicts);
                if (!string.IsNullOrEmpty(valueExport))
                {
                    var indentedValue = Indent(valueExport, indent);
                    sb.AppendLine(indentedValue);
                    sb.AppendLine();
                }

                // C.5.2 FIX: For interfaces without views, emit alias pointing to $instance
                // This allows cross-namespace references like System.Collections.IEnumerable to work
                // Example: export type IEnumerable = IEnumerable$instance;
                // Only do this for interfaces - not for static classes, delegates, or enums
                var finalName = ctx.Renamer.GetFinalTypeName(typeOrder.Type);
                var instanceName = ctx.Renamer.GetInstanceTypeName(typeOrder.Type);
                var isInterface = typeOrder.Type.Kind == Model.Symbols.TypeKind.Interface;
                var isStaticClass = typesWithoutGenerics != null && typesWithoutGenerics.Contains(finalName);

                // LINQ ASSIGNABILITY: Emit merged interface extends for interfaces too
                // This ensures IEnumerator_1$instance<T> extends IDisposable$instance, etc.
                // Uses SafeToExtend analysis to only extend interfaces that won't cause TS2430/TS2320
                if (isInterface)
                {
                    var mergedInterface = EmitMergedInterfaceExtends(typeOrder.Type, resolver, ctx, graph, safeToExtend);
                    if (!string.IsNullOrEmpty(mergedInterface))
                    {
                        var indentedMerged = Indent(mergedInterface, indent);
                        sb.Append("export ");
                        sb.AppendLine(indentedMerged);
                        sb.AppendLine();
                    }
                }

                // Only emit alias for interfaces that aren't static classes
                if (isInterface && finalName != instanceName && !isStaticClass)
                {
                    sb.Append(indent);
                    sb.Append("export type ");
                    sb.Append(finalName);

                    // Add type parameters if needed
                    var typeArgs = AliasEmit.GenerateTypeArguments(typeOrder.Type);
                    var typeParams = AliasEmit.GenerateTypeParametersWithConstraints(typeOrder.Type, resolver, ctx);
                    sb.Append(typeParams);

                    sb.Append(" = ");
                    sb.Append(instanceName);
                    sb.Append(typeArgs);
                    sb.AppendLine(";");
                    sb.AppendLine();
                }

                // ESM FLATTENING: Provide module-level aliases for class/struct types without views
                // With namespace blocks removed, the stem name (GetFinalTypeName) must be exported
                // so facade/type-position references resolve. Skip static classes that lost generics
                // to avoid TS2315 (non-generic emitted type referenced as generic).
                //
                // NOTE: We use type aliases here (not value re-exports) because type aliases are
                // HOISTED in TypeScript, enabling forward references within the file. Value exports
                // for static access are added in the facade layer (see FacadeEmitter.cs).
                var isClassLike = typeOrder.Type.Kind is Model.Symbols.TypeKind.Class or Model.Symbols.TypeKind.Struct or Model.Symbols.TypeKind.StaticNamespace;
                var needsAlias = isClassLike && finalName != instanceName && !isStaticClass;
                if (needsAlias)
                {
                    AliasEmit.EmitGenericAlias(
                        sb,
                        aliasName: finalName,
                        sourceType: typeOrder.Type,
                        rhsExpression: instanceName,
                        resolver,
                        ctx,
                        withConstraints: true);
                    sb.AppendLine();
                }

            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// INTERNAL CONSTRAINTS: Generates generic type parameters WITH constraints for internal convenience exports.
    /// Mirrors the facade constraint propagation logic to fix TS2344 errors in module-level type aliases.
    /// </summary>
    private static string GenerateTypeParametersWithConstraints(
        Model.Symbols.TypeSymbol sourceType,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        var gps = sourceType.GenericParameters;
        if (gps.Length == 0)
            return string.Empty;

        var parts = new List<string>(gps.Length);

        foreach (var gp in gps)
        {
            // Collect type constraints (interfaces/classes)
            // Skip C# special constraints (struct, class, new()) as TypeScript can't express them
            var typeConstraints = gp.Constraints
                .Where(c => c is not null && !IsSpecialConstraint(c))
                .ToList();

            if (typeConstraints.Count == 0)
            {
                // No constraints: just the parameter name
                parts.Add(gp.Name);
            }
            else
            {
                // Print each constraint using TypeRefPrinter (handles CLROf, imports, etc.)
                var constraintStrings = typeConstraints
                    .Select(c => Printers.TypeRefPrinter.Print(c, resolver, ctx))
                    .ToArray();

                // Join multiple constraints with & (intersection type)
                var constraintList = string.Join(" & ", constraintStrings);
                parts.Add($"{gp.Name} extends {constraintList}");
            }
        }

        return $"<{string.Join(", ", parts)}>";
    }

    /// <summary>
    /// Check if a constraint is a C# special constraint (struct, class, new()).
    /// These don't translate to TypeScript and should be filtered out.
    /// </summary>
    private static bool IsSpecialConstraint(Model.Types.TypeReference constraint)
    {
        // Special constraints (struct, class, new()) are not in GenericParameter.Constraints
        // They're represented by separate flags in the model
        // This method is here for future-proofing in case the model changes
        return false;
    }

    private static void EmitBrandedPrimitiveImports(StringBuilder sb)
    {
        sb.AppendLine("// Branded primitive types are sourced from @tsonic/types");
        sb.AppendLine("import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';");
        sb.AppendLine();
    }

    private static void EmitCLROfUtility(StringBuilder sb, string currentNamespace)
    {
        // CLROf<T> - Primitive Lifting Utility
        // CRITICAL: Uses PrimitiveLift.Rules as single source of truth (PG_GENERIC_PRIM_LIFT_001)
        sb.AppendLine("// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints");
        sb.AppendLine("// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints");
        sb.AppendLine("// Value positions (parameters, return types) use lowercase primitives for ergonomics");
        sb.AppendLine("export type CLROf<T> =");

        // Generate conditional type branches from PrimitiveLift.Rules
        // For System namespace, use direct type names (no prefix)
        // For other namespaces, use System_Internal.TypeName (namespace-qualified)
        var isSystemNamespace = currentNamespace == "System";
        foreach (var (tsName, _, clrSimpleName) in PrimitiveLift.Rules)
        {
            var typeRef = isSystemNamespace ? clrSimpleName : $"System_Internal.{clrSimpleName}";
            sb.AppendLine($"    T extends {tsName} ? {typeRef} :");
        }

        sb.AppendLine("    T; // Identity fallback for non-primitive types");
        sb.AppendLine();
    }

    /// <summary>
    /// LINQ ASSIGNABILITY: Emit a merged interface declaration that extends safe interfaces.
    /// This uses TypeScript declaration merging to make T$instance assignable to interface types
    /// without requiring "implements" (which would trigger TS2420 member compliance checks).
    ///
    /// Example output:
    ///   export interface List_1$instance&lt;T&gt; extends IEnumerable_1$instance&lt;T&gt;, ICollection_1$instance&lt;T&gt; {}
    ///
    /// This enables:
    ///   declare function takeEnum&lt;T&gt;(x: IEnumerable_1&lt;T&gt;): void;
    ///   const list = new List_1&lt;int&gt;();
    ///   takeEnum(list);  // ✓ type-checks without .As_IEnumerable_1()
    ///
    /// Uses SafeToExtend analysis to only extend interfaces that won't cause TS2430/TS2320.
    /// Interfaces that would create member signature conflicts are accessible via views instead.
    /// </summary>
    private static string? EmitMergedInterfaceExtends(
        TypeSymbol type,
        TypeNameResolver resolver,
        BuildContext ctx,
        SymbolGraph graph,
        Dictionary<string, Plan.SafeToExtendAnalyzer.SafeToExtendResult> safeToExtend)
    {
        // Get assignable interfaces from SafeToExtend analysis
        var typeStableId = type.StableId.ToString();
        if (!safeToExtend.TryGetValue(typeStableId, out var safeToExtendResult))
        {
            // No analysis for this type - no extends to emit
            return null;
        }

        var interfaces = safeToExtendResult.AssignableInterfaces;
        if (interfaces.Count == 0)
            return null;

        var sb = new StringBuilder();

        // Get the instance type name
        var instanceName = ctx.Renamer.GetInstanceTypeName(type);

        sb.Append($"interface {instanceName}");

        // Add generic parameters with constraints
        if (type.GenericParameters.Length > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", type.GenericParameters.Select(gp =>
                PrintGenericParameterWithConstraints(gp, resolver, ctx))));
            sb.Append('>');
        }

        sb.Append(" extends ");

        // Interfaces are already sorted by CLR full name from SafeToExtend analyzer (deterministic)
        // Emit extends list with correct $instance suffix and type arguments
        var extendsList = new List<string>();
        foreach (var iface in interfaces)
        {
            var interfaceName = PrintInterfaceForExtends(iface, type.Namespace, resolver, ctx, graph);
            extendsList.Add(interfaceName);
        }

        sb.Append(string.Join(", ", extendsList));
        sb.Append(" {}");

        return sb.ToString();
    }

    /// <summary>
    /// Check if an interface is in the symbol graph (exists in emitted output).
    /// </summary>
    private static bool IsInterfaceInGraph(TypeReference ifaceRef, SymbolGraph graph)
    {
        if (ifaceRef is not NamedTypeReference named)
            return true; // Non-named types (generic parameters, etc.) are always allowed

        // TypeIndex uses ClrFullName as key
        return graph.TypeIndex.TryGetValue(named.FullName, out _);
    }

    /// <summary>
    /// Check if an interface is a non-generic System.Collections interface that conflicts
    /// with its generic counterpart. These interfaces have methods like GetEnumerator()
    /// that return different types (IEnumerator vs IEnumerator&lt;T&gt;), causing TS2430 errors
    /// when both are extended.
    ///
    /// C# handles this via explicit interface implementation, but TypeScript cannot express
    /// this pattern, so we filter them out from the merged extends.
    /// </summary>
    private static bool IsConflictingNonGenericInterface(TypeReference ifaceRef)
    {
        if (ifaceRef is not NamedTypeReference named)
            return false;

        var fullName = named.FullName;

        // List of non-generic System.Collections interfaces that conflict with generic ones
        return fullName switch
        {
            "System.Collections.IEnumerable" => true,
            "System.Collections.IEnumerator" => true,
            "System.Collections.ICollection" => true,
            "System.Collections.IList" => true,
            "System.Collections.IDictionary" => true,
            "System.Collections.IDictionaryEnumerator" => true,
            "System.Collections.IComparer" => true,
            "System.Collections.IEqualityComparer" => true,
            "System.Collections.IStructuralComparable" => true,
            "System.Collections.IStructuralEquatable" => true,
            _ => false
        };
    }

    /// <summary>
    /// Get the CLR full name from an interface reference for sorting.
    /// </summary>
    private static string GetInterfaceFullName(TypeReference ifaceRef)
    {
        return ifaceRef switch
        {
            NamedTypeReference named => named.FullName,
            NestedTypeReference nested => nested.FullReference.FullName,
            _ => ifaceRef.ToString() ?? ""
        };
    }

    /// <summary>
    /// Print an interface reference for use in the extends clause of merged interface.
    /// Ensures correct $instance suffix and cross-namespace qualification.
    /// </summary>
    private static string PrintInterfaceForExtends(
        TypeReference ifaceRef,
        string currentNamespace,
        TypeNameResolver resolver,
        BuildContext ctx,
        SymbolGraph graph)
    {
        // Print the interface using TypeRefPrinter (handles type args correctly)
        var baseName = Printers.TypeRefPrinter.Print(ifaceRef, resolver, ctx,
            allowedTypeParameterNames: null, forValuePosition: true);

        // Apply $instance suffix for same-namespace interfaces that have views
        baseName = ApplyInstanceSuffixForExtends(baseName, ifaceRef, currentNamespace, graph, ctx);

        // If cross-namespace, ensure it's qualified
        if (ifaceRef is NamedTypeReference named)
        {
            var interfaceNamespace = ExtractNamespace(named.FullName);

            if (!string.IsNullOrEmpty(interfaceNamespace) &&
                interfaceNamespace != currentNamespace &&
                !baseName.Contains('.'))
            {
                var namespaceAlias = interfaceNamespace.Replace('.', '_') + "_Internal";
                return $"{namespaceAlias}.{baseName}";
            }
        }

        return baseName;
    }

    /// <summary>
    /// Apply $instance suffix to interface names for extends clause.
    /// Interfaces don't have views, so we use $instance suffix to match the emitted type name.
    /// </summary>
    private static string ApplyInstanceSuffixForExtends(
        string typeName,
        TypeReference ifaceRef,
        string currentNamespace,
        SymbolGraph graph,
        BuildContext ctx)
    {
        if (ifaceRef is not NamedTypeReference named)
            return typeName;

        // Find the interface in the graph
        if (!graph.TypeIndex.TryGetValue(named.FullName, out var ifaceSymbol))
            return typeName;

        // Check if it's an interface and in the same namespace
        if (ifaceSymbol.Kind != TypeKind.Interface)
            return typeName;

        var interfaceNamespace = ExtractNamespace(named.FullName);
        if (interfaceNamespace != currentNamespace)
            return typeName; // Cross-namespace already handled by qualification

        // Check if name already has $instance suffix (avoid double-suffix)
        var genericStart = typeName.IndexOf('<');
        var basePart = genericStart >= 0 ? typeName.Substring(0, genericStart) : typeName;

        if (basePart.EndsWith("$instance"))
            return typeName; // Already has suffix

        // For same-namespace interfaces, add $instance suffix
        if (genericStart >= 0)
        {
            var typeArgsPart = typeName.Substring(genericStart);
            return $"{basePart}$instance{typeArgsPart}";
        }
        else
        {
            return $"{typeName}$instance";
        }
    }

    /// <summary>
    /// Extract namespace from CLR full name.
    /// </summary>
    private static string ExtractNamespace(string fullName)
    {
        // Remove assembly qualification if present
        var commaIndex = fullName.IndexOf(',');
        if (commaIndex >= 0)
            fullName = fullName.Substring(0, commaIndex).Trim();

        // Extract namespace (everything before the last dot)
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(0, lastDot) : "";
    }

    private static string EmitCompanionViewsInterface(TypeSymbol type, ImmutableArray<Shape.ViewPlanner.ExplicitView> views, TypeNameResolver resolver, BuildContext ctx)
    {
        var sb = new StringBuilder();

        // Get final type name
        var finalName = ctx.Renamer.GetFinalTypeName(type);

        // Companion interface: __TypeName$views<...>
        sb.Append($"interface __{finalName}$views");

        // TS2344 FIX: Generic parameters WITH CONSTRAINTS
        // View interface must have same constraints as the type alias
        // Otherwise: type Foo<T extends IBar<T>> = Foo$instance<T> & __Foo$views<T>
        // fails because __Foo$views<T> doesn't have the constraint
        if (type.GenericParameters.Length > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", type.GenericParameters.Select(gp =>
                PrintGenericParameterWithConstraints(gp, resolver, ctx))));
            sb.Append('>');
        }

        sb.AppendLine(" {");

        // Emit view accessor methods (not properties - methods are the stable API)
        foreach (var view in views)
        {
            sb.Append("    ");
            sb.Append(view.ViewPropertyName);
            sb.Append("(): ");

            // FIX D: Match view's interface reference to type's actual interface implementation
            // to get correct type arguments (fixes generic "T" leaks in view interfaces)
            var matchedInterface = FindMatchingInterface(type, view.InterfaceReference);
            var interfaceToEmit = matchedInterface ?? view.InterfaceReference;

            // TS2304 FIX: View interfaces need namespace qualification
            // Some view interfaces (like IEnumerable) are transitively implemented and not in
            // ValueImportQualifiedNames, so we need to manually qualify cross-namespace types
            // NOTE: Always emit actual CLR type arguments (e.g., INumberBase_1<int> for Int32).
            // Never substitute 'any' - that breaks type safety. The real self-type satisfies
            // recursive constraints because Int32 genuinely implements INumberBase_1<Int32>.
            var viewTypeName = QualifyViewInterface(interfaceToEmit, type.Namespace, resolver, ctx);
            sb.Append(viewTypeName);
            sb.AppendLine(";");
        }

        // TS2344 FIX: Add structural method bridges for numeric interface constraints
        // TypeScript uses structural typing - interfaces require PascalCase methods
        // but instance classes use camelCase. Add PascalCase methods to satisfy constraints.
        var numericInterfaces = GetNumericInterfaceSet(views);
        if (numericInterfaces != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Structural method bridges for numeric interface constraints");
            EmitNumericStructuralMethods(sb, type, numericInterfaces, resolver, ctx);
        }

        sb.Append("}");

        return sb.ToString();
    }

    /// <summary>
    /// Get the set of numeric interfaces that require structural method bridges.
    /// Returns null if no numeric interfaces are implemented.
    /// </summary>
    private static HashSet<string>? GetNumericInterfaceSet(ImmutableArray<Shape.ViewPlanner.ExplicitView> views)
    {
        HashSet<string>? interfaces = null;

        foreach (var view in views)
        {
            if (view.InterfaceReference is Model.Types.NamedTypeReference named)
            {
                var interfaceName = named.FullName;

                // Track which specific numeric interfaces are implemented
                if (interfaceName.Contains("System.Numerics.INumber`1") ||
                    interfaceName.Contains("System.Numerics.IBinaryInteger`1") ||
                    interfaceName.Contains("System.Numerics.IFloatingPoint`1") ||
                    interfaceName.Contains("System.Numerics.INumberBase`1") ||
                    interfaceName.Contains("System.Numerics.IRootFunctions`1") ||
                    interfaceName.Contains("System.Numerics.ITrigonometricFunctions`1") ||
                    interfaceName.Contains("System.IEquatable`1") ||
                    interfaceName.Contains("System.IComparable"))
                {
                    interfaces ??= new HashSet<string>();

                    // Normalize to generic base name for easier checking
                    if (interfaceName.Contains("System.Numerics.INumber`1"))
                        interfaces.Add("INumber");
                    if (interfaceName.Contains("System.Numerics.IBinaryInteger`1"))
                        interfaces.Add("IBinaryInteger");
                    if (interfaceName.Contains("System.Numerics.IFloatingPoint`1"))
                        interfaces.Add("IFloatingPoint");
                    if (interfaceName.Contains("System.Numerics.INumberBase`1"))
                        interfaces.Add("INumberBase");
                    if (interfaceName.Contains("System.Numerics.IRootFunctions`1"))
                        interfaces.Add("IRootFunctions");
                    if (interfaceName.Contains("System.Numerics.ITrigonometricFunctions`1"))
                        interfaces.Add("ITrigonometricFunctions");
                    if (interfaceName.Contains("System.IEquatable`1"))
                        interfaces.Add("IEquatable");
                    if (interfaceName.Contains("System.IComparable"))
                        interfaces.Add("IComparable");
                }
            }
        }

        return interfaces;
    }

    /// <summary>
    /// Emit structural method bridges to satisfy numeric interface constraints.
    /// These methods use PascalCase (matching C# interface definitions) while instance
    /// methods use camelCase. This satisfies TypeScript's structural type checking.
    /// Only emits methods for the specific interfaces actually implemented.
    /// </summary>
    private static void EmitNumericStructuralMethods(
        StringBuilder sb,
        TypeSymbol type,
        HashSet<string> numericInterfaces,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        // Get the actual type name with generic parameters for use in signatures
        var typeName = ctx.Renamer.GetFinalTypeName(type);
        if (type.GenericParameters.Length > 0)
        {
            typeName += $"<{string.Join(", ", type.GenericParameters.Select(gp => gp.Name))}>";
        }

        // Determine if we're in System namespace (can use simple names)
        var inSystemNamespace = type.Namespace == "System";

        // Helper to get qualified type name
        string Qualified(string simpleName)
        {
            if (inSystemNamespace)
                return simpleName;
            else
                return $"import(\"../../System/internal/index\").{simpleName}";
        }

        // IEquatable<T>.Equals
        if (numericInterfaces.Contains("IEquatable"))
        {
            sb.AppendLine($"    Equals(other: {typeName}): boolean;");
        }

        // IComparable.CompareTo
        if (numericInterfaces.Contains("IComparable"))
        {
            sb.AppendLine("    CompareTo(obj: unknown): int;");
        }

        // INumberBase<TSelf>, INumber<TSelf>, IBinaryInteger<TSelf>, IFloatingPoint<TSelf>, etc.
        // All require ToString and TryFormat
        if (numericInterfaces.Contains("INumberBase") ||
            numericInterfaces.Contains("INumber") ||
            numericInterfaces.Contains("IBinaryInteger") ||
            numericInterfaces.Contains("IFloatingPoint") ||
            numericInterfaces.Contains("IRootFunctions") ||
            numericInterfaces.Contains("ITrigonometricFunctions"))
        {
            sb.AppendLine($"    ToString(format: string, formatProvider: {Qualified("IFormatProvider")}): string;");
            // ref is from @tsonic/types, so never qualify it
            sb.AppendLine($"    TryFormat(destination: {Qualified("Span_1")}<{Qualified("CLROf")}<char>>, charsWritten: {{ value: ref<int> }}, format: {Qualified("ReadOnlySpan_1")}<{Qualified("CLROf")}<char>>, provider: {Qualified("IFormatProvider")}): boolean;");
        }

        // IBinaryInteger<TSelf> - GetByteCount, TryWriteBigEndian, WriteBigEndian
        if (numericInterfaces.Contains("IBinaryInteger"))
        {
            sb.AppendLine("    GetByteCount(): int;");
            // TryWriteBigEndian with out parameter
            sb.AppendLine($"    TryWriteBigEndian(destination: {Qualified("Span_1")}<{Qualified("CLROf")}<byte>>, bytesWritten: {{ value: ref<int> }}): boolean;");
            // WriteBigEndian overloads
            sb.AppendLine("    WriteBigEndian(destination: byte[], startIndex: int): int;");
            sb.AppendLine("    WriteBigEndian(destination: byte[]): int;");
            sb.AppendLine($"    WriteBigEndian(destination: {Qualified("Span_1")}<{Qualified("CLROf")}<byte>>): int;");
        }

        // IFloatingPoint<TSelf> - GetExponentByteCount, GetExponentShortestBitLength, TryWriteExponentBigEndian, WriteExponentBigEndian
        if (numericInterfaces.Contains("IFloatingPoint"))
        {
            sb.AppendLine("    GetExponentByteCount(): int;");
            sb.AppendLine("    GetExponentShortestBitLength(): int;");
            // TryWriteExponentBigEndian with out parameter
            sb.AppendLine($"    TryWriteExponentBigEndian(destination: {Qualified("Span_1")}<{Qualified("CLROf")}<byte>>, bytesWritten: {{ value: ref<int> }}): boolean;");
            // WriteExponentBigEndian overloads
            sb.AppendLine("    WriteExponentBigEndian(destination: byte[], startIndex: int): int;");
            sb.AppendLine("    WriteExponentBigEndian(destination: byte[]): int;");
            sb.AppendLine($"    WriteExponentBigEndian(destination: {Qualified("Span_1")}<{Qualified("CLROf")}<byte>>): int;");
        }
    }

    /// <summary>
    /// Print a generic parameter with its constraints for use in type declarations.
    /// E.g., "T extends IFoo & IBar"
    /// </summary>
    private static string PrintGenericParameterWithConstraints(
        Model.Symbols.GenericParameterSymbol gp,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        var sb = new StringBuilder();
        sb.Append(gp.Name);

        // Add constraints
        if (gp.Constraints.Length > 0)
        {
            sb.Append(" extends ");

            if (gp.Constraints.Length == 1)
            {
                sb.Append(Printers.TypeRefPrinter.Print(gp.Constraints[0], resolver, ctx));
            }
            else
            {
                // Multiple constraints: T extends IFoo & IBar
                var constraints = gp.Constraints.Select(c =>
                    Printers.TypeRefPrinter.Print(c, resolver, ctx));
                sb.Append(string.Join(" & ", constraints));
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// TS2304 FIX: Qualify view interface types with namespace alias if cross-namespace.
    /// View interfaces that are transitively implemented (not directly in implements clause)
    /// don't get added to ValueImportQualifiedNames, so we need manual qualification.
    /// </summary>
    private static string QualifyViewInterface(
        Model.Types.TypeReference interfaceRef,
        string currentNamespace,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        // Always emit actual CLR type arguments using the normal type printer.
        // For self-referential interfaces (e.g., INumberBase_1<Int32>), this emits
        // the real instantiation which satisfies the recursive constraint correctly.
        // NEVER substitute 'any' - that breaks type safety and poisons downstream inference.
        var baseName = Printers.TypeRefPrinter.Print(interfaceRef, resolver, ctx,
            forValuePosition: true);

        // If it's a NamedTypeReference, check if it's cross-namespace
        if (interfaceRef is Model.Types.NamedTypeReference named)
        {
            // Extract namespace from CLR full name
            var fullName = named.FullName;
            var commaIndex = fullName.IndexOf(',');
            if (commaIndex >= 0)
            {
                fullName = fullName.Substring(0, commaIndex).Trim();
            }

            var interfaceNamespace = fullName.Contains('.')
                ? fullName.Substring(0, fullName.LastIndexOf('.'))
                : "";

            // If cross-namespace and not already qualified (doesn't contain '.'), qualify it
            if (!string.IsNullOrEmpty(interfaceNamespace) &&
                interfaceNamespace != currentNamespace &&
                !baseName.Contains('.'))
            {
                // Flat ESM: qualify with namespace import alias only
                var namespaceAlias = interfaceNamespace.Replace('.', '_') + "_Internal";
                return $"{namespaceAlias}.{baseName}";
            }
        }

        return baseName;
    }

    /// <summary>
    /// FIX D: Find the matching interface in type.Interfaces that corresponds to the view's interface reference.
    /// Returns the matched interface with correct type arguments, or null if not found.
    /// </summary>
    private static TypeReference? FindMatchingInterface(TypeSymbol type, TypeReference viewInterfaceRef)
    {
        // Get the base name without type arguments for matching
        var viewBaseName = GetInterfaceBaseName(viewInterfaceRef);

        foreach (var implementedInterface in type.Interfaces)
        {
            var implBaseName = GetInterfaceBaseName(implementedInterface);

            // Match by base name (e.g., "IEnumerator_1" matches)
            if (viewBaseName == implBaseName)
            {
                return implementedInterface;
            }
        }

        return null;
    }

    /// <summary>
    /// Get the base name of an interface (without type arguments) for matching.
    /// Examples: "IEnumerator`1" -> "IEnumerator`1", "System.Collections.Generic.IEnumerator`1" -> "IEnumerator`1"
    /// </summary>
    private static string GetInterfaceBaseName(TypeReference typeRef)
    {
        return typeRef switch
        {
            NamedTypeReference named => named.Name,  // Just the name, e.g., "IEnumerator`1"
            NestedTypeReference nested => nested.NestedName,
            _ => typeRef.ToString() ?? ""
        };
    }

    private static string EmitIntersectionTypeAlias(TypeSymbol type, TypeNameResolver resolver, BuildContext ctx)
    {
        var sb = new StringBuilder();

        // Get final type name
        var finalName = ctx.Renamer.GetFinalTypeName(type);

        // VIEW COMPOSITION CONSTRAINTS: Type alias with constraints on LHS, plain args on RHS
        // export type TypeName<T extends IFoo> = TypeName$instance<T> & __TypeName$views<T>

        // Build RHS: both $instance and $views need type arguments
        var typeArgs = AliasEmit.GenerateTypeArguments(type);

        // DELEGATE CALL SIGNATURE: For delegates, prepend call signature to make arrow functions assignable
        // export type Func_2<T, TResult> = ((arg: T) => TResult) & Func_2$instance<T, TResult> & __Func_2$views<T, TResult>
        var callSignature = "";
        if (type.Kind == TypeKind.Delegate)
        {
            callSignature = BuildDelegateCallSignature(type, resolver, ctx);
            if (!string.IsNullOrEmpty(callSignature))
            {
                callSignature = callSignature + " & ";
            }
        }

        // BOOLEAN UNION FIX: System.Boolean must accept native TS boolean for predicate ergonomics
        // Arrow functions like (x => x % 2 === 0) return native boolean, but Func_2<T, Boolean> expects CLR Boolean.
        // Making Boolean a union allows both to work: export type Boolean = boolean | (Boolean$instance & __Boolean$views);
        var nativePrimitivePrefix = "";
        if (type.ClrFullName == "System.Boolean")
        {
            nativePrimitivePrefix = "boolean | (";
        }

        var nativePrimitiveSuffix = nativePrimitivePrefix.Length > 0 ? ")" : "";

        var rhsExpression = $"{nativePrimitivePrefix}{callSignature}{finalName}$instance{typeArgs} & __{finalName}$views{typeArgs}{nativePrimitiveSuffix}";

        // Emit the alias with constraints on LHS
        // Note: We pass the complete RHS (including type args), so we use the manual emission
        sb.Append("export type ");
        sb.Append(finalName);

        var typeParamsLHS = AliasEmit.GenerateTypeParametersWithConstraints(type, resolver, ctx);
        sb.Append(typeParamsLHS);

        sb.Append(" = ");
        sb.Append(rhsExpression);
        sb.AppendLine(";");

        return sb.ToString();
    }

    private static string Indent(string text, string indentation)
    {
        var lines = text.Split('\n').Select(line => string.IsNullOrWhiteSpace(line) ? line : indentation + line);
        return string.Join("\n", lines);
    }

    /// <summary>
    /// Build a TypeScript call signature for a delegate type based on its Invoke method.
    /// Example: Func_2&lt;T, TResult&gt; becomes "((arg: T) => TResult)"
    /// This allows arrow functions to be assignable to delegate types.
    /// </summary>
    private static string BuildDelegateCallSignature(TypeSymbol type, TypeNameResolver resolver, BuildContext ctx)
    {
        // Find the Invoke method - this defines the delegate's signature
        var invokeMethod = type.Members.Methods.FirstOrDefault(m => m.ClrName == "Invoke");
        if (invokeMethod == null)
        {
            return ""; // Fallback: no call signature if Invoke not found
        }

        // Build allowed type parameter names set for TypeRefPrinter
        var allowedTypeParams = new HashSet<string>(type.GenericParameters.Select(gp => gp.Name));

        // Build parameter list: (arg1: T, arg2: U, ...)
        var parameters = string.Join(", ", invokeMethod.Parameters.Select(p =>
        {
            var paramType = TypeRefPrinter.Print(p.Type, resolver, ctx, allowedTypeParams);
            return $"{p.Name}: {paramType}";
        }));

        // Build return type
        var returnType = TypeRefPrinter.Print(invokeMethod.ReturnType, resolver, ctx, allowedTypeParams);

        // Return call signature: ((params) => returnType)
        return $"(({parameters}) => {returnType})";
    }

    /// <summary>
    /// Check if namespace contains any pointer or byref types that require support type markers.
    /// Scans all public types and their members for PointerTypeReference or ByRefTypeReference.
    /// </summary>
    private static bool NamespaceUsesSupportTypes(NamespaceSymbol ns)
    {
        foreach (var type in ns.Types.Where(t => t.Accessibility == Accessibility.Public))
        {
            // TS2304 FIX: Check constructors for unsafe types
            foreach (var ctor in type.Members.Constructors)
            {
                // Constructors are always on class surface
                foreach (var param in ctor.Parameters)
                {
                    if (ContainsUnsafeType(param.Type))
                        return true;
                }
            }

            // Check methods (only those actually emitted to class/static surface)
            foreach (var method in type.Members.Methods)
            {
                // Only check methods on class/static surface (skip ViewOnly)
                if (method.EmitScope != EmitScope.ClassSurface && method.EmitScope != EmitScope.StaticSurface)
                    continue;

                // Check return type
                if (ContainsUnsafeType(method.ReturnType))
                    return true;

                // Check parameters
                foreach (var param in method.Parameters)
                {
                    if (ContainsUnsafeType(param.Type))
                        return true;
                }
            }

            // Check properties (only those on class/static surface)
            foreach (var prop in type.Members.Properties)
            {
                if (prop.EmitScope != EmitScope.ClassSurface && prop.EmitScope != EmitScope.StaticSurface)
                    continue;

                if (ContainsUnsafeType(prop.PropertyType))
                    return true;
            }

            // Check fields (only those on class/static surface)
            foreach (var field in type.Members.Fields)
            {
                if (field.EmitScope != EmitScope.ClassSurface && field.EmitScope != EmitScope.StaticSurface)
                    continue;

                if (ContainsUnsafeType(field.FieldType))
                    return true;
            }

            // Check events (only those on class/static surface)
            foreach (var evt in type.Members.Events)
            {
                if (evt.EmitScope != EmitScope.ClassSurface && evt.EmitScope != EmitScope.StaticSurface)
                    continue;

                if (ContainsUnsafeType(evt.EventHandlerType))
                    return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Recursively check if a type reference contains pointers or byrefs.
    /// </summary>
    private static bool ContainsUnsafeType(Model.Types.TypeReference typeRef)
    {
        return typeRef switch
        {
            Model.Types.PointerTypeReference => true,
            Model.Types.ByRefTypeReference => true,
            Model.Types.ArrayTypeReference arr => ContainsUnsafeType(arr.ElementType),
            Model.Types.NamedTypeReference named => named.TypeArguments.Any(ContainsUnsafeType),
            Model.Types.NestedTypeReference nested => ContainsUnsafeType(nested.FullReference),
            _ => false
        };
    }

}
