using System.Collections.Immutable;
using System.Text;
using tsbindgen.Core.Policy;
using tsbindgen.Emit.Printers;
using tsbindgen.Model;
using tsbindgen.Model.Symbols;
using tsbindgen.Model.Symbols.MemberSymbols;
using tsbindgen.Model.Types;
using tsbindgen.Plan;
using tsbindgen.Renaming;

namespace tsbindgen.Emit;

/// <summary>
/// Emits internal/index.d.ts files for each namespace.
/// Uses EmitOrder to generate declarations in deterministic order.
/// Orchestrates ClassPrinter, MethodPrinter, TypeRefPrinter.
/// </summary>
public static class InternalIndexEmitter
{
    /// <summary>
    /// Determines if a type should be emitted to .d.ts files.
    /// Top-level types stay public-only; nested protected/protected-internal types
    /// are also emitted when they are externally nameable from emitted signatures.
    /// </summary>
    public static bool ShouldEmit(TypeSymbol type)
    {
        return TypeEmissionAccessibility.IsEmittable(type);
    }

    public static void Emit(BuildContext ctx, EmissionPlan plan, string outputDirectory)
    {
        ctx.Log("InternalIndexEmitter", "Generating TypeScript declarations...");

        var emittedCount = 0;

        // Process each namespace in order
        foreach (var nsOrder in plan.EmissionOrder.Namespaces)
        {
            var ns = nsOrder.Namespace;
            ctx.Log("InternalIndexEmitter", $"  Emitting namespace: {ns.Name}");

            // Generate .d.ts content
            var content = GenerateNamespaceDeclaration(ctx, plan, nsOrder);

            // Write to file: output/Namespace.Name/internal/index.d.ts (or _root for empty namespace)
            // Use mapped output name if namespace-map is configured
            var outputName = NamespacePathMapper.GetOutputName(ns, ctx);
            var namespacePath = Path.Combine(outputDirectory, outputName);
            // Use _root for empty namespace to avoid case-sensitivity collision with "Internal" namespace
            var subdirName = ns.IsRoot ? "_root" : "internal";
            var internalPath = Path.Combine(namespacePath, subdirName);
            Directory.CreateDirectory(internalPath);

            var outputFile = Path.Combine(internalPath, "index.d.ts");
            File.WriteAllText(outputFile, content);

            ctx.Log("InternalIndexEmitter", $"    → {outputFile}");
            emittedCount++;
        }

        ctx.Log("InternalIndexEmitter", $"Generated {emittedCount} declaration files");
    }

    private static string GenerateNamespaceDeclaration(BuildContext ctx, EmissionPlan plan, NamespaceEmitOrder nsOrder)
    {
        // Extract plan components
        var graph = plan.Graph;
        // IMPORTANT: internal/index.d.ts must use the "internal" import plan.
        // In library mode, this imports from <pkg>/<Namespace>/internal/index.js and keeps arity-stable names.
        // This is required for assignability checks (e.g. DbSet<T> should satisfy IQueryable_1<T>).
        var importPlan = plan.ImportsInternal;
        var staticFlattening = plan.StaticFlattening;
        var staticConflicts = plan.StaticConflicts;
        var overrideConflicts = plan.OverrideConflicts;
        var propertyOverrides = plan.PropertyOverrides;
        var honestEmission = plan.HonestEmission;
        var safeToExtend = plan.SafeToExtend;

        // Create TypeNameResolver - single source of truth for type names
        // TS2693 FIX: Pass ImportPlan and current namespace for qualified name resolution
        var resolver = new TypeNameResolver(
            ctx,
            graph,
            importPlan,
            nsOrder.Namespace.Name,
            facadeMode: false,
            libraryImportStyle: Plan.LibraryImportStyle.InternalIndex);

        // V2 FIX: Create BindingsProvider for inherited member exposure (TS2416 fix)
        var bindingsProvider = new BindingsProvider(ctx, graph);

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Architecture");
        sb.AppendLine($"// Namespace: {nsOrder.Namespace.Name}");
        sb.AppendLine($"// Assembly: {string.Join(", ", nsOrder.Namespace.ContributingAssemblies.OrderBy(a => a))}");
        sb.AppendLine();

        SupportTypePreamble.EmitCoreTypeImports(sb);
        SupportTypePreamble.EmitOpaqueTypeSupportMarker(sb);

        // Emit import statements for cross-namespace type references
        var imports = importPlan.GetImportsFor(nsOrder.Namespace.Name);

        // CLR type names (Char, Int32, etc.) are defined in System namespace
        // Check if we need to add System_Internal for non-System namespaces
        var systemImport = imports.FirstOrDefault(i => i.TargetNamespace == "System");
        var needsSystemInternalForClrTypes = nsOrder.Namespace.Name != "System"
            && (systemImport == null || systemImport.TypeImports.All(ti => !ti.IsValueImport));

        if (imports.Count > 0 || needsSystemInternalForClrTypes)
        {
            sb.AppendLine("// Import types from other namespaces");

            // Add System_Internal namespace import for CLR type aliases if not already present
            if (needsSystemInternalForClrTypes)
            {
                // Use library package specifier if in library mode and System types are in the library
                string systemPath;
                if (ctx.LibraryContract != null && ctx.LibraryContract.AllowedClrFullNames.Contains("System.Int32"))
                {
                    // Library mode: import from external package internal index
                    // Use per-type mapping to get the correct package for System types
                    var systemPackage = ctx.LibraryContract.GetPackageForClrFullName("System.Int32");
                    systemPath = $"{systemPackage}/System/internal/index.js";
                }
                else
                {
                    // Normal mode: relative path with mapped output names
                    systemPath = Plan.PathPlanner.GetSpecifier(ctx, nsOrder.Namespace.Name, "System");
                }
                sb.AppendLine($"import * as System_Internal from \"{systemPath}\";");
            }

            // Sort imports by module specifier for stable output
            foreach (var import in imports.OrderBy(i => i.ImportPath))
            {
                // TS2693 FIX: Use namespace imports for value imports to make them accessible inside namespace blocks
                // TypeScript limitation: named value imports aren't accessible inside namespace declarations
                var valueImports = import.TypeImports.Where(ti => ti.IsValueImport).ToList();
                var typeOnlyImports = import.TypeImports.Where(ti => !ti.IsValueImport).ToList();

                // Emit BOTH named AND namespace imports for reflection types
                // - Named imports work outside namespace blocks (for simple names in return types)
                // - Namespace imports work inside namespace blocks (for base classes)
                // We need both to support reflection types used in both positions
                var reflectionValueImports = valueImports
                    .Where(ti => ReflectionTypes.IsCommonReflectionTypeName(import.TargetNamespace, ti.TypeName))
                    .ToList();

                // Emit named value imports for reflection types (accessible outside namespace)
                if (reflectionValueImports.Count > 0)
                {
                    var reflectionList = string.Join(", ", reflectionValueImports
                        .OrderBy(ti => ti.TypeName)
                        .Select(ti => ti.Alias != null ? $"{ti.TypeName} as {ti.Alias}" : ti.TypeName));

                    sb.AppendLine($"import {{ {reflectionList} }} from \"{import.ImportPath}\";");
                }

                // CRITICAL: Always emit namespace import for ALL value imports (not just non-reflection)
                // Namespace imports are required for accessing types inside namespace blocks
                if (valueImports.Count > 0)
                {
                    sb.AppendLine($"import * as {import.NamespaceAlias} from \"{import.ImportPath}\";");
                }

                // TS2416 FIX: Emit type-only imports for ALL types (not just non-value imports)
                // EXCEPT reflection types that were already imported as regular imports above
                // Types used in both value positions (extends) and type positions (return types) need BOTH:
                // - namespace import for extends: "import * as Foo_Internal"
                // - type import for return types: "import type { FooType }"
                // Example: ClaimsIdentity used in "extends ClaimsIdentity$instance" AND "clone(): ClaimsIdentity"
                var reflectionValueImportNames = new HashSet<string>(reflectionValueImports.Select(ti => ti.TypeName));
                var typesNotAlreadyImported = import.TypeImports
                    .Where(ti => !reflectionValueImportNames.Contains(ti.TypeName))
                    .ToList();

                if (typesNotAlreadyImported.Count > 0)
                {
                    var allTypeImportsList = string.Join(", ", typesNotAlreadyImported
                        .OrderBy(ti => ti.TypeName)
                        .Select(ti => ti.Alias != null ? $"{ti.TypeName} as {ti.Alias}" : ti.TypeName));

                    sb.AppendLine($"import type {{ {allTypeImportsList} }} from \"{import.ImportPath}\";");
                }
            }

            sb.AppendLine(); // Blank line after imports
        }

        var indent = string.Empty;

        // Track types that lost generics during emission (used for diagnostics/aliases)
        var typesWithoutGenerics = new HashSet<string>();

        static IEnumerable<TypeEmitOrder> EnumerateTypeOrders(IEnumerable<TypeEmitOrder> orders)
        {
            foreach (var order in orders)
            {
                yield return order;

                foreach (var nested in EnumerateTypeOrders(order.OrderedNestedTypes))
                {
                    yield return nested;
                }
            }
        }

        // Emit types in order (PUBLIC ONLY - internal types should not appear in .d.ts)
	        foreach (var typeOrder in EnumerateTypeOrders(nsOrder.OrderedTypes).Where(to => ShouldEmit(to.Type)))
	        {
	            // Check if type has explicit views (attached by ViewPlanner)
	            var views = typeOrder.Type.ExplicitViews;
	            var hasViews = views.Length > 0 && (typeOrder.Type.Kind == Model.Symbols.TypeKind.Class || typeOrder.Type.Kind == Model.Symbols.TypeKind.Struct || typeOrder.Type.Kind == Model.Symbols.TypeKind.Delegate);

	            if (hasViews)
	            {
	                // LINQ ASSIGNABILITY: Determine safe interfaces to extend.
	                // IMPORTANT: For some generic types (e.g. DbSet<TEntity>), TypeScript does NOT reliably
	                // apply heritage clauses added via declaration merging *after* the primary interface.
	                // To ensure members propagate (Expression/Provider/etc.), we inline the safe extends list
	                // into the primary $instance interface declaration instead of emitting a second declaration.
	                var mergedInterface = EmitMergedInterfaceExtends(typeOrder.Type, resolver, ctx, graph, safeToExtend);

	                // Emit class with $instance suffix - PUBLIC TYPES GET export KEYWORD
	                var instanceClass = ClassPrinter.PrintInstance(typeOrder.Type, resolver, ctx, graph, bindingsProvider, staticFlattening, staticConflicts, overrideConflicts, propertyOverrides, honestEmission, safeToExtend);
	                if (!string.IsNullOrEmpty(mergedInterface))
	                {
	                    instanceClass = InlineMergedInterfaceExtendsIntoInstance(instanceClass, mergedInterface);
	                }
	                var indentedInstance = Indent(instanceClass, indent);

	                // PUBLIC TYPES: Always export (both root and namespaces)
	                sb.Append("export ");
	                sb.AppendLine(indentedInstance);
	                sb.AppendLine();

                // STATIC-SIDE FIX: Emit value export for constructors and static members
                // This is a const declaration that replaces the static side of the class
                var valueExport = ClassPrinter.PrintValueExport(typeOrder.Type, resolver, ctx, graph, staticConflicts);
                if (!string.IsNullOrEmpty(valueExport))
                {
                    var indentedValue = Indent(valueExport, indent);
                    sb.AppendLine(indentedValue);
                    sb.AppendLine();
                }

                // Emit companion views interface - PUBLIC TYPES GET export KEYWORD
                var viewsInterface = EmitCompanionViewsInterface(typeOrder.Type, views, resolver, ctx);
                var indentedViews = Indent(viewsInterface, indent);

                // PUBLIC TYPES: Always export (both root and namespaces)
                sb.Append("export ");
                sb.AppendLine(indentedViews);
                sb.AppendLine();

                // Emit intersection type alias (already has export in the returned string)
                var typeAlias = EmitIntersectionTypeAlias(typeOrder.Type, resolver, ctx);
                var indentedAlias = Indent(typeAlias, indent);

	                // Type alias already includes "export" keyword
	                sb.AppendLine(indentedAlias);
	                sb.AppendLine();

	            }
	            else
	            {
                // Normal emission (no views) - PUBLIC TYPES GET export KEYWORD
                var typeDecl = ClassPrinter.Print(typeOrder.Type, resolver, ctx, graph, typesWithoutGenerics, bindingsProvider, staticFlattening, staticConflicts, overrideConflicts, propertyOverrides, honestEmission, safeToExtend);
                var indented = Indent(typeDecl, indent);

                // PUBLIC TYPES: Always export (both root and namespaces)
                sb.Append("export ");
                sb.AppendLine(indented);
                sb.AppendLine();

                // STATIC-SIDE FIX: Emit value export for constructors and static members (classes/structs only)
                var valueExport = ClassPrinter.PrintValueExport(typeOrder.Type, resolver, ctx, graph, staticConflicts);
                if (!string.IsNullOrEmpty(valueExport))
                {
                    var indentedValue = Indent(valueExport, indent);
                    sb.AppendLine(indentedValue);
                    sb.AppendLine();
	        }

                // C.5.2 FIX: For interfaces without views, emit alias pointing to $instance
                // This allows cross-namespace references like System.Collections.IEnumerable to work
                // Example: export type IEnumerable = IEnumerable$instance;
                // Only do this for interfaces - not for static classes, delegates, or enums
                var finalName = ctx.Renamer.GetFinalTypeName(typeOrder.Type);
                var instanceName = ctx.Renamer.GetInstanceTypeName(typeOrder.Type);
                var isInterface = typeOrder.Type.Kind == Model.Symbols.TypeKind.Interface;
                var isStaticClass = typesWithoutGenerics != null && typesWithoutGenerics.Contains(finalName);

                // LINQ ASSIGNABILITY: Emit merged interface extends for interfaces too
                // This ensures IEnumerator_1$instance<T> extends IDisposable$instance, etc.
                // Uses SafeToExtend analysis to only extend interfaces that won't cause TS2430/TS2320
                if (isInterface)
                {
                    var mergedInterface = EmitMergedInterfaceExtends(typeOrder.Type, resolver, ctx, graph, safeToExtend);
                    if (!string.IsNullOrEmpty(mergedInterface))
                    {
                        var indentedMerged = Indent(mergedInterface, indent);
                        sb.Append("export ");
                        sb.AppendLine(indentedMerged);
                        sb.AppendLine();
                    }
                }

                // Only emit alias for interfaces that aren't static classes
                if (isInterface && finalName != instanceName && !isStaticClass)
                {
                    var indexerIntersection = BuildIndexerIntersection(typeOrder.Type, resolver, ctx);

                    sb.Append(indent);
                    sb.Append("export type ");
                    sb.Append(finalName);

                    // Add type parameters if needed
                    var typeArgs = AliasEmit.GenerateTypeArguments(typeOrder.Type);
                    var typeParams = AliasEmit.GenerateTypeParametersWithConstraints(typeOrder.Type, resolver, ctx);
                    sb.Append(typeParams);

                    sb.Append(" = ");
                    sb.Append(instanceName);
                    sb.Append(typeArgs);
                    sb.Append(indexerIntersection);
                    sb.AppendLine(";");
                    sb.AppendLine();
                }

                // ESM FLATTENING: Provide module-level aliases for class/struct types without views
                // With namespace blocks removed, the stem name (GetFinalTypeName) must be exported
                // so facade/type-position references resolve. Skip static classes that lost generics
                // to avoid TS2315 (non-generic emitted type referenced as generic).
                //
                // NOTE: We use type aliases here (not value re-exports) because type aliases are
                // HOISTED in TypeScript, enabling forward references within the file. Value exports
                // for static access are added in the facade layer (see FacadeEmitter.cs).
                var isClassLike = typeOrder.Type.Kind is Model.Symbols.TypeKind.Class or Model.Symbols.TypeKind.Struct or Model.Symbols.TypeKind.StaticNamespace;
                var needsAlias = isClassLike && finalName != instanceName && !isStaticClass;
                if (needsAlias)
                {
                    // C# LAMBDA CONVERSION: Expression<TDelegate> should accept lambdas (TDelegate)
                    // at the TypeScript surface so queryable APIs can be called ergonomically.
                    // Model this as a union: Expression_1<T> = T | Expression_1$instance<T>.
                    var rhsExpression = instanceName;
                    if (typeOrder.Type.Namespace == "System.Linq.Expressions" &&
                        finalName == "Expression_1" &&
                        typeOrder.Type.GenericParameters.Length == 1)
                    {
                        rhsExpression = $"{typeOrder.Type.GenericParameters[0].Name} | {instanceName}";
                    }

                    var indexerIntersection = BuildIndexerIntersection(typeOrder.Type, resolver, ctx);
                    if (string.IsNullOrEmpty(indexerIntersection))
                    {
                        // Fast path: simple alias emission
                        AliasEmit.EmitGenericAlias(
                            sb,
                            aliasName: finalName,
                            sourceType: typeOrder.Type,
                            rhsExpression: rhsExpression,
                            resolver,
                            ctx,
                            withConstraints: true);
                    }
                    else
                    {
                        // Indexers must be represented via intersection at the alias level.
                        // We must emit manually (not AliasEmit.EmitGenericAlias) because that helper appends
                        // generic type arguments after the full RHS expression, which would incorrectly
                        // bind `<T>` to the intersection literal instead of the `$instance` identifier.
                        sb.Append(indent);
                        sb.Append("export type ");
                        sb.Append(finalName);

                        var typeParamsLHS = AliasEmit.GenerateTypeParametersWithConstraints(typeOrder.Type, resolver, ctx);
                        sb.Append(typeParamsLHS);

                        sb.Append(" = ");

                        // Append type args to the RHS so they bind to the trailing identifier (typically `$instance`).
                        // This preserves the Expression_1 special-case union shape too.
                        var typeArgs = AliasEmit.GenerateTypeArguments(typeOrder.Type);
                        sb.Append(rhsExpression);
                        sb.Append(typeArgs);
                        sb.Append(indexerIntersection);
                        sb.AppendLine(";");
                    }
                    sb.AppendLine();
                }

            }
        }

        return SupportTypePreamble.FinalizeOpaqueTypeSupport(sb.ToString());
    }

	    private static string InlineMergedInterfaceExtendsIntoInstance(string instanceDecl, string mergedInterfaceDecl)
	    {
	        // mergedInterfaceDecl format (no export keyword):
	        //   interface Foo$instance<T> extends A, B {}
	        // instanceDecl format:
	        //   interface Foo$instance<T> { ... }
	        // or
	        //   interface Foo$instance<T> extends X { ... }

	        const string extendsToken = " extends ";
	        var mergedTrimmed = mergedInterfaceDecl.Trim();
	        if (mergedTrimmed.EndsWith(" {}", StringComparison.Ordinal))
	            mergedTrimmed = mergedTrimmed.Substring(0, mergedTrimmed.Length - 3).TrimEnd();

	        var extendsIndex = FindHeritageExtendsIndex(mergedTrimmed, extendsToken);
	        if (extendsIndex < 0)
	            return instanceDecl;

	        var extendsList = mergedTrimmed.Substring(extendsIndex + extendsToken.Length).Trim();
	
	        // Update only the first line containing the interface header.
	        var lines = instanceDecl.Split('\n');
	        for (var i = 0; i < lines.Length; i++)
	        {
	            var line = lines[i];
	            var braceIndex = line.IndexOf('{');
	            if (braceIndex < 0)
	                continue;

	            var header = line.Substring(0, braceIndex);

	            // If header already has extends, merge lists deterministically.
	            var existingExtendsIndex = FindHeritageExtendsIndex(header, extendsToken);
	            if (existingExtendsIndex >= 0)
	            {
	                var existingList = header.Substring(existingExtendsIndex + extendsToken.Length).Trim();
	                var merged = MergeExtendsLists(existingList, extendsList);
	                lines[i] = header.Substring(0, existingExtendsIndex) + extendsToken + merged + " " + line.Substring(braceIndex);
	                return string.Join("\n", lines);
	            }

	            // Insert extends list right before the opening brace.
	            lines[i] = header.TrimEnd() + extendsToken + extendsList + " " + line.Substring(braceIndex);
	            return string.Join("\n", lines);
	        }

	        return instanceDecl;
	    }

	    private static int FindHeritageExtendsIndex(string header, string extendsToken)
	    {
	        // Header may include `extends` inside generic parameter constraints (e.g. `<T extends IFoo>`),
	        // and may also include generic type arguments in the base list (e.g. `extends Foo_1<Bar>`).
	        //
	        // We must find the *heritage* `extends` clause, not the `extends` keyword inside `<...>`.
	        // The simplest robust approach: scan for the token at top-level (angleDepth == 0).
	        var angleDepth = 0;
	        for (var i = 0; i <= header.Length - extendsToken.Length; i++)
	        {
	            var c = header[i];
	            if (c == '<') angleDepth++;
	            else if (c == '>' && angleDepth > 0) angleDepth--;

	            if (angleDepth == 0 && header.AsSpan(i).StartsWith(extendsToken, StringComparison.Ordinal))
	                return i;
	        }

	        return -1;
	    }

	    private static int FindMatchingAngleBracketEnd(string text, int ltIndex)
	    {
	        var depth = 0;
	        for (var i = ltIndex; i < text.Length; i++)
	        {
	            var c = text[i];
	            if (c == '<') depth++;
	            else if (c == '>')
	            {
	                depth--;
	                if (depth == 0) return i;
	            }
	        }

	        return -1;
	    }

	    private static string MergeExtendsLists(string existingList, string additionalList)
	    {
	        // Merge and de-duplicate while preserving deterministic order.
	        // We keep existing entries first, then append new unique entries.
	        var items = new List<string>();
	        var seen = new HashSet<string>(StringComparer.Ordinal);

	        void AddItems(string list)
	        {
	            foreach (var raw in SplitTopLevelCommaSeparated(list))
	            {
	                var item = raw.Trim();
	                if (item.Length == 0)
	                    continue;
	                if (seen.Add(item))
	                    items.Add(item);
	            }
	        }

	        AddItems(existingList);
	        AddItems(additionalList);
	
	        return string.Join(", ", items);
	    }

	    private static IEnumerable<string> SplitTopLevelCommaSeparated(string list)
	    {
	        // Split a comma-separated list while respecting nested generic argument lists.
	        //
	        // Example:
	        //   IAdd_3<Foo<T>, Foo<T>, Foo<T>>, IBit_3<Foo<T>, Foo<T>, Foo<T>>
	        //
	        // We must NOT split on commas inside `<...>`.
	        var start = 0;
	        var angleDepth = 0;
	        var parenDepth = 0;
	        var bracketDepth = 0;
	        var braceDepth = 0;

	        for (var i = 0; i < list.Length; i++)
	        {
	            var c = list[i];
	            switch (c)
	            {
	                case '<':
	                    angleDepth++;
	                    break;
	                case '>':
	                    if (angleDepth > 0) angleDepth--;
	                    break;
	                case '(':
	                    parenDepth++;
	                    break;
	                case ')':
	                    if (parenDepth > 0) parenDepth--;
	                    break;
	                case '[':
	                    bracketDepth++;
	                    break;
	                case ']':
	                    if (bracketDepth > 0) bracketDepth--;
	                    break;
	                case '{':
	                    braceDepth++;
	                    break;
	                case '}':
	                    if (braceDepth > 0) braceDepth--;
	                    break;
	                case ',':
	                    if (angleDepth == 0 && parenDepth == 0 && bracketDepth == 0 && braceDepth == 0)
	                    {
	                        yield return list.Substring(start, i - start);
	                        start = i + 1;
	                    }
	                    break;
	            }
	        }

	        if (start <= list.Length)
	            yield return list.Substring(start);
	    }

    /// <summary>
    /// INTERNAL CONSTRAINTS: Generates generic type parameters WITH constraints for internal convenience exports.
    /// Mirrors the facade constraint propagation logic to fix TS2344 errors in module-level type aliases.
    /// PRIMITIVE CONSTRAINT RELAXATION: IEquatable_1<T>, IComparable_1<T>, IComparable
    /// are widened to admit TS primitives (number | string | boolean).
    /// </summary>
    private static string GenerateTypeParametersWithConstraints(
        Model.Symbols.TypeSymbol sourceType,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        var gps = sourceType.GenericParameters;
        if (gps.Length == 0)
            return string.Empty;

        var parts = new List<string>(gps.Length);

        foreach (var gp in gps)
        {
            // Collect type constraints (interfaces/classes)
            // Skip C# special constraints (struct, class, new()) as TypeScript can't express them
            var typeConstraints = gp.Constraints
                .Where(c => c is not null && !IsSpecialConstraint(c))
                .ToList();

            if (typeConstraints.Count == 0)
            {
                parts.Add($"{gp.Name} extends {AliasEmit.BuildConstraintText(gp, Array.Empty<string>())}");
            }
            else
            {
                // Print each constraint using TypeRefPrinter (handles imports, qualification, etc.)
                // PRIMITIVE CONSTRAINT RELAXATION: Widen value semantics constraints
                var constraintStrings = typeConstraints
                    .Select(c =>
                    {
                        var printed = Printers.TypeRefPrinter.Print(c, resolver, ctx);
                        // Relax IEquatable_1<T>, IComparable_1<T>, IComparable to admit primitives
                        if (AliasEmit.IsValueSemanticsConstraint(c, gp.Name))
                        {
                            return AliasEmit.RelaxConstraintForPrimitives(printed, gp.Name);
                        }
                        return printed;
                    })
                    .Where(c => c != "any" && !Printers.TypeRefPrinter.IsOpaqueTypeText(c))
                    .ToArray();

                parts.Add($"{gp.Name} extends {AliasEmit.BuildConstraintText(gp, constraintStrings)}");
            }
        }

        return $"<{string.Join(", ", parts)}>";
    }

    /// <summary>
    /// Check if a constraint is a C# special constraint (struct, class, new()).
    /// These don't translate to TypeScript and should be filtered out.
    /// </summary>
    private static bool IsSpecialConstraint(Model.Types.TypeReference constraint)
    {
        // Special constraints (struct, class, new()) are not in GenericParameter.Constraints
        // They're represented by separate flags in the model
        // This method is here for future-proofing in case the model changes
        return false;
    }

    private static void EmitBrandedPrimitiveImports(StringBuilder sb)
    {
        SupportTypePreamble.EmitCoreTypeImports(sb);
    }


    /// <summary>
    /// LINQ ASSIGNABILITY: Emit a merged interface declaration that extends safe interfaces.
    /// This uses TypeScript declaration merging to make T$instance assignable to interface types
    /// without requiring "implements" (which would trigger TS2420 member compliance checks).
    ///
    /// Example output:
    ///   export interface List_1$instance&lt;T&gt; extends IEnumerable_1$instance&lt;T&gt;, ICollection_1$instance&lt;T&gt; {}
    ///
    /// This enables:
    ///   declare function takeEnum&lt;T&gt;(x: IEnumerable_1&lt;T&gt;): void;
    ///   const list = new List_1&lt;int&gt;();
    ///   takeEnum(list);  // ✓ type-checks without .As_IEnumerable_1()
    ///
    /// Uses SafeToExtend analysis to only extend interfaces that won't cause TS2430/TS2320.
    /// Interfaces that would create member signature conflicts are accessible via views instead.
    /// </summary>
    private static string? EmitMergedInterfaceExtends(
        TypeSymbol type,
        TypeNameResolver resolver,
        BuildContext ctx,
        SymbolGraph graph,
        Dictionary<string, Plan.SafeToExtendAnalyzer.SafeToExtendResult> safeToExtend)
    {
        // Get assignable interfaces from SafeToExtend analysis
        var typeStableId = type.StableId.ToString();
        if (!safeToExtend.TryGetValue(typeStableId, out var safeToExtendResult))
        {
            // No analysis for this type - no extends to emit
            return null;
        }

        var interfaces = safeToExtendResult.AssignableInterfaces;
        if (interfaces.Count == 0)
            return null;

        var sb = new StringBuilder();

        // Get the instance type name
        var instanceName = ctx.Renamer.GetInstanceTypeName(type);

        sb.Append($"interface {instanceName}");

        // Add generic parameters with constraints
        if (type.GenericParameters.Length > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", type.GenericParameters.Select(gp =>
                PrintGenericParameterWithConstraints(gp, resolver, ctx))));
            sb.Append('>');
        }

        sb.Append(" extends ");

        // Interfaces are already sorted by CLR full name from SafeToExtend analyzer (deterministic)
        // Emit extends list with correct $instance suffix and type arguments
        var extendsList = new List<string>();
        foreach (var iface in interfaces)
        {
            var interfaceName = PrintInterfaceForExtends(iface, type.Namespace, resolver, ctx, graph);
            extendsList.Add(interfaceName);
        }

        sb.Append(string.Join(", ", extendsList));
        sb.Append(" {}");

        return sb.ToString();
    }

    /// <summary>
    /// Check if an interface is in the symbol graph (exists in emitted output).
    /// </summary>
    private static bool IsInterfaceInGraph(TypeReference ifaceRef, SymbolGraph graph)
    {
        if (ifaceRef is not NamedTypeReference named)
            return true; // Non-named types (generic parameters, etc.) are always allowed

        // TypeIndex uses ClrFullName as key
        return graph.TypeIndex.TryGetValue(named.FullName, out _);
    }

    /// <summary>
    /// Check if an interface is a non-generic System.Collections interface that conflicts
    /// with its generic counterpart. These interfaces have methods like GetEnumerator()
    /// that return different types (IEnumerator vs IEnumerator&lt;T&gt;), causing TS2430 errors
    /// when both are extended.
    ///
    /// C# handles this via explicit interface implementation, but TypeScript cannot express
    /// this pattern, so we filter them out from the merged extends.
    /// </summary>
    private static bool IsConflictingNonGenericInterface(TypeReference ifaceRef)
    {
        if (ifaceRef is not NamedTypeReference named)
            return false;

        var fullName = named.FullName;

        // List of non-generic System.Collections interfaces that conflict with generic ones
        return fullName switch
        {
            "System.Collections.IEnumerable" => true,
            "System.Collections.IEnumerator" => true,
            "System.Collections.ICollection" => true,
            "System.Collections.IList" => true,
            "System.Collections.IDictionary" => true,
            "System.Collections.IDictionaryEnumerator" => true,
            "System.Collections.IComparer" => true,
            "System.Collections.IEqualityComparer" => true,
            "System.Collections.IStructuralComparable" => true,
            "System.Collections.IStructuralEquatable" => true,
            _ => false
        };
    }

    /// <summary>
    /// Get the CLR full name from an interface reference for sorting.
    /// </summary>
    private static string GetInterfaceFullName(TypeReference ifaceRef)
    {
        return ifaceRef switch
        {
            NamedTypeReference named => named.FullName,
            NestedTypeReference nested => nested.FullReference.FullName,
            _ => ifaceRef.ToString() ?? ""
        };
    }

    /// <summary>
    /// Print an interface reference for use in the extends clause of merged interface.
    /// Ensures correct $instance suffix and cross-namespace qualification.
    /// </summary>
    private static string PrintInterfaceForExtends(
        TypeReference ifaceRef,
        string currentNamespace,
        TypeNameResolver resolver,
        BuildContext ctx,
        SymbolGraph graph)
    {
        // Print the interface using TypeRefPrinter (handles type args correctly)
        var baseName = Printers.TypeRefPrinter.Print(ifaceRef, resolver, ctx,
            allowedTypeParameterNames: null, forValuePosition: true);

        // Apply $instance suffix for same-namespace interfaces that have views
        baseName = ApplyInstanceSuffixForExtends(baseName, ifaceRef, currentNamespace, graph, ctx);

        // If cross-namespace, ensure it's qualified
        if (ifaceRef is NamedTypeReference named)
        {
            var interfaceNamespace = ExtractNamespace(named.FullName);

            if (!string.IsNullOrEmpty(interfaceNamespace) &&
                interfaceNamespace != currentNamespace &&
                !baseName.Contains('.'))
            {
                var namespaceAlias = interfaceNamespace.Replace('.', '_') + "_Internal";
                return $"{namespaceAlias}.{baseName}";
            }
        }

        return baseName;
    }

    /// <summary>
    /// Apply $instance suffix to interface names for extends clause.
    /// Interfaces don't have views, so we use $instance suffix to match the emitted type name.
    /// </summary>
    private static string ApplyInstanceSuffixForExtends(
        string typeName,
        TypeReference ifaceRef,
        string currentNamespace,
        SymbolGraph graph,
        BuildContext ctx)
    {
        if (ifaceRef is not NamedTypeReference named)
            return typeName;

        // Find the interface in the graph
        if (!graph.TypeIndex.TryGetValue(named.FullName, out var ifaceSymbol))
            return typeName;

        // Check if it's an interface and in the same namespace
        if (ifaceSymbol.Kind != TypeKind.Interface)
            return typeName;

        var interfaceNamespace = ExtractNamespace(named.FullName);
        if (interfaceNamespace != currentNamespace)
            return typeName; // Cross-namespace already handled by qualification

        // Check if name already has $instance suffix (avoid double-suffix)
        var genericStart = typeName.IndexOf('<');
        var basePart = genericStart >= 0 ? typeName.Substring(0, genericStart) : typeName;

        if (basePart.EndsWith("$instance"))
            return typeName; // Already has suffix

        // For same-namespace interfaces, add $instance suffix
        if (genericStart >= 0)
        {
            var typeArgsPart = typeName.Substring(genericStart);
            return $"{basePart}$instance{typeArgsPart}";
        }
        else
        {
            return $"{typeName}$instance";
        }
    }

    /// <summary>
    /// Extract namespace from CLR full name.
    /// </summary>
    private static string ExtractNamespace(string fullName)
    {
        // Remove assembly qualification if present
        var commaIndex = fullName.IndexOf(',');
        if (commaIndex >= 0)
            fullName = fullName.Substring(0, commaIndex).Trim();

        // Extract namespace (everything before the last dot)
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(0, lastDot) : "";
    }

    private static string EmitCompanionViewsInterface(TypeSymbol type, ImmutableArray<Shape.ViewPlanner.ExplicitView> views, TypeNameResolver resolver, BuildContext ctx)
    {
        var sb = new StringBuilder();

        // Get final type name
        var finalName = ctx.Renamer.GetFinalTypeName(type);

        // Companion interface: __TypeName$views<...>
        sb.Append($"interface __{finalName}$views");

        // TS2344 FIX: Generic parameters WITH CONSTRAINTS
        // View interface must have same constraints as the type alias
        // Otherwise: type Foo<T extends IBar<T>> = Foo$instance<T> & __Foo$views<T>
        // fails because __Foo$views<T> doesn't have the constraint
        if (type.GenericParameters.Length > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", type.GenericParameters.Select(gp =>
                PrintGenericParameterWithConstraints(gp, resolver, ctx))));
            sb.Append('>');
        }

        sb.AppendLine(" {");

        // Emit view accessor methods (not properties - methods are the stable API)
        foreach (var view in views)
        {
            sb.Append("    ");
            sb.Append(view.ViewPropertyName);
            sb.Append("(): ");

            // FIX D: Match view's interface reference to type's actual interface implementation
            // to get correct type arguments (fixes generic "T" leaks in view interfaces)
            var matchedInterface = FindMatchingInterface(type, view.InterfaceReference);
            var interfaceToEmit = matchedInterface ?? view.InterfaceReference;

            // TS2304 FIX: View interfaces need namespace qualification
            // Some view interfaces (like IEnumerable) are transitively implemented and not in
            // ValueImportQualifiedNames, so we need to manually qualify cross-namespace types
            // NOTE: Always emit actual CLR type arguments (e.g., INumberBase_1<int> for Int32).
            // Never substitute 'any' - that breaks type safety. The real self-type satisfies
            // recursive constraints because Int32 genuinely implements INumberBase_1<Int32>.
            var viewTypeName = QualifyViewInterface(interfaceToEmit, type.Namespace, resolver, ctx);
            sb.Append(viewTypeName);
            sb.AppendLine(";");
        }

        // TS2344 FIX: Add structural method bridges for numeric interface constraints
        // TypeScript uses structural typing - interfaces require PascalCase methods
        // but instance classes use camelCase. Add PascalCase methods to satisfy constraints.
        var numericInterfaces = GetNumericInterfaceSet(views);
        if (numericInterfaces != null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Structural method bridges for numeric interface constraints");
            EmitNumericStructuralMethods(sb, type, numericInterfaces, resolver, ctx);
        }

        sb.Append("}");

        return sb.ToString();
    }

    /// <summary>
    /// Get the set of numeric interfaces that require structural method bridges.
    /// Returns null if no numeric interfaces are implemented.
    /// </summary>
    private static HashSet<string>? GetNumericInterfaceSet(ImmutableArray<Shape.ViewPlanner.ExplicitView> views)
    {
        HashSet<string>? interfaces = null;

        foreach (var view in views)
        {
            if (view.InterfaceReference is Model.Types.NamedTypeReference named)
            {
                var interfaceName = named.FullName;

                // Track which specific numeric interfaces are implemented
                if (interfaceName.Contains("System.Numerics.INumber`1") ||
                    interfaceName.Contains("System.Numerics.IBinaryInteger`1") ||
                    interfaceName.Contains("System.Numerics.IFloatingPoint`1") ||
                    interfaceName.Contains("System.Numerics.INumberBase`1") ||
                    interfaceName.Contains("System.Numerics.IRootFunctions`1") ||
                    interfaceName.Contains("System.Numerics.ITrigonometricFunctions`1") ||
                    interfaceName.Contains("System.IEquatable`1") ||
                    interfaceName.Contains("System.IComparable") ||
                    interfaceName.Contains("System.IUtf8SpanFormattable"))
                {
                    interfaces ??= new HashSet<string>();

                    // Normalize to generic base name for easier checking
                    if (interfaceName.Contains("System.Numerics.INumber`1"))
                        interfaces.Add("INumber");
                    if (interfaceName.Contains("System.Numerics.IBinaryInteger`1"))
                        interfaces.Add("IBinaryInteger");
                    if (interfaceName.Contains("System.Numerics.IFloatingPoint`1"))
                        interfaces.Add("IFloatingPoint");
                    if (interfaceName.Contains("System.Numerics.INumberBase`1"))
                        interfaces.Add("INumberBase");
                    if (interfaceName.Contains("System.Numerics.IRootFunctions`1"))
                        interfaces.Add("IRootFunctions");
                    if (interfaceName.Contains("System.Numerics.ITrigonometricFunctions`1"))
                        interfaces.Add("ITrigonometricFunctions");
                    if (interfaceName.Contains("System.IEquatable`1"))
                        interfaces.Add("IEquatable");
                    if (interfaceName.Contains("System.IComparable"))
                        interfaces.Add("IComparable");
                    if (interfaceName.Contains("System.IUtf8SpanFormattable"))
                        interfaces.Add("IUtf8SpanFormattable");
                }
            }
        }

        return interfaces;
    }

    /// <summary>
    /// Emit structural method bridges to satisfy numeric interface constraints.
    /// These methods must match the naming style of the interface members they satisfy.
    /// Only emits methods for the specific interfaces actually implemented.
    /// </summary>
    private static void EmitNumericStructuralMethods(
        StringBuilder sb,
        TypeSymbol type,
        HashSet<string> numericInterfaces,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        // Get the actual type name with generic parameters for use in signatures
        var typeName = ctx.Renamer.GetFinalTypeName(type);
        if (type.GenericParameters.Length > 0)
        {
            typeName += $"<{string.Join(", ", type.GenericParameters.Select(gp => gp.Name))}>";
        }

        // Determine if we're in System namespace (can use simple names)
        var inSystemNamespace = type.Namespace == "System";

        // Helper to get qualified type name
        string Qualified(string simpleName)
        {
            if (inSystemNamespace)
                return simpleName;
            else
                return $"import(\"../../System/internal/index\").{simpleName}";
        }

        // IEquatable<T>.Equals
        if (numericInterfaces.Contains("IEquatable"))
        {
            sb.AppendLine($"    Equals(other: {typeName}): boolean;");
        }

        // IComparable.CompareTo
        if (numericInterfaces.Contains("IComparable"))
        {
            sb.AppendLine($"    CompareTo(obj: JsValue): int;");
        }

        // INumberBase<TSelf>, INumber<TSelf>, IBinaryInteger<TSelf>, IFloatingPoint<TSelf>, etc.
        // All require ToString and TryFormat
        if (numericInterfaces.Contains("INumberBase") ||
            numericInterfaces.Contains("INumber") ||
            numericInterfaces.Contains("IBinaryInteger") ||
            numericInterfaces.Contains("IFloatingPoint") ||
            numericInterfaces.Contains("IRootFunctions") ||
            numericInterfaces.Contains("ITrigonometricFunctions"))
        {
            sb.AppendLine($"    ToString(format: string, formatProvider: {Qualified("IFormatProvider")}): string;");
            // ref/out modifiers are ABI semantics tracked in metadata, not TS types - emit plain element type
            sb.AppendLine($"    TryFormat(destination: {Qualified("Span_1")}<{Qualified("Char")}>, charsWritten: int, format: {Qualified("ReadOnlySpan_1")}<{Qualified("Char")}>, provider: {Qualified("IFormatProvider")}): boolean;");
        }

        // IUtf8SpanFormattable - TryFormat UTF-8 overload (byte version)
        // This overload is required when the interface hierarchy includes IUtf8SpanFormattable
        if (numericInterfaces.Contains("IUtf8SpanFormattable"))
        {
            // ref/out modifiers are ABI semantics tracked in metadata, not TS types - emit plain element type
            sb.AppendLine($"    TryFormat(utf8Destination: {Qualified("Span_1")}<{Qualified("Byte")}>, bytesWritten: int, format: {Qualified("ReadOnlySpan_1")}<{Qualified("Char")}>, provider: {Qualified("IFormatProvider")}): boolean;");
        }

        // IBinaryInteger<TSelf> - GetByteCount, TryWriteBigEndian, WriteBigEndian
        if (numericInterfaces.Contains("IBinaryInteger"))
        {
            sb.AppendLine($"    GetByteCount(): int;");
            // ref/out modifiers are ABI semantics tracked in metadata, not TS types - emit plain element type
            sb.AppendLine($"    TryWriteBigEndian(destination: {Qualified("Span_1")}<{Qualified("Byte")}>, bytesWritten: int): boolean;");
            // WriteBigEndian overloads
            sb.AppendLine($"    WriteBigEndian(destination: byte[], startIndex: int): int;");
            sb.AppendLine($"    WriteBigEndian(destination: byte[]): int;");
            sb.AppendLine($"    WriteBigEndian(destination: {Qualified("Span_1")}<{Qualified("Byte")}>): int;");
        }

        // IFloatingPoint<TSelf> - GetExponentByteCount, GetExponentShortestBitLength, TryWriteExponentBigEndian, WriteExponentBigEndian
        if (numericInterfaces.Contains("IFloatingPoint"))
        {
            sb.AppendLine($"    GetExponentByteCount(): int;");
            sb.AppendLine($"    GetExponentShortestBitLength(): int;");
            // ref/out modifiers are ABI semantics tracked in metadata, not TS types - emit plain element type
            sb.AppendLine($"    TryWriteExponentBigEndian(destination: {Qualified("Span_1")}<{Qualified("Byte")}>, bytesWritten: int): boolean;");
            // WriteExponentBigEndian overloads
            sb.AppendLine($"    WriteExponentBigEndian(destination: byte[], startIndex: int): int;");
            sb.AppendLine($"    WriteExponentBigEndian(destination: byte[]): int;");
            sb.AppendLine($"    WriteExponentBigEndian(destination: {Qualified("Span_1")}<{Qualified("Byte")}>): int;");
        }
    }

    /// <summary>
    /// Print a generic parameter with its constraints for use in type declarations.
    /// E.g., "T extends IFoo & IBar"
    /// PRIMITIVE CONSTRAINT RELAXATION: IEquatable_1<T>, IComparable_1<T>, IComparable
    /// are widened to admit TS primitives (number | string | boolean).
    /// </summary>
    private static string PrintGenericParameterWithConstraints(
        Model.Symbols.GenericParameterSymbol gp,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        var sb = new StringBuilder();
        sb.Append(gp.Name);

        // Add constraints
        if (gp.Constraints.Length > 0)
        {
            sb.Append(" extends ");

            // PRIMITIVE CONSTRAINT RELAXATION: Widen value semantics constraints
            var constraints = gp.Constraints.Select(c =>
            {
                var printed = Printers.TypeRefPrinter.Print(c, resolver, ctx);
                // Relax IEquatable_1<T>, IComparable_1<T>, IComparable to admit primitives
                if (AliasEmit.IsValueSemanticsConstraint(c, gp.Name))
                {
                    return AliasEmit.RelaxConstraintForPrimitives(printed, gp.Name);
                }
                return printed;
            })
            .Where(c => c != "any" && !Printers.TypeRefPrinter.IsOpaqueTypeText(c))
            .ToArray();
            sb.Append(AliasEmit.BuildConstraintText(gp, constraints));
        }
        else
        {
            sb.Append(" extends ");
            sb.Append(AliasEmit.BuildConstraintText(gp, Array.Empty<string>()));
        }

        return sb.ToString();
    }

    /// <summary>
    /// TS2304 FIX: Qualify view interface types with namespace alias if cross-namespace.
    /// View interfaces that are transitively implemented (not directly in implements clause)
    /// don't get added to ValueImportQualifiedNames, so we need manual qualification.
    /// </summary>
    private static string QualifyViewInterface(
        Model.Types.TypeReference interfaceRef,
        string currentNamespace,
        TypeNameResolver resolver,
        BuildContext ctx)
    {
        // Always emit actual CLR type arguments using the normal type printer.
        // For self-referential interfaces (e.g., INumberBase_1<Int32>), this emits
        // the real instantiation which satisfies the recursive constraint correctly.
        // NEVER substitute 'any' - that breaks type safety and poisons downstream inference.
        var baseName = Printers.TypeRefPrinter.Print(interfaceRef, resolver, ctx,
            forValuePosition: true);

        // If it's a NamedTypeReference, check if it's cross-namespace
        if (interfaceRef is Model.Types.NamedTypeReference named)
        {
            // Extract namespace from CLR full name
            var fullName = named.FullName;
            var commaIndex = fullName.IndexOf(',');
            if (commaIndex >= 0)
            {
                fullName = fullName.Substring(0, commaIndex).Trim();
            }

            var interfaceNamespace = fullName.Contains('.')
                ? fullName.Substring(0, fullName.LastIndexOf('.'))
                : "";

            // If cross-namespace and not already qualified (doesn't contain '.'), qualify it
            if (!string.IsNullOrEmpty(interfaceNamespace) &&
                interfaceNamespace != currentNamespace &&
                !baseName.Contains('.'))
            {
                // Flat ESM: qualify with namespace import alias only
                var namespaceAlias = interfaceNamespace.Replace('.', '_') + "_Internal";
                return $"{namespaceAlias}.{baseName}";
            }
        }

        return baseName;
    }

    /// <summary>
    /// FIX D: Find the matching interface in type.Interfaces that corresponds to the view's interface reference.
    /// Returns the matched interface with correct type arguments, or null if not found.
    /// </summary>
    private static TypeReference? FindMatchingInterface(TypeSymbol type, TypeReference viewInterfaceRef)
    {
        // Get the base name without type arguments for matching
        var viewBaseName = GetInterfaceBaseName(viewInterfaceRef);

        foreach (var implementedInterface in type.Interfaces)
        {
            var implBaseName = GetInterfaceBaseName(implementedInterface);

            // Match by base name (e.g., "IEnumerator_1" matches)
            if (viewBaseName == implBaseName)
            {
                return implementedInterface;
            }
        }

        return null;
    }

    /// <summary>
    /// Get the base name of an interface (without type arguments) for matching.
    /// Examples: "IEnumerator`1" -> "IEnumerator`1", "System.Collections.Generic.IEnumerator`1" -> "IEnumerator`1"
    /// </summary>
    private static string GetInterfaceBaseName(TypeReference typeRef)
    {
        return typeRef switch
        {
            NamedTypeReference named => named.Name,  // Just the name, e.g., "IEnumerator`1"
            NestedTypeReference nested => nested.NestedName,
            _ => typeRef.ToString() ?? ""
        };
    }

    private static string EmitIntersectionTypeAlias(TypeSymbol type, TypeNameResolver resolver, BuildContext ctx)
    {
        var sb = new StringBuilder();

        // Get final type name
        var finalName = ctx.Renamer.GetFinalTypeName(type);
        var shapeName = $"{finalName}$shape";

        // VIEW COMPOSITION CONSTRAINTS: Type alias with constraints on LHS, plain args on RHS
        // export type TypeName<T extends IFoo> = TypeName$instance<T> & __TypeName$views<T>

        // Build RHS: both $instance and $views need type arguments
        var typeArgs = AliasEmit.GenerateTypeArguments(type);

        // DELEGATE CALL SIGNATURE: For delegates, prepend call signature to make arrow functions assignable
        // export type Func_2<T, TResult> = ((arg: T) => TResult) & Func_2$instance<T, TResult> & __Func_2$views<T, TResult>
        var callSignature = "";
        if (type.Kind == TypeKind.Delegate)
        {
            callSignature = BuildDelegateCallSignature(type, resolver, ctx);
            if (!string.IsNullOrEmpty(callSignature))
            {
                callSignature = callSignature + " & ";
            }
        }

        // PRIMITIVE TYPE EMISSION: For primitives (System.String, System.Int32, etc.), use the
        // TypeScript carrier type (string, number, boolean) as the base in the intersection.
        // This enables LINQ assignability: List<int> is assignable to IEnumerable<Int32> because
        // Int32 = int & Int32$instance & ... and `int` is assignable to `int`.
        // Example: export type String = string & String$instance & __String$views;
        var primitiveCarrier = PrimitiveLift.GetTsCarrier(type.ClrFullName);
        var carrierPrefix = primitiveCarrier != null ? $"{primitiveCarrier} & " : "";

        var indexerIntersection = BuildIndexerIntersection(type, resolver, ctx);
        var thenableIntersection = BuildThenableIntersection(type);

        // BOOLEAN UNION: keep the ergonomic `boolean | Boolean$shape` surface, but avoid TS2344
        // self-constraint failures by providing a non-union shape alias that can be used in
        // recursive generic constraints (e.g. IParsable_1<TSelf extends IParsable_1<TSelf>>).
        if (type.ClrFullName == "System.Boolean")
        {
            // Shape: the branded/CLR-backed carrier (no union)
            var shapeRhs = $"{carrierPrefix}{callSignature}{finalName}$instance{typeArgs} & __{finalName}$views{typeArgs}{indexerIntersection}{thenableIntersection}";

            sb.Append("export type ");
            sb.Append(shapeName);
            sb.Append(" = ");
            sb.Append(shapeRhs);
            sb.AppendLine(";");

            sb.Append("export type ");
            sb.Append(finalName);
            sb.Append(" = boolean | ");
            sb.Append(shapeName);
            sb.AppendLine(";");

            return sb.ToString();
        }

        var rhsExpression = $"{carrierPrefix}{callSignature}{finalName}$instance{typeArgs} & __{finalName}$views{typeArgs}{indexerIntersection}{thenableIntersection}";

        // Emit the alias with constraints on LHS
        // Note: We pass the complete RHS (including type args), so we use the manual emission
        sb.Append("export type ");
        sb.Append(finalName);

        var typeParamsLHS = AliasEmit.GenerateTypeParametersWithConstraints(type, resolver, ctx);
        sb.Append(typeParamsLHS);

        sb.Append(" = ");
        sb.Append(rhsExpression);
        sb.AppendLine(";");

        return sb.ToString();
    }

    private static string BuildThenableIntersection(TypeSymbol type)
    {
        // Model Task/ValueTask as thenables for TypeScript await/async typing.
        //
        // CRITICAL: Do NOT emit `then` on the $instance interface, because Task<TResult> : Task
        // would require an override-compatible `then` signature. TS rejects that (TS2430) when
        // the awaited type differs (void vs TResult).
        //
        // Instead, we represent thenability at the type-alias level via intersection with an
        // object type containing `then` overloads.
        //
        // For generic Task<TResult>/ValueTask<TResult>, we include:
        // - awaited (TResult): so Awaited<Task<TResult>> infers TResult
        // - JsValue: a broad overload used by various TS inference paths.
        //
        // For Task<TResult> specifically, we ALSO include an `TResult | void`
        // compatibility overload so Task<TResult> remains assignable to non-generic
        // Task in TypeScript without weakening to `any`.
        //
        // Rationale: in the CLR, Task<TResult> : Task, but TypeScript's structural
        // typing for thenables would otherwise reject the assignment because
        // PromiseLike<TResult> is not assignable to PromiseLike<void>.
        //
        // IMPORTANT: We do NOT add a raw `void` overload for generic forms, because it causes
        // TS's Awaited<> helper to infer `never` (contravariant intersection of overload
        // parameter types like TResult & void & JsValue). The `TResult | void`
        // compatibility overload keeps the intersection anchored on TResult.
        //
        // For non-generic Task/ValueTask, we include:
        // - void (Awaited<Task> is void)
        // - JsValue (broad overload)
        var isTask =
            type.ClrFullName == "System.Threading.Tasks.Task" ||
            type.ClrFullName.StartsWith("System.Threading.Tasks.Task`", StringComparison.Ordinal) ||
            type.ClrFullName.StartsWith("System.Threading.Tasks.Task\u0060", StringComparison.Ordinal);

        var isValueTask =
            type.ClrFullName == "System.Threading.Tasks.ValueTask" ||
            type.ClrFullName.StartsWith("System.Threading.Tasks.ValueTask`", StringComparison.Ordinal) ||
            type.ClrFullName.StartsWith("System.Threading.Tasks.ValueTask\u0060", StringComparison.Ordinal);

        if (!isTask && !isValueTask)
            return "";

        var awaitedType =
            type.GenericParameters.Length == 1
                ? type.GenericParameters[0].Name
                : "void";

        var sb = new StringBuilder();
        sb.Append(" & {");
        sb.AppendLine();

        void EmitThenOverload(string valueType, string defaultResultType)
        {
            sb.Append("    then<TResult1 = ");
            sb.Append(defaultResultType);
            sb.Append(", TResult2 = never>(");
            sb.Append("onfulfilled?: ((value: ");
            sb.Append(valueType);
            sb.Append(") => TResult1 | PromiseLike<TResult1>) | undefined | null, ");
            sb.Append("onrejected?: ((reason: JsValue) => TResult2 | PromiseLike<TResult2>) | undefined | null");
            sb.AppendLine("): PromiseLike<TResult1 | TResult2>;");
        }

        if (type.GenericParameters.Length == 1)
        {
            EmitThenOverload(awaitedType, awaitedType);
            EmitThenOverload("JsValue", "JsValue");
            if (isTask)
            {
                EmitThenOverload($"{awaitedType} | void", awaitedType);
            }
        }
        else
        {
            EmitThenOverload("void", "void");
            EmitThenOverload("JsValue", "JsValue");
        }

        sb.Append("}");
        return sb.ToString();
    }

    private static string BuildIndexerIntersection(TypeSymbol type, TypeNameResolver resolver, BuildContext ctx)
    {
        // Indexers are represented via type-alias intersections:
        //   export type Foo = Foo$instance & __Foo$views & { [key: string]: T };
        //
        // Rationale: emitting index signatures directly inside $instance interfaces triggers TS2411
        // (all properties must be assignable to the index signature) for common BCL shapes like
        // StringDictionary, NameValueCollection, etc.
        //
        // We keep this conservative and deterministic:
        // - only instance indexers
        // - only single-parameter indexers
        // - only string/number keys
        // - if multiple representable indexers exist, prefer string over number
        var candidates = type.Members.Properties
            .Where(p => p.EmitScope == EmitScope.ClassSurface && p.IsIndexer && !p.IsStatic && p.IndexParameters.Length == 1)
            .Select(p =>
            {
                var p0 = p.IndexParameters[0];
                var rawKeyType = TypeRefPrinter.Print(p0.Type, resolver, ctx);

                string? keyType = rawKeyType switch
                {
                    "string" => "string",
                    "System_Internal.String" => "string",
                    "String" => "string",
                    "System.String" => "string",
                    // All numeric CLR indexers surface as number in TypeScript.
                    // Tsonic's proof system enforces the actual CLR numeric requirements.
                    "number" => "number",
                    "int" or "long" or "short" or "byte" or "sbyte" or "uint" or "ulong" or "ushort" or "nint" or "nuint" => "number",
                    "float" or "double" or "decimal" or "half" => "number",
                    _ => null
                };

                if (keyType == null)
                    return null;

                var valueType = TypeRefPrinter.Print(p.PropertyType, resolver, ctx);
                var keyName = string.IsNullOrWhiteSpace(p0.Name) ? "key" : p0.Name;
                var readonlyPrefix = p.HasSetter ? "" : "readonly ";
                var signature = $"{readonlyPrefix}[{keyName}: {keyType}]: {valueType};";

                return new
                {
                    KeyType = keyType,
                    Signature = signature,
                    StableId = p.StableId
                };
            })
            .Where(x => x != null)
            .Select(x => x!)
            .ToList();

        if (candidates.Count == 0)
            return "";

        // Prefer string indexers, then number. Within a key type, choose deterministically by StableId.
        var selected = candidates
            .OrderByDescending(c => c.KeyType == "string")
            .ThenBy(c => c.StableId.ToString(), StringComparer.Ordinal)
            .First();

        return $" & {{ {selected.Signature} }}";
    }

    private static string Indent(string text, string indentation)
    {
        var lines = text.Split('\n').Select(line => string.IsNullOrWhiteSpace(line) ? line : indentation + line);
        return string.Join("\n", lines);
    }

    /// <summary>
    /// Build a TypeScript call signature for a delegate type based on its Invoke method.
    /// Example: Func_2&lt;T, TResult&gt; becomes "((arg: T) => TResult)"
    /// This allows arrow functions to be assignable to delegate types.
    /// </summary>
    private static string BuildDelegateCallSignature(TypeSymbol type, TypeNameResolver resolver, BuildContext ctx)
    {
        // Find the Invoke method - this defines the delegate's signature
        var invokeMethod = type.Members.Methods.FirstOrDefault(m => m.ClrName == "Invoke");
        if (invokeMethod == null)
        {
            return ""; // Fallback: no call signature if Invoke not found
        }

        // Build allowed type parameter names set for TypeRefPrinter
        var allowedTypeParams = new HashSet<string>(type.GenericParameters.Select(gp => gp.Name));

        // Build parameter list: (arg1: T, arg2: U, ...)
        var parameters = string.Join(", ", invokeMethod.Parameters.Select(p =>
        {
            var paramType = TypeRefPrinter.Print(p.Type, resolver, ctx, allowedTypeParams);
            return $"{p.Name}: {paramType}";
        }));

        // Build return type
        var returnType = TypeRefPrinter.Print(invokeMethod.ReturnType, resolver, ctx, allowedTypeParams);

        // Return call signature: ((params) => returnType)
        return $"(({parameters}) => {returnType})";
    }

    /// <summary>
    /// Check if namespace contains any pointer or byref types that require support type markers.
    /// Scans all public types and their members for PointerTypeReference or ByRefTypeReference.
    /// </summary>
    private static bool NamespaceUsesSupportTypes(NamespaceSymbol ns)
    {
        foreach (var type in TypeEmissionAccessibility.EnumerateEmittableNamespaceTypes(ns))
        {
            // TS2304 FIX: Check constructors for unsafe types
            foreach (var ctor in type.Members.Constructors)
            {
                // Constructors are always on class surface
                foreach (var param in ctor.Parameters)
                {
                    if (ContainsUnsafeType(param.Type))
                        return true;
                }
            }

            // Check methods (only those actually emitted to class/static surface)
            foreach (var method in type.Members.Methods)
            {
                // Only check methods on class/static surface (skip ViewOnly)
                if (method.EmitScope != EmitScope.ClassSurface && method.EmitScope != EmitScope.StaticSurface)
                    continue;

                // Check return type
                if (ContainsUnsafeType(method.ReturnType))
                    return true;

                // Check parameters
                foreach (var param in method.Parameters)
                {
                    if (ContainsUnsafeType(param.Type))
                        return true;
                }
            }

            // Check properties (only those on class/static surface)
            foreach (var prop in type.Members.Properties)
            {
                if (prop.EmitScope != EmitScope.ClassSurface && prop.EmitScope != EmitScope.StaticSurface)
                    continue;

                if (ContainsUnsafeType(prop.PropertyType))
                    return true;
            }

            // Check fields (only those on class/static surface)
            foreach (var field in type.Members.Fields)
            {
                if (field.EmitScope != EmitScope.ClassSurface && field.EmitScope != EmitScope.StaticSurface)
                    continue;

                if (ContainsUnsafeType(field.FieldType))
                    return true;
            }

            // Check events (only those on class/static surface)
            foreach (var evt in type.Members.Events)
            {
                if (evt.EmitScope != EmitScope.ClassSurface && evt.EmitScope != EmitScope.StaticSurface)
                    continue;

                if (ContainsUnsafeType(evt.EventHandlerType))
                    return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Recursively check if a type reference contains pointers or byrefs.
    /// </summary>
    private static bool ContainsUnsafeType(Model.Types.TypeReference typeRef)
    {
        return typeRef switch
        {
            Model.Types.PointerTypeReference => true,
            Model.Types.ByRefTypeReference => true,
            Model.Types.ArrayTypeReference arr => ContainsUnsafeType(arr.ElementType),
            Model.Types.NamedTypeReference named => named.TypeArguments.Any(ContainsUnsafeType),
            Model.Types.NestedTypeReference nested => ContainsUnsafeType(nested.FullReference),
            _ => false
        };
    }

}
