#!/bin/bash
# Test: Primitive identity - CLR primitives are simple aliases to TS primitives
# This enables LINQ assignability: List<int> is assignable to IEnumerable<Int32>

source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

echo "Running primitive identity tests..."

# Use cached BCL output
BCL_DIR=$(ensure_bcl default)

# Create temp directory for test files
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Install required packages for noLib mode
cd "$TEMP_DIR"
npm init -y > /dev/null 2>&1
npm install --save-dev @tsonic/dotnet-globals > /dev/null 2>&1

# Create test file that simulates the real LINQ scenario
cat > "$TEMP_DIR/test.ts" << 'TESTEOF'
// Branded primitive types (from @tsonic/types)
type int = number & { __brand: "int" };
type long = number & { __brand: "long" };

// CLR primitive aliases (as now generated by tsbindgen)
// Note: Boolean maps to native boolean, but we can't alias 'boolean' in TS
// So we use a namespace to avoid conflicts with global Boolean
namespace System {
    export type Int32 = int;
    export type Int64 = long;
    export type Boolean = boolean;  // Simple alias, no wrapper!
}

// CLROf utility (as generated by tsbindgen)
// When primitives are simple aliases, CLROf becomes identity
type CLROf<T> =
    T extends int ? System.Int32 :
    T extends long ? System.Int64 :
    T extends boolean ? System.Boolean :
    T;

// ============================================================
// TEST 1: Primitive identity - CLROf<int> resolves to int
// Since Int32 = int, CLROf<int> = Int32 = int (identity)
// ============================================================
type Test1_CLROfInt = CLROf<int>;
// Compile-time assertion: CLROf<int> must be assignable to int and vice versa
const _test1a: Test1_CLROfInt = 42 as int;
const _test1b: int = 42 as Test1_CLROfInt;

// ============================================================
// TEST 2: Primitive identity - CLROf<boolean> resolves to boolean
// Since Boolean = boolean, CLROf<boolean> = Boolean = boolean (identity)
// ============================================================
type Test2_CLROfBoolean = CLROf<boolean>;
const _test2a: Test2_CLROfBoolean = true;
const _test2b: boolean = true as Test2_CLROfBoolean;

// ============================================================
// TEST 3: LINQ assignability - List<int> to IEnumerable<Int32>
// This is the exact scenario that was blocking LINQ in Tsonic
// ============================================================
// Simplified interface declarations (matching generated output)
interface IEnumerable_1$instance<T> {
    getEnumerator(): Iterator<T>;
}
type IEnumerable_1<T> = IEnumerable_1$instance<T>;

interface List_1$instance<T> extends IEnumerable_1$instance<T> {
    add(item: T): void;
    readonly count: int;
}
type List_1<T> = List_1$instance<T>;

// This MUST compile - List<int> is assignable to IEnumerable<Int32>
// Works because: List_1<int> extends IEnumerable_1<int> and Int32 = int
declare function takeEnumerable<T>(items: IEnumerable_1<T>): T[];
declare const myList: List_1<int>;
const result: System.Int32[] = takeEnumerable<System.Int32>(myList);  // <-- This was failing before

// Verify result type is compatible with int
const resultAsInt: int[] = result;  // Works because Int32 = int

// ============================================================
// TEST 4: Direct type equivalence
// List_1<Int32> should be the same type as List_1<int>
// ============================================================
const list1: List_1<System.Int32> = {} as List_1<int>;  // Works because Int32 = int
const list2: List_1<int> = {} as List_1<System.Int32>;  // Works because int = Int32

// ============================================================
// TEST 5: Boolean predicate in LINQ-style function
// Since Boolean = boolean, predicates work naturally
// ============================================================
type Func_2<T, TResult> = (arg: T) => TResult;

declare function where<T>(items: IEnumerable_1<T>, predicate: Func_2<T, System.Boolean>): IEnumerable_1<T>;

// This MUST compile - arrow returns native boolean, function expects System.Boolean
const filtered = where(myList, (x: int) => x > 0);

// All primitive identity tests passed!
TESTEOF

# Create tsconfig.json with noLib (like Tsonic uses)
cat > "$TEMP_DIR/tsconfig.json" << 'CONFIGEOF'
{
  "compilerOptions": {
    "strict": true,
    "noEmit": true,
    "noLib": true,
    "skipLibCheck": true,
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "types": ["@tsonic/dotnet-globals"]
  },
  "include": ["test.ts"]
}
CONFIGEOF

# Run TypeScript compiler
echo "  Compiling test file with tsc --strict..."
cd "$TEMP_DIR"
if run_tsc --noEmit 2>&1; then
    echo -e "${GREEN}All primitive identity tests passed!${NC}"
    echo ""
    echo "Verified:"
    echo "  - CLROf<int> resolves to int (identity)"
    echo "  - CLROf<boolean> resolves to boolean (identity)"
    echo "  - List<int> is assignable to IEnumerable<Int32>"
    echo "  - List<Int32> is same type as List<int>"
    echo "  - Boolean predicates work naturally"
    exit 0
else
    echo -e "${RED}Primitive identity tests FAILED!${NC}"
    exit 1
fi
