#!/bin/bash
# Test: TypeScript compile tests for delegate assignability
# Tests both LINQ predicate pattern and facade assign+call pattern.
# This is the exact failure scenario from Tsonic that was blocking LINQ.

source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

echo "Running TypeScript compile tests for delegate assignability..."

# Use cached BCL output
BCL_DIR=$(ensure_bcl default)

# Create temp directory for test files
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Create test file that simulates real usage
cat > "$TEMP_DIR/test.ts" << 'EOF'
// Branded int type (as generated by tsbindgen)
type int = number & { __brand: "int" };

// Internal delegate types (imported from generated output)
namespace Internal {
  export type Func_1<TResult> = () => TResult;
  export type Func_2<T, TResult> = (arg: T) => TResult;
  export type Func_3<T1, T2, TResult> = (arg1: T1, arg2: T2) => TResult;
  export type Action = () => void;
  export type Action_1<T> = (obj: T) => void;
  export type Action_2<T1, T2> = (arg1: T1, arg2: T2) => void;
}

// Sentinel for unspecified type parameters
declare const __unspecified: unique symbol;
type __ = typeof __unspecified;

// Facade pattern (as in System/index.d.ts)
type Func<
  T1 = __,
  T2 = __,
  T3 = __,
  T4 = __,
> =
  [T2] extends [__] ? ((() => T1) | Internal.Func_1<T1>) :
  [T3] extends [__] ? (((arg1: T1) => T2) | Internal.Func_2<T1, T2>) :
  [T4] extends [__] ? (((arg1: T1, arg2: T2) => T3) | Internal.Func_3<T1, T2, T3>) :
  never;

type Action<
  T1 = __,
  T2 = __,
  T3 = __,
> =
  [T1] extends [__] ? ((() => void) | Internal.Action) :
  [T2] extends [__] ? (((arg1: T1) => void) | Internal.Action_1<T1>) :
  [T3] extends [__] ? (((arg1: T1, arg2: T2) => void) | Internal.Action_2<T1, T2>) :
  never;

// ============================================================
// TEST 1: LINQ predicate pattern (the exact Tsonic failure)
// ============================================================
// This is what Enumerable.where() looks like
declare function where<T>(source: T[], predicate: Internal.Func_2<T, boolean>): T[];

const numbers: number[] = [1, 2, 3, 4, 5];

// This MUST compile - it's the exact pattern that was failing
const evens = where(numbers, (x: number) => x % 2 === 0);

// ============================================================
// TEST 2: Facade assign + call (fundamental requirement)
// ============================================================

// Assignment - arrow function to Func<int, int>
const f: Func<int, int> = (x: int) => (x + 1) as int;

// Callability - must be callable
const y: int = f(5 as int);

// Action assignment + call
const a: Action<int> = (x: int) => { console.log(x); };
a(1 as int);

// ============================================================
// TEST 3: Direct internal type usage
// ============================================================
const directFunc: Internal.Func_2<int, int> = (x: int) => (x * 2) as int;
const directResult: int = directFunc(3 as int);

const directAction: Internal.Action_1<string> = (s: string) => console.log(s);
directAction("hello");

// ============================================================
// TEST 4: Multiple parameters
// ============================================================
const add: Func<int, int, int> = (a: int, b: int) => ((a as number) + (b as number)) as int;
const sum: int = add(1 as int, 2 as int);

// ============================================================
// TEST 5: Boolean return type (native boolean → CLR Boolean)
// Arrow functions naturally return native 'boolean', but Func_2<T, CLRBoolean>
// expects CLR Boolean. The Boolean union fix makes this work.
// ============================================================
// Simulated CLR Boolean type (union with native boolean)
// Named CLRBoolean to avoid conflict with global Boolean
namespace CLR {
  interface Boolean$instance { readonly __clr: "Boolean"; }
  interface __Boolean$views { As_IComparable(): unknown; }
  export type Boolean = boolean | (Boolean$instance & __Boolean$views);
}

// This MUST compile - arrow returns native boolean, Func expects CLR Boolean
declare function takesBoolPred(p: Internal.Func_2<number, CLR.Boolean>): void;
takesBoolPred(x => x % 2 === 0);

// Also test with facade pattern
declare function takesFacadeBoolPred(p: Func<number, CLR.Boolean>): void;
takesFacadeBoolPred(x => x > 0);

console.log("All TypeScript compile tests passed!");
EOF

# Create tsconfig.json
cat > "$TEMP_DIR/tsconfig.json" << 'EOF'
{
  "compilerOptions": {
    "strict": true,
    "noEmit": true,
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node"
  },
  "include": ["test.ts"]
}
EOF

# Run TypeScript compiler
echo "  Compiling test file with tsc --strict..."
cd "$TEMP_DIR"
if run_tsc --noEmit 2>&1; then
    echo -e "${GREEN}All TypeScript compile tests passed!${NC}"
    echo ""
    echo "Verified:"
    echo "  - LINQ predicate pattern: where(numbers, (x) => x % 2 === 0)"
    echo "  - Facade assign: const f: Func<int, int> = (x) => x + 1"
    echo "  - Facade call: f(5 as int)"
    echo "  - Action assign + call"
    echo "  - Direct internal type usage"
    echo "  - Boolean return type: takesBoolPred(x => x % 2 === 0)"
    exit 0
else
    echo -e "${RED}TypeScript compile tests FAILED!${NC}"
    exit 1
fi
