#!/bin/bash
# Test: TypeScript compile tests for delegate assignability
# Tests both LINQ predicate pattern and facade assign+call pattern.
# This is the exact failure scenario from Tsonic that was blocking LINQ.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "Running TypeScript compile tests for delegate assignability..."

# Create temp directory for tests
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Generate BCL namespaces needed for tests
RUNTIME_DIR="/home/jeswin/dotnet/shared/Microsoft.NETCore.App/10.0.0-rc.1.25451.107"
OUT_DIR="$TEMP_DIR/generated"

echo "  Generating BCL namespaces..."
dotnet run --project "$PROJECT_ROOT/src/tsbindgen/tsbindgen.csproj" -- \
    generate -a "$RUNTIME_DIR/System.Private.CoreLib.dll" \
    --out-dir "$OUT_DIR" > /dev/null 2>&1

# Create test file that simulates real usage
cat > "$TEMP_DIR/test.ts" << 'EOF'
// Branded int type (as generated by tsbindgen)
type int = number & { __brand: "int" };

// Internal delegate types (imported from generated output)
namespace Internal {
  export type Func_1<TResult> = () => TResult;
  export type Func_2<T, TResult> = (arg: T) => TResult;
  export type Func_3<T1, T2, TResult> = (arg1: T1, arg2: T2) => TResult;
  export type Action = () => void;
  export type Action_1<T> = (obj: T) => void;
  export type Action_2<T1, T2> = (arg1: T1, arg2: T2) => void;
}

// Sentinel for unspecified type parameters
declare const __unspecified: unique symbol;
type __ = typeof __unspecified;

// Facade pattern (as in System/index.d.ts)
type Func<
  T1 = __,
  T2 = __,
  T3 = __,
  T4 = __,
> =
  [T2] extends [__] ? ((() => T1) | Internal.Func_1<T1>) :
  [T3] extends [__] ? (((arg1: T1) => T2) | Internal.Func_2<T1, T2>) :
  [T4] extends [__] ? (((arg1: T1, arg2: T2) => T3) | Internal.Func_3<T1, T2, T3>) :
  never;

type Action<
  T1 = __,
  T2 = __,
  T3 = __,
> =
  [T1] extends [__] ? ((() => void) | Internal.Action) :
  [T2] extends [__] ? (((arg1: T1) => void) | Internal.Action_1<T1>) :
  [T3] extends [__] ? (((arg1: T1, arg2: T2) => void) | Internal.Action_2<T1, T2>) :
  never;

// ============================================================
// TEST 1: LINQ predicate pattern (the exact Tsonic failure)
// ============================================================
// This is what Enumerable.where() looks like
declare function where<T>(source: T[], predicate: Internal.Func_2<T, boolean>): T[];

const numbers: number[] = [1, 2, 3, 4, 5];

// This MUST compile - it's the exact pattern that was failing
const evens = where(numbers, (x: number) => x % 2 === 0);

// ============================================================
// TEST 2: Facade assign + call (fundamental requirement)
// ============================================================

// Assignment - arrow function to Func<int, int>
const f: Func<int, int> = (x: int) => (x + 1) as int;

// Callability - must be callable
const y: int = f(5 as int);

// Action assignment + call
const a: Action<int> = (x: int) => { console.log(x); };
a(1 as int);

// ============================================================
// TEST 3: Direct internal type usage
// ============================================================
const directFunc: Internal.Func_2<int, int> = (x: int) => (x * 2) as int;
const directResult: int = directFunc(3 as int);

const directAction: Internal.Action_1<string> = (s: string) => console.log(s);
directAction("hello");

// ============================================================
// TEST 4: Multiple parameters
// ============================================================
const add: Func<int, int, int> = (a: int, b: int) => ((a as number) + (b as number)) as int;
const sum: int = add(1 as int, 2 as int);

console.log("All TypeScript compile tests passed!");
EOF

# Create tsconfig.json
cat > "$TEMP_DIR/tsconfig.json" << 'EOF'
{
  "compilerOptions": {
    "strict": true,
    "noEmit": true,
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node"
  },
  "include": ["test.ts"]
}
EOF

# Run TypeScript compiler
echo "  Compiling test file with tsc --strict..."
cd "$TEMP_DIR"
if npx tsc --noEmit 2>&1; then
    echo -e "${GREEN}All TypeScript compile tests passed!${NC}"
    echo ""
    echo "Verified:"
    echo "  - LINQ predicate pattern: where(numbers, (x) => x % 2 === 0)"
    echo "  - Facade assign: const f: Func<int, int> = (x) => x + 1"
    echo "  - Facade call: f(5 as int)"
    echo "  - Action assign + call"
    echo "  - Direct internal type usage"
    exit 0
else
    echo -e "${RED}TypeScript compile tests FAILED!${NC}"
    exit 1
fi
